/**
 * Clinical Demo Seed — بيانات سريرية تجريبية
 *
 * One coherent hospital day. The cohort is deliberately small and deeply
 * linked rather than large and shallow: every patient here has a story that
 * crosses modules, so opening any screen shows real consequences of what
 * happened on another.
 *
 *   pt-01  Khalid Al-Otaibi   ED chest pain → admitted CCU → troponin rising
 *   pt-02  Maryam Al-Ghamdi   Post-op day 1, laparoscopic cholecystectomy
 *   pt-03  Fatima Al-Harbi    Diabetic outpatient, renal impairment, dose alerts
 *   pt-04  Noura Al-Qahtani   Maternity, term, for elective section
 *   pt-05  Yousef Al-Dosari   Paediatric asthma, ED short stay
 *   pt-06  Abdullah Al-Shehri ICU, ventilated, sepsis
 *   pt-07  Sara Al-Mutairi    Day case, cataract, discharged
 *   pt-08  Ibrahim Al-Zahrani Orthopaedic, awaiting theatre
 *   pt-09  Hessa Al-Subaie    Oncology day unit, chemotherapy
 *   pt-10  Majed Al-Rashid    ED waiting, ankle injury, fast-track
 *   pt-11  Layla Al-Anazi     Telehealth follow-up, dermatology
 *   pt-12  Turki Al-Malki     ED triage 2, breathing difficulty
 *   pt-13  Reem Al-Faisal     Outpatient clinic, thyroid
 *   pt-14  Saud Al-Amri       Discharged yesterday, claim in progress
 *
 * All IDs are stable so cross-module links never dangle.
 */

import type { Database } from "@/domain/types";

type T<K extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][K]["Row"];

const W = "demo";

/** Date helpers — everything is relative so the demo never looks stale. */
const d = (daysAgo: number) => new Date(Date.now() - daysAgo * 86_400_000).toISOString().slice(0, 10);
const ts = (daysAgo: number) => new Date(Date.now() - daysAgo * 86_400_000).toISOString();
const hrs = (hoursAgo: number) => new Date(Date.now() - hoursAgo * 3_600_000).toISOString();
const mins = (minutesAgo: number) => new Date(Date.now() - minutesAgo * 60_000).toISOString();
/** Forward-dated, for scheduled things. */
const inHrs = (hoursAhead: number) => new Date(Date.now() + hoursAhead * 3_600_000).toISOString();
const inDays = (daysAhead: number) => new Date(Date.now() + daysAhead * 86_400_000).toISOString();
/** A fixed birth date `years` ago, so ages stay stable within a session. */
const dob = (years: number, month = 5, day = 12) =>
  `${new Date().getFullYear() - years}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;

// ─── Departments ──────────────────────────────────────────

export const DEMO_DEPARTMENTS: T<"departments">[] = [
  { id: "dept-01", workspace_id: W, code: "EMRG", name_en: "Emergency Medicine", name_ar: "الطوارئ", department_type: "clinical", branch_id: "br-01", head_provider_id: "prov-03", head_provider_name: "Dr. Nasser Al-Juhani", cost_centre: "CC-1100", location: "Ground Floor, East Wing", phone_extension: "1100", accepts_appointments: false, status: "active", metadata: {}, created_at: ts(400), updated_at: ts(3) },
  { id: "dept-02", workspace_id: W, code: "CARD", name_en: "Cardiology", name_ar: "القلب", department_type: "clinical", branch_id: "br-01", head_provider_id: "prov-01", head_provider_name: "Dr. Hala Al-Rasheed", cost_centre: "CC-1200", location: "Floor 3, North", phone_extension: "1200", accepts_appointments: true, status: "active", metadata: {}, created_at: ts(400), updated_at: ts(8) },
  { id: "dept-03", workspace_id: W, code: "SURG", name_en: "General Surgery", name_ar: "الجراحة العامة", department_type: "clinical", branch_id: "br-01", head_provider_id: "prov-02", head_provider_name: "Dr. Faisal Al-Harthy", cost_centre: "CC-1300", location: "Floor 4, West", phone_extension: "1300", accepts_appointments: true, status: "active", metadata: {}, created_at: ts(400), updated_at: ts(12) },
  { id: "dept-04", workspace_id: W, code: "ICU", name_en: "Intensive Care", name_ar: "العناية المركزة", department_type: "clinical", branch_id: "br-01", head_provider_id: "prov-06", head_provider_name: "Dr. Omar Bin Salem", cost_centre: "CC-1400", location: "Floor 2, Central", phone_extension: "1400", accepts_appointments: false, status: "active", metadata: {}, created_at: ts(400), updated_at: ts(2) },
  { id: "dept-05", workspace_id: W, code: "OBGY", name_en: "Obstetrics & Gynaecology", name_ar: "النساء والولادة", department_type: "clinical", branch_id: "br-01", head_provider_id: "prov-07", head_provider_name: "Dr. Amal Al-Shamrani", cost_centre: "CC-1500", location: "Floor 5", phone_extension: "1500", accepts_appointments: true, status: "active", metadata: {}, created_at: ts(400), updated_at: ts(20) },
  { id: "dept-06", workspace_id: W, code: "PAED", name_en: "Paediatrics", name_ar: "الأطفال", department_type: "clinical", branch_id: "br-01", head_provider_id: "prov-08", head_provider_name: "Dr. Rana Al-Suwailem", cost_centre: "CC-1600", location: "Floor 6", phone_extension: "1600", accepts_appointments: true, status: "active", metadata: {}, created_at: ts(400), updated_at: ts(15) },
  { id: "dept-07", workspace_id: W, code: "ORTH", name_en: "Orthopaedics", name_ar: "العظام", department_type: "clinical", branch_id: "br-01", head_provider_id: "prov-09", head_provider_name: "Dr. Bandar Al-Otaibi", cost_centre: "CC-1700", location: "Floor 4, East", phone_extension: "1700", accepts_appointments: true, status: "active", metadata: {}, created_at: ts(400), updated_at: ts(30) },
  { id: "dept-08", workspace_id: W, code: "LAB", name_en: "Laboratory", name_ar: "المختبر", department_type: "ancillary", branch_id: "br-01", head_provider_id: "prov-10", head_provider_name: "Dr. Salma Al-Hazmi", cost_centre: "CC-2100", location: "Basement 1", phone_extension: "2100", accepts_appointments: false, status: "active", metadata: {}, created_at: ts(400), updated_at: ts(1) },
  { id: "dept-09", workspace_id: W, code: "RAD", name_en: "Radiology", name_ar: "الأشعة", department_type: "ancillary", branch_id: "br-01", head_provider_id: "prov-11", head_provider_name: "Dr. Tariq Al-Balawi", cost_centre: "CC-2200", location: "Ground Floor, West", phone_extension: "2200", accepts_appointments: true, status: "active", metadata: {}, created_at: ts(400), updated_at: ts(1) },
  { id: "dept-10", workspace_id: W, code: "PHAR", name_en: "Pharmacy", name_ar: "الصيدلية", department_type: "ancillary", branch_id: "br-01", head_provider_id: "prov-12", head_provider_name: "Dr. Huda Al-Qarni", cost_centre: "CC-2300", location: "Ground Floor, Central", phone_extension: "2300", accepts_appointments: false, status: "active", metadata: {}, created_at: ts(400), updated_at: ts(1) },
  { id: "dept-11", workspace_id: W, code: "THTR", name_en: "Operating Theatres", name_ar: "غرف العمليات", department_type: "clinical", branch_id: "br-01", head_provider_id: "prov-02", head_provider_name: "Dr. Faisal Al-Harthy", cost_centre: "CC-1800", location: "Floor 2, West", phone_extension: "1800", accepts_appointments: false, status: "active", metadata: {}, created_at: ts(400), updated_at: ts(4) },
  { id: "dept-12", workspace_id: W, code: "ONCO", name_en: "Oncology Day Unit", name_ar: "وحدة الأورام النهارية", department_type: "clinical", branch_id: "br-01", head_provider_id: "prov-13", head_provider_name: "Dr. Ziad Al-Mansour", cost_centre: "CC-1900", location: "Floor 7", phone_extension: "1900", accepts_appointments: true, status: "active", metadata: {}, created_at: ts(400), updated_at: ts(9) },
  { id: "dept-13", workspace_id: W, code: "DERM", name_en: "Dermatology", name_ar: "الجلدية", department_type: "clinical", branch_id: "br-02", head_provider_id: "prov-14", head_provider_name: "Dr. Lina Al-Yousef", cost_centre: "CC-2000", location: "Clinic Block, Floor 1", phone_extension: "2000", accepts_appointments: true, status: "active", metadata: {}, created_at: ts(400), updated_at: ts(11) },
  { id: "dept-14", workspace_id: W, code: "BIOM", name_en: "Biomedical Engineering", name_ar: "الهندسة الطبية", department_type: "support", branch_id: "br-01", head_provider_id: null, head_provider_name: "Eng. Mishal Al-Ruwaili", cost_centre: "CC-3100", location: "Basement 2", phone_extension: "3100", accepts_appointments: false, status: "active", metadata: {}, created_at: ts(400), updated_at: ts(6) },
  { id: "dept-15", workspace_id: W, code: "RCM", name_en: "Revenue Cycle", name_ar: "الدورة الإيرادية", department_type: "administrative", branch_id: "br-01", head_provider_id: null, head_provider_name: "Mr. Waleed Al-Sudairi", cost_centre: "CC-4100", location: "Admin Block, Floor 2", phone_extension: "4100", accepts_appointments: false, status: "active", metadata: {}, created_at: ts(400), updated_at: ts(2) },
];

// ─── Providers ────────────────────────────────────────────

export const DEMO_PROVIDERS: T<"providers">[] = [
  { id: "prov-01", workspace_id: W, employee_id: "emp-01", name_en: "Dr. Hala Al-Rasheed", name_ar: "د. هالة الرشيد", title: "Consultant", provider_type: "physician", speciality_en: "Interventional Cardiology", speciality_ar: "قسطرة القلب", department_id: "dept-02", department_name: "Cardiology", license_number: "SCFHS-114872", license_authority: "SCFHS", license_expiry: d(-420), credential_status: "verified", credentialed_at: ts(300), employment_type: "consultant", can_prescribe: true, dea_number: null, phone: "+966-55-410-0001", email: "h.rasheed@alobour.sa", photo_url: null, languages: ["ar", "en"], status: "active", metadata: { on_call: true }, created_at: ts(400), updated_at: ts(3) },
  { id: "prov-02", workspace_id: W, employee_id: "emp-02", name_en: "Dr. Faisal Al-Harthy", name_ar: "د. فيصل الحارثي", title: "Consultant", provider_type: "surgeon", speciality_en: "Laparoscopic Surgery", speciality_ar: "الجراحة بالمنظار", department_id: "dept-03", department_name: "General Surgery", license_number: "SCFHS-108341", license_authority: "SCFHS", license_expiry: d(-95), credential_status: "verified", credentialed_at: ts(280), employment_type: "consultant", can_prescribe: true, dea_number: null, phone: "+966-55-410-0002", email: "f.harthy@alobour.sa", photo_url: null, languages: ["ar", "en"], status: "active", metadata: {}, created_at: ts(400), updated_at: ts(4) },
  { id: "prov-03", workspace_id: W, employee_id: null, name_en: "Dr. Nasser Al-Juhani", name_ar: "د. ناصر الجهني", title: "Consultant", provider_type: "physician", speciality_en: "Emergency Medicine", speciality_ar: "طب الطوارئ", department_id: "dept-01", department_name: "Emergency Medicine", license_number: "SCFHS-121905", license_authority: "SCFHS", license_expiry: d(-610), credential_status: "verified", credentialed_at: ts(360), employment_type: "full_time", can_prescribe: true, dea_number: null, phone: "+966-55-410-0003", email: "n.juhani@alobour.sa", photo_url: null, languages: ["ar", "en"], status: "active", metadata: { on_call: true }, created_at: ts(400), updated_at: ts(1) },
  { id: "prov-04", workspace_id: W, employee_id: null, name_en: "Dr. Maha Al-Sanea", name_ar: "د. مها الصانع", title: "Specialist", provider_type: "physician", speciality_en: "Internal Medicine", speciality_ar: "الباطنة", department_id: "dept-02", department_name: "Cardiology", license_number: "SCFHS-133220", license_authority: "SCFHS", license_expiry: d(22), credential_status: "expired", credentialed_at: ts(700), employment_type: "full_time", can_prescribe: false, dea_number: null, phone: "+966-55-410-0004", email: "m.sanea@alobour.sa", photo_url: null, languages: ["ar"], status: "active", metadata: { blocked_reason: "License lapsed — renewal submitted to SCFHS" }, created_at: ts(700), updated_at: ts(1) },
  { id: "prov-05", workspace_id: W, employee_id: null, name_en: "Nurse Aisha Al-Dakhil", name_ar: "الممرضة عائشة الدخيل", title: "Charge Nurse", provider_type: "nurse", speciality_en: "Critical Care Nursing", speciality_ar: "تمريض العناية المركزة", department_id: "dept-04", department_name: "Intensive Care", license_number: "SCFHS-N-40218", license_authority: "SCFHS", license_expiry: d(-500), credential_status: "verified", credentialed_at: ts(320), employment_type: "full_time", can_prescribe: false, dea_number: null, phone: "+966-55-410-0005", email: "a.dakhil@alobour.sa", photo_url: null, languages: ["ar", "en"], status: "active", metadata: {}, created_at: ts(400), updated_at: ts(1) },
  { id: "prov-06", workspace_id: W, employee_id: null, name_en: "Dr. Omar Bin Salem", name_ar: "د. عمر بن سالم", title: "Consultant", provider_type: "physician", speciality_en: "Critical Care", speciality_ar: "العناية المركزة", department_id: "dept-04", department_name: "Intensive Care", license_number: "SCFHS-117044", license_authority: "SCFHS", license_expiry: d(-380), credential_status: "verified", credentialed_at: ts(290), employment_type: "consultant", can_prescribe: true, dea_number: null, phone: "+966-55-410-0006", email: "o.binsalem@alobour.sa", photo_url: null, languages: ["ar", "en"], status: "active", metadata: { on_call: true }, created_at: ts(400), updated_at: ts(1) },
  { id: "prov-07", workspace_id: W, employee_id: null, name_en: "Dr. Amal Al-Shamrani", name_ar: "د. أمل الشمراني", title: "Consultant", provider_type: "physician", speciality_en: "Obstetrics", speciality_ar: "التوليد", department_id: "dept-05", department_name: "Obstetrics & Gynaecology", license_number: "SCFHS-119873", license_authority: "SCFHS", license_expiry: d(-250), credential_status: "verified", credentialed_at: ts(310), employment_type: "consultant", can_prescribe: true, dea_number: null, phone: "+966-55-410-0007", email: "a.shamrani@alobour.sa", photo_url: null, languages: ["ar", "en"], status: "active", metadata: {}, created_at: ts(400), updated_at: ts(7) },
  { id: "prov-08", workspace_id: W, employee_id: null, name_en: "Dr. Rana Al-Suwailem", name_ar: "د. رنا السويلم", title: "Consultant", provider_type: "physician", speciality_en: "Paediatrics", speciality_ar: "طب الأطفال", department_id: "dept-06", department_name: "Paediatrics", license_number: "SCFHS-125618", license_authority: "SCFHS", license_expiry: d(-190), credential_status: "verified", credentialed_at: ts(300), employment_type: "full_time", can_prescribe: true, dea_number: null, phone: "+966-55-410-0008", email: "r.suwailem@alobour.sa", photo_url: null, languages: ["ar", "en"], status: "active", metadata: {}, created_at: ts(400), updated_at: ts(2) },
  { id: "prov-09", workspace_id: W, employee_id: null, name_en: "Dr. Bandar Al-Otaibi", name_ar: "د. بندر العتيبي", title: "Consultant", provider_type: "surgeon", speciality_en: "Orthopaedic Surgery", speciality_ar: "جراحة العظام", department_id: "dept-07", department_name: "Orthopaedics", license_number: "SCFHS-110992", license_authority: "SCFHS", license_expiry: d(-45), credential_status: "verified", credentialed_at: ts(270), employment_type: "visiting", can_prescribe: true, dea_number: null, phone: "+966-55-410-0009", email: "b.otaibi@alobour.sa", photo_url: null, languages: ["ar"], status: "active", metadata: {}, created_at: ts(400), updated_at: ts(5) },
  { id: "prov-10", workspace_id: W, employee_id: null, name_en: "Dr. Salma Al-Hazmi", name_ar: "د. سلمى الحازمي", title: "Consultant", provider_type: "pathologist", speciality_en: "Clinical Pathology", speciality_ar: "علم الأمراض السريري", department_id: "dept-08", department_name: "Laboratory", license_number: "SCFHS-113456", license_authority: "SCFHS", license_expiry: d(-320), credential_status: "verified", credentialed_at: ts(300), employment_type: "full_time", can_prescribe: false, dea_number: null, phone: "+966-55-410-0010", email: "s.hazmi@alobour.sa", photo_url: null, languages: ["ar", "en"], status: "active", metadata: {}, created_at: ts(400), updated_at: ts(1) },
  { id: "prov-11", workspace_id: W, employee_id: null, name_en: "Dr. Tariq Al-Balawi", name_ar: "د. طارق البلوي", title: "Consultant", provider_type: "radiologist", speciality_en: "Diagnostic Radiology", speciality_ar: "الأشعة التشخيصية", department_id: "dept-09", department_name: "Radiology", license_number: "SCFHS-116230", license_authority: "SCFHS", license_expiry: d(-410), credential_status: "verified", credentialed_at: ts(300), employment_type: "full_time", can_prescribe: false, dea_number: null, phone: "+966-55-410-0011", email: "t.balawi@alobour.sa", photo_url: null, languages: ["ar", "en"], status: "active", metadata: {}, created_at: ts(400), updated_at: ts(1) },
  { id: "prov-12", workspace_id: W, employee_id: null, name_en: "Dr. Huda Al-Qarni", name_ar: "د. هدى القرني", title: "Chief Pharmacist", provider_type: "pharmacist", speciality_en: "Clinical Pharmacy", speciality_ar: "الصيدلة السريرية", department_id: "dept-10", department_name: "Pharmacy", license_number: "SCFHS-P-22114", license_authority: "SCFHS", license_expiry: d(-280), credential_status: "verified", credentialed_at: ts(300), employment_type: "full_time", can_prescribe: false, dea_number: null, phone: "+966-55-410-0012", email: "h.qarni@alobour.sa", photo_url: null, languages: ["ar", "en"], status: "active", metadata: {}, created_at: ts(400), updated_at: ts(1) },
  { id: "prov-13", workspace_id: W, employee_id: null, name_en: "Dr. Ziad Al-Mansour", name_ar: "د. زياد المنصور", title: "Consultant", provider_type: "physician", speciality_en: "Medical Oncology", speciality_ar: "أورام الباطنة", department_id: "dept-12", department_name: "Oncology Day Unit", license_number: "SCFHS-118776", license_authority: "SCFHS", license_expiry: d(-150), credential_status: "verified", credentialed_at: ts(290), employment_type: "consultant", can_prescribe: true, dea_number: null, phone: "+966-55-410-0013", email: "z.mansour@alobour.sa", photo_url: null, languages: ["ar", "en"], status: "active", metadata: {}, created_at: ts(400), updated_at: ts(6) },
  { id: "prov-14", workspace_id: W, employee_id: null, name_en: "Dr. Lina Al-Yousef", name_ar: "د. لينا اليوسف", title: "Specialist", provider_type: "physician", speciality_en: "Dermatology", speciality_ar: "الأمراض الجلدية", department_id: "dept-13", department_name: "Dermatology", license_number: "SCFHS-128904", license_authority: "SCFHS", license_expiry: d(-75), credential_status: "verified", credentialed_at: ts(250), employment_type: "part_time", can_prescribe: true, dea_number: null, phone: "+966-55-410-0014", email: "l.yousef@alobour.sa", photo_url: null, languages: ["ar", "en"], status: "active", metadata: { telehealth_enabled: true }, created_at: ts(400), updated_at: ts(3) },
  { id: "prov-15", workspace_id: W, employee_id: null, name_en: "Nurse Khalid Al-Ruwais", name_ar: "الممرض خالد الرويس", title: "Triage Nurse", provider_type: "nurse", speciality_en: "Emergency Nursing", speciality_ar: "تمريض الطوارئ", department_id: "dept-01", department_name: "Emergency Medicine", license_number: "SCFHS-N-41903", license_authority: "SCFHS", license_expiry: d(-330), credential_status: "verified", credentialed_at: ts(300), employment_type: "full_time", can_prescribe: false, dea_number: null, phone: "+966-55-410-0015", email: "k.ruwais@alobour.sa", photo_url: null, languages: ["ar", "en"], status: "active", metadata: {}, created_at: ts(400), updated_at: ts(1) },
  { id: "prov-16", workspace_id: W, employee_id: null, name_en: "Dr. Yasser Al-Habib", name_ar: "د. ياسر الحبيب", title: "Consultant", provider_type: "physician", speciality_en: "Anaesthesia", speciality_ar: "التخدير", department_id: "dept-11", department_name: "Operating Theatres", license_number: "SCFHS-112087", license_authority: "SCFHS", license_expiry: d(-30), credential_status: "pending", credentialed_at: null, employment_type: "locum", can_prescribe: true, dea_number: null, phone: "+966-55-410-0016", email: "y.habib@alobour.sa", photo_url: null, languages: ["ar", "en"], status: "active", metadata: { note: "Renewal in committee — expires in 30 days" }, created_at: ts(200), updated_at: ts(2) },
];

// ─── Wards & beds ─────────────────────────────────────────

export const DEMO_WARDS: T<"wards">[] = [
  { id: "wd-01", workspace_id: W, code: "CCU", name_en: "Coronary Care Unit", name_ar: "وحدة العناية القلبية", branch_id: "br-01", floor: "3", speciality: "Cardiology", ward_type: "hdu", bed_count: 8, sex_restriction: "mixed", charge_nurse_id: "prov-05", status: "open", metadata: {}, created_at: ts(400), updated_at: ts(1) },
  { id: "wd-02", workspace_id: W, code: "SURG-A", name_en: "Surgical Ward A", name_ar: "جناح الجراحة أ", branch_id: "br-01", floor: "4", speciality: "General Surgery", ward_type: "surgical", bed_count: 12, sex_restriction: "mixed", charge_nurse_id: null, status: "open", metadata: {}, created_at: ts(400), updated_at: ts(1) },
  { id: "wd-03", workspace_id: W, code: "ICU", name_en: "Intensive Care Unit", name_ar: "وحدة العناية المركزة", branch_id: "br-01", floor: "2", speciality: "Critical Care", ward_type: "icu", bed_count: 10, sex_restriction: "mixed", charge_nurse_id: "prov-05", status: "open", metadata: {}, created_at: ts(400), updated_at: ts(1) },
  { id: "wd-04", workspace_id: W, code: "MAT", name_en: "Maternity Ward", name_ar: "جناح الولادة", branch_id: "br-01", floor: "5", speciality: "Obstetrics", ward_type: "maternity", bed_count: 10, sex_restriction: "female", charge_nurse_id: null, status: "open", metadata: {}, created_at: ts(400), updated_at: ts(1) },
  { id: "wd-05", workspace_id: W, code: "PAED", name_en: "Paediatric Ward", name_ar: "جناح الأطفال", branch_id: "br-01", floor: "6", speciality: "Paediatrics", ward_type: "general", bed_count: 8, sex_restriction: "mixed", charge_nurse_id: null, status: "open", metadata: {}, created_at: ts(400), updated_at: ts(1) },
  { id: "wd-06", workspace_id: W, code: "ISO", name_en: "Isolation Unit", name_ar: "وحدة العزل", branch_id: "br-01", floor: "2", speciality: "Infection Control", ward_type: "isolation", bed_count: 4, sex_restriction: "mixed", charge_nurse_id: null, status: "partial", metadata: { note: "Two bays closed for deep clean" }, created_at: ts(400), updated_at: ts(1) },
];

/**
 * Beds are generated so the occupancy board has realistic volume, then the
 * ones that matter clinically are overridden below. A hand-written list of
 * 52 beds would be noise; the overrides are the part worth reading.
 */
function generateBeds(): T<"beds">[] {
  const spec: [wardId: string, wardName: string, count: number, type: T<"beds">["bed_type"], prefix: string][] = [
    ["wd-01", "Coronary Care Unit", 8, "icu", "CCU"],
    ["wd-02", "Surgical Ward A", 12, "standard", "SA"],
    ["wd-03", "Intensive Care Unit", 10, "icu", "ICU"],
    ["wd-04", "Maternity Ward", 10, "standard", "MAT"],
    ["wd-05", "Paediatric Ward", 8, "paediatric", "PD"],
    ["wd-06", "Isolation Unit", 4, "isolation", "ISO"],
  ];
  const beds: T<"beds">[] = [];
  for (const [wardId, wardName, count, type, prefix] of spec) {
    for (let i = 1; i <= count; i++) {
      // A deterministic spread: roughly 60% occupied, some cleaning, some free.
      const cycle = i % 5;
      const status: T<"beds">["status"] =
        cycle === 0 ? "cleaning" : cycle === 4 ? "available" : "occupied";
      beds.push({
        id: `bed-${prefix}-${String(i).padStart(2, "0")}`,
        workspace_id: W, ward_id: wardId, ward_name: wardName,
        room: `${prefix}-${Math.ceil(i / 2)}`, label: `${prefix}-${String(i).padStart(2, "0")}`,
        bed_type: type, status,
        current_encounter_id: null,
        current_patient_name: status === "occupied" ? "—" : null,
        occupied_since: status === "occupied" ? hrs(6 + (i % 40)) : null,
        reserved_until: null,
        has_oxygen: type === "icu" || type === "isolation" || i % 3 === 0,
        has_monitor: type === "icu",
        metadata: {}, created_at: ts(400), updated_at: hrs(i % 12),
      });
    }
  }
  return beds;
}

const beds = generateBeds();

/** The beds our cohort actually occupies, patched onto the generated grid. */
const BED_ASSIGNMENTS: [bedId: string, encounterId: string, patientName: string, hoursOccupied: number][] = [
  ["bed-CCU-01", "enc-01", "Khalid Al-Otaibi", 9],
  ["bed-SA-01", "enc-02", "Maryam Al-Ghamdi", 28],
  ["bed-ICU-02", "enc-06", "Abdullah Al-Shehri", 76],
  ["bed-MAT-03", "enc-04", "Noura Al-Qahtani", 14],
  ["bed-PD-02", "enc-05", "Yousef Al-Dosari", 5],
  ["bed-SA-06", "enc-08", "Ibrahim Al-Zahrani", 20],
];

for (const [bedId, encId, name, hoursOccupied] of BED_ASSIGNMENTS) {
  const bed = beds.find((b) => b.id === bedId);
  if (bed) {
    bed.status = "occupied";
    bed.current_encounter_id = encId;
    bed.current_patient_name = name;
    bed.occupied_since = hrs(hoursOccupied);
  }
}

// A blocked bay, so the board shows why capacity is short.
const isoBed = beds.find((b) => b.id === "bed-ISO-03");
if (isoBed) {
  isoBed.status = "blocked";
  isoBed.current_encounter_id = null;
  isoBed.current_patient_name = null;
  isoBed.occupied_since = null;
  isoBed.metadata = { blocked_reason: "Awaiting HEPA filter replacement — BIOM-WO-0231" };
}

export const DEMO_BEDS = beds;

// ─── Patients ─────────────────────────────────────────────

export const DEMO_PATIENTS: T<"patients">[] = [
  { id: "pt-01", workspace_id: W, mrn: "MRN-100241", name_en: "Khalid Al-Otaibi", name_ar: "خالد العتيبي", date_of_birth: dob(58, 3, 14), sex: "male", national_id: "1042887531", phone: "+966-50-771-2201", email: "k.otaibi@example.sa", address_en: "Al Malaz, Riyadh", address_ar: "الملز، الرياض", blood_group: "O+", allergy_summary: "Penicillin — rash", next_of_kin_name: "Munira Al-Otaibi", next_of_kin_phone: "+966-50-771-2299", next_of_kin_relation: "Spouse", preferred_language: "ar", status: "active", merged_into_id: null, vip_flag: false, photo_url: null, registered_at: ts(1200), tags: ["cardiac", "hypertension"], metadata: { smoker: true, egfr: 68 }, created_at: ts(1200), updated_at: hrs(2) },
  { id: "pt-02", workspace_id: W, mrn: "MRN-100388", name_en: "Maryam Al-Ghamdi", name_ar: "مريم الغامدي", date_of_birth: dob(41, 9, 2), sex: "female", national_id: "1055123908", phone: "+966-50-882-4410", email: "m.ghamdi@example.sa", address_en: "Al Rawdah, Jeddah", address_ar: "الروضة، جدة", blood_group: "A+", allergy_summary: null, next_of_kin_name: "Saeed Al-Ghamdi", next_of_kin_phone: "+966-50-882-4499", next_of_kin_relation: "Spouse", preferred_language: "ar", status: "active", merged_into_id: null, vip_flag: false, photo_url: null, registered_at: ts(640), tags: ["surgical"], metadata: { egfr: 94 }, created_at: ts(640), updated_at: hrs(5) },
  { id: "pt-03", workspace_id: W, mrn: "MRN-100455", name_en: "Fatima Al-Harbi", name_ar: "فاطمة الحربي", date_of_birth: dob(67, 1, 25), sex: "female", national_id: "1033445120", phone: "+966-50-664-7788", email: null, address_en: "Al Naseem, Riyadh", address_ar: "النسيم، الرياض", blood_group: "B+", allergy_summary: "Sulfonamides — angioedema", next_of_kin_name: "Ahmed Al-Harbi", next_of_kin_phone: "+966-50-664-7700", next_of_kin_relation: "Son", preferred_language: "ar", status: "active", merged_into_id: null, vip_flag: false, photo_url: null, registered_at: ts(2100), tags: ["diabetes", "ckd"], metadata: { egfr: 26, diabetic: true }, created_at: ts(2100), updated_at: hrs(30) },
  { id: "pt-04", workspace_id: W, mrn: "MRN-100512", name_en: "Noura Al-Qahtani", name_ar: "نورة القحطاني", date_of_birth: dob(29, 7, 8), sex: "female", national_id: "1078990234", phone: "+966-50-334-9021", email: "n.qahtani@example.sa", address_en: "Al Yasmin, Riyadh", address_ar: "الياسمين، الرياض", blood_group: "AB+", allergy_summary: null, next_of_kin_name: "Sultan Al-Qahtani", next_of_kin_phone: "+966-50-334-9000", next_of_kin_relation: "Spouse", preferred_language: "ar", status: "active", merged_into_id: null, vip_flag: false, photo_url: null, registered_at: ts(280), tags: ["maternity"], metadata: { pregnant: true, gestation_weeks: 39, gravida: 2, para: 1, egfr: 102 }, created_at: ts(280), updated_at: hrs(14) },
  { id: "pt-05", workspace_id: W, mrn: "MRN-100603", name_en: "Yousef Al-Dosari", name_ar: "يوسف الدوسري", date_of_birth: dob(7, 4, 30), sex: "male", national_id: "1099887766", phone: "+966-50-221-3344", email: null, address_en: "Al Sulaimaniyah, Riyadh", address_ar: "السليمانية، الرياض", blood_group: "O-", allergy_summary: "Peanut — anaphylaxis", next_of_kin_name: "Hind Al-Dosari", next_of_kin_phone: "+966-50-221-3300", next_of_kin_relation: "Mother", preferred_language: "ar", status: "active", merged_into_id: null, vip_flag: false, photo_url: null, registered_at: ts(900), tags: ["paediatric", "asthma"], metadata: { weight_kg: 24 }, created_at: ts(900), updated_at: hrs(4) },
  { id: "pt-06", workspace_id: W, mrn: "MRN-100677", name_en: "Abdullah Al-Shehri", name_ar: "عبدالله الشهري", date_of_birth: dob(73, 11, 3), sex: "male", national_id: "1011223344", phone: "+966-50-556-1122", email: null, address_en: "Al Aziziyah, Riyadh", address_ar: "العزيزية، الرياض", blood_group: "A-", allergy_summary: null, next_of_kin_name: "Faisal Al-Shehri", next_of_kin_phone: "+966-50-556-1100", next_of_kin_relation: "Son", preferred_language: "ar", status: "active", merged_into_id: null, vip_flag: false, photo_url: null, registered_at: ts(1500), tags: ["icu", "sepsis"], metadata: { egfr: 34, ventilated: true }, created_at: ts(1500), updated_at: hrs(1) },
  { id: "pt-07", workspace_id: W, mrn: "MRN-100714", name_en: "Sara Al-Mutairi", name_ar: "سارة المطيري", date_of_birth: dob(63, 2, 19), sex: "female", national_id: "1044556677", phone: "+966-50-998-2233", email: "s.mutairi@example.sa", address_en: "Al Wurud, Riyadh", address_ar: "الورود، الرياض", blood_group: "B-", allergy_summary: null, next_of_kin_name: "Mona Al-Mutairi", next_of_kin_phone: "+966-50-998-2200", next_of_kin_relation: "Daughter", preferred_language: "ar", status: "active", merged_into_id: null, vip_flag: false, photo_url: null, registered_at: ts(420), tags: ["day_case", "ophthalmology"], metadata: { egfr: 78 }, created_at: ts(420), updated_at: hrs(26) },
  { id: "pt-08", workspace_id: W, mrn: "MRN-100822", name_en: "Ibrahim Al-Zahrani", name_ar: "إبراهيم الزهراني", date_of_birth: dob(35, 6, 11), sex: "male", national_id: "1066778899", phone: "+966-50-443-5566", email: "i.zahrani@example.sa", address_en: "Al Khobar", address_ar: "الخبر", blood_group: "O+", allergy_summary: null, next_of_kin_name: "Nawaf Al-Zahrani", next_of_kin_phone: "+966-50-443-5500", next_of_kin_relation: "Brother", preferred_language: "en", status: "active", merged_into_id: null, vip_flag: false, photo_url: null, registered_at: ts(60), tags: ["orthopaedic", "trauma"], metadata: { egfr: 98 }, created_at: ts(60), updated_at: hrs(20) },
  { id: "pt-09", workspace_id: W, mrn: "MRN-100901", name_en: "Hessa Al-Subaie", name_ar: "حصة السبيعي", date_of_birth: dob(54, 8, 22), sex: "female", national_id: "1022334455", phone: "+966-50-887-9900", email: "h.subaie@example.sa", address_en: "Al Nakheel, Riyadh", address_ar: "النخيل، الرياض", blood_group: "A+", allergy_summary: "Contrast media — urticaria", next_of_kin_name: "Bader Al-Subaie", next_of_kin_phone: "+966-50-887-9911", next_of_kin_relation: "Spouse", preferred_language: "ar", status: "active", merged_into_id: null, vip_flag: true, photo_url: null, registered_at: ts(800), tags: ["oncology"], metadata: { egfr: 61, chemo_cycle: 4 }, created_at: ts(800), updated_at: hrs(7) },
  { id: "pt-10", workspace_id: W, mrn: "MRN-101034", name_en: "Majed Al-Rashid", name_ar: "ماجد الراشد", date_of_birth: dob(23, 12, 5), sex: "male", national_id: "1088776655", phone: "+966-50-112-3344", email: "m.rashid@example.sa", address_en: "Al Izdihar, Riyadh", address_ar: "الازدهار، الرياض", blood_group: "O+", allergy_summary: null, next_of_kin_name: "Salem Al-Rashid", next_of_kin_phone: "+966-50-112-3300", next_of_kin_relation: "Father", preferred_language: "ar", status: "active", merged_into_id: null, vip_flag: false, photo_url: null, registered_at: ts(15), tags: ["ed"], metadata: { egfr: 110 }, created_at: ts(15), updated_at: mins(50) },
  { id: "pt-11", workspace_id: W, mrn: "MRN-101120", name_en: "Layla Al-Anazi", name_ar: "ليلى العنزي", date_of_birth: dob(31, 10, 17), sex: "female", national_id: "1077665544", phone: "+966-50-667-8899", email: "l.anazi@example.sa", address_en: "Al Rabwah, Riyadh", address_ar: "الربوة، الرياض", blood_group: "B+", allergy_summary: null, next_of_kin_name: null, next_of_kin_phone: null, next_of_kin_relation: null, preferred_language: "en", status: "active", merged_into_id: null, vip_flag: false, photo_url: null, registered_at: ts(200), tags: ["dermatology", "telehealth"], metadata: { egfr: 105 }, created_at: ts(200), updated_at: hrs(3) },
  { id: "pt-12", workspace_id: W, mrn: "MRN-101208", name_en: "Turki Al-Malki", name_ar: "تركي المالكي", date_of_birth: dob(66, 5, 9), sex: "male", national_id: "1099001122", phone: "+966-50-778-6655", email: null, address_en: "Al Shifa, Riyadh", address_ar: "الشفا، الرياض", blood_group: "AB-", allergy_summary: "Aspirin — bronchospasm", next_of_kin_name: "Hussa Al-Malki", next_of_kin_phone: "+966-50-778-6600", next_of_kin_relation: "Spouse", preferred_language: "ar", status: "active", merged_into_id: null, vip_flag: false, photo_url: null, registered_at: ts(1100), tags: ["copd", "ed"], metadata: { egfr: 55 }, created_at: ts(1100), updated_at: mins(25) },
  { id: "pt-13", workspace_id: W, mrn: "MRN-101315", name_en: "Reem Al-Faisal", name_ar: "ريم الفيصل", date_of_birth: dob(45, 3, 28), sex: "female", national_id: "1055667788", phone: "+966-50-334-1122", email: "r.faisal@example.sa", address_en: "Al Muruj, Riyadh", address_ar: "المروج، الرياض", blood_group: "A+", allergy_summary: null, next_of_kin_name: null, next_of_kin_phone: null, next_of_kin_relation: null, preferred_language: "ar", status: "active", merged_into_id: null, vip_flag: false, photo_url: null, registered_at: ts(500), tags: ["endocrine"], metadata: { egfr: 88 }, created_at: ts(500), updated_at: hrs(48) },
  { id: "pt-14", workspace_id: W, mrn: "MRN-101402", name_en: "Saud Al-Amri", name_ar: "سعود العمري", date_of_birth: dob(52, 7, 4), sex: "male", national_id: "1033221100", phone: "+966-50-445-9988", email: "s.amri@example.sa", address_en: "Al Nahdah, Riyadh", address_ar: "النهضة، الرياض", blood_group: "O+", allergy_summary: null, next_of_kin_name: "Wafa Al-Amri", next_of_kin_phone: "+966-50-445-9900", next_of_kin_relation: "Spouse", preferred_language: "ar", status: "active", merged_into_id: null, vip_flag: false, photo_url: null, registered_at: ts(700), tags: ["discharged"], metadata: { egfr: 82 }, created_at: ts(700), updated_at: hrs(26) },
];

// ─── Encounters ───────────────────────────────────────────

export const DEMO_ENCOUNTERS: T<"encounters">[] = [
  { id: "enc-01", workspace_id: W, encounter_number: "ENC-2026-04411", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", patient_mrn: "MRN-100241", class: "inpatient", status: "in_progress", department_id: "dept-02", department_name: "Cardiology", attending_provider_id: "prov-01", attending_provider_name: "Dr. Hala Al-Rasheed", ward_id: "wd-01", bed_id: "bed-CCU-01", bed_label: "CCU-01", admitted_at: hrs(9), discharged_at: null, chief_complaint_en: "Central chest pain radiating to left arm", chief_complaint_ar: "ألم في وسط الصدر يمتد إلى الذراع الأيسر", admission_source: "emergency", discharge_disposition: null, los_hours: null, isolation_required: false, insurance_policy_id: "pol-01", metadata: { referred_from: "ED" }, created_at: hrs(11), updated_at: hrs(1) },
  { id: "enc-02", workspace_id: W, encounter_number: "ENC-2026-04398", patient_id: "pt-02", patient_name: "Maryam Al-Ghamdi", patient_mrn: "MRN-100388", class: "inpatient", status: "in_progress", department_id: "dept-03", department_name: "General Surgery", attending_provider_id: "prov-02", attending_provider_name: "Dr. Faisal Al-Harthy", ward_id: "wd-02", bed_id: "bed-SA-01", bed_label: "SA-01", admitted_at: hrs(28), discharged_at: null, chief_complaint_en: "Right upper quadrant pain, gallstones", chief_complaint_ar: "ألم أعلى البطن الأيمن مع حصوات المرارة", admission_source: "elective", discharge_disposition: null, los_hours: null, isolation_required: false, insurance_policy_id: "pol-02", metadata: { post_op_day: 1 }, created_at: hrs(30), updated_at: hrs(5) },
  { id: "enc-03", workspace_id: W, encounter_number: "ENC-2026-04502", patient_id: "pt-03", patient_name: "Fatima Al-Harbi", patient_mrn: "MRN-100455", class: "outpatient", status: "in_progress", department_id: "dept-02", department_name: "Cardiology", attending_provider_id: "prov-01", attending_provider_name: "Dr. Hala Al-Rasheed", ward_id: null, bed_id: null, bed_label: null, admitted_at: null, discharged_at: null, chief_complaint_en: "Diabetes review, worsening renal function", chief_complaint_ar: "متابعة السكري مع تدهور وظائف الكلى", admission_source: "referral", discharge_disposition: null, los_hours: null, isolation_required: false, insurance_policy_id: "pol-03", metadata: {}, created_at: hrs(31), updated_at: hrs(30) },
  { id: "enc-04", workspace_id: W, encounter_number: "ENC-2026-04478", patient_id: "pt-04", patient_name: "Noura Al-Qahtani", patient_mrn: "MRN-100512", class: "inpatient", status: "in_progress", department_id: "dept-05", department_name: "Obstetrics & Gynaecology", attending_provider_id: "prov-07", attending_provider_name: "Dr. Amal Al-Shamrani", ward_id: "wd-04", bed_id: "bed-MAT-03", bed_label: "MAT-03", admitted_at: hrs(14), discharged_at: null, chief_complaint_en: "Term pregnancy, admitted for elective caesarean", chief_complaint_ar: "حمل مكتمل، دخول لعملية قيصرية مخططة", admission_source: "elective", discharge_disposition: null, los_hours: null, isolation_required: false, insurance_policy_id: "pol-04", metadata: { gestation_weeks: 39 }, created_at: hrs(15), updated_at: hrs(2) },
  { id: "enc-05", workspace_id: W, encounter_number: "ENC-2026-04533", patient_id: "pt-05", patient_name: "Yousef Al-Dosari", patient_mrn: "MRN-100603", class: "observation", status: "in_progress", department_id: "dept-06", department_name: "Paediatrics", attending_provider_id: "prov-08", attending_provider_name: "Dr. Rana Al-Suwailem", ward_id: "wd-05", bed_id: "bed-PD-02", bed_label: "PD-02", admitted_at: hrs(5), discharged_at: null, chief_complaint_en: "Acute asthma exacerbation", chief_complaint_ar: "نوبة ربو حادة", admission_source: "emergency", discharge_disposition: null, los_hours: null, isolation_required: false, insurance_policy_id: "pol-05", metadata: {}, created_at: hrs(6), updated_at: hrs(1) },
  { id: "enc-06", workspace_id: W, encounter_number: "ENC-2026-04301", patient_id: "pt-06", patient_name: "Abdullah Al-Shehri", patient_mrn: "MRN-100677", class: "inpatient", status: "in_progress", department_id: "dept-04", department_name: "Intensive Care", attending_provider_id: "prov-06", attending_provider_name: "Dr. Omar Bin Salem", ward_id: "wd-03", bed_id: "bed-ICU-02", bed_label: "ICU-02", admitted_at: hrs(76), discharged_at: null, chief_complaint_en: "Urosepsis with septic shock", chief_complaint_ar: "إنتان بولي مع صدمة إنتانية", admission_source: "emergency", discharge_disposition: null, los_hours: null, isolation_required: true, insurance_policy_id: "pol-06", metadata: { ventilated: true, vasopressors: true }, created_at: hrs(78), updated_at: mins(40) },
  { id: "enc-07", workspace_id: W, encounter_number: "ENC-2026-04455", patient_id: "pt-07", patient_name: "Sara Al-Mutairi", patient_mrn: "MRN-100714", class: "day_case", status: "discharged", department_id: "dept-03", department_name: "General Surgery", attending_provider_id: "prov-02", attending_provider_name: "Dr. Faisal Al-Harthy", ward_id: null, bed_id: null, bed_label: null, admitted_at: hrs(32), discharged_at: hrs(26), chief_complaint_en: "Cataract, right eye", chief_complaint_ar: "مياه بيضاء في العين اليمنى", admission_source: "elective", discharge_disposition: "home", los_hours: 6, isolation_required: false, insurance_policy_id: "pol-07", metadata: {}, created_at: hrs(34), updated_at: hrs(26) },
  { id: "enc-08", workspace_id: W, encounter_number: "ENC-2026-04520", patient_id: "pt-08", patient_name: "Ibrahim Al-Zahrani", patient_mrn: "MRN-100822", class: "inpatient", status: "in_progress", department_id: "dept-07", department_name: "Orthopaedics", attending_provider_id: "prov-09", attending_provider_name: "Dr. Bandar Al-Otaibi", ward_id: "wd-02", bed_id: "bed-SA-06", bed_label: "SA-06", admitted_at: hrs(20), discharged_at: null, chief_complaint_en: "Closed tibial shaft fracture, road traffic accident", chief_complaint_ar: "كسر مغلق في عظم الساق نتيجة حادث مروري", admission_source: "emergency", discharge_disposition: null, los_hours: null, isolation_required: false, insurance_policy_id: "pol-08", metadata: { awaiting_theatre: true }, created_at: hrs(21), updated_at: hrs(3) },
  { id: "enc-09", workspace_id: W, encounter_number: "ENC-2026-04541", patient_id: "pt-09", patient_name: "Hessa Al-Subaie", patient_mrn: "MRN-100901", class: "day_case", status: "in_progress", department_id: "dept-12", department_name: "Oncology Day Unit", attending_provider_id: "prov-13", attending_provider_name: "Dr. Ziad Al-Mansour", ward_id: null, bed_id: null, bed_label: null, admitted_at: hrs(7), discharged_at: null, chief_complaint_en: "Chemotherapy cycle 4", chief_complaint_ar: "الجرعة الرابعة من العلاج الكيميائي", admission_source: "elective", discharge_disposition: null, los_hours: null, isolation_required: false, insurance_policy_id: "pol-09", metadata: { regimen: "FOLFOX" }, created_at: hrs(8), updated_at: hrs(2) },
  { id: "enc-10", workspace_id: W, encounter_number: "ENC-2026-04560", patient_id: "pt-10", patient_name: "Majed Al-Rashid", patient_mrn: "MRN-101034", class: "emergency", status: "arrived", department_id: "dept-01", department_name: "Emergency Medicine", attending_provider_id: null, attending_provider_name: null, ward_id: null, bed_id: null, bed_label: null, admitted_at: null, discharged_at: null, chief_complaint_en: "Inversion ankle injury, unable to weight bear", chief_complaint_ar: "التواء في الكاحل مع عدم القدرة على المشي", admission_source: "walk_in", discharge_disposition: null, los_hours: null, isolation_required: false, insurance_policy_id: null, metadata: {}, created_at: mins(50), updated_at: mins(50) },
  { id: "enc-11", workspace_id: W, encounter_number: "ENC-2026-04549", patient_id: "pt-11", patient_name: "Layla Al-Anazi", patient_mrn: "MRN-101120", class: "telehealth", status: "planned", department_id: "dept-13", department_name: "Dermatology", attending_provider_id: "prov-14", attending_provider_name: "Dr. Lina Al-Yousef", ward_id: null, bed_id: null, bed_label: null, admitted_at: null, discharged_at: null, chief_complaint_en: "Eczema follow-up", chief_complaint_ar: "متابعة الإكزيما", admission_source: "referral", discharge_disposition: null, los_hours: null, isolation_required: false, insurance_policy_id: "pol-11", metadata: {}, created_at: hrs(30), updated_at: hrs(3) },
  { id: "enc-12", workspace_id: W, encounter_number: "ENC-2026-04562", patient_id: "pt-12", patient_name: "Turki Al-Malki", patient_mrn: "MRN-101208", class: "emergency", status: "in_progress", department_id: "dept-01", department_name: "Emergency Medicine", attending_provider_id: "prov-03", attending_provider_name: "Dr. Nasser Al-Juhani", ward_id: null, bed_id: null, bed_label: null, admitted_at: null, discharged_at: null, chief_complaint_en: "Increasing breathlessness, known COPD", chief_complaint_ar: "ضيق تنفس متزايد مع انسداد رئوي مزمن معروف", admission_source: "emergency", discharge_disposition: null, los_hours: null, isolation_required: false, insurance_policy_id: "pol-12", metadata: {}, created_at: mins(95), updated_at: mins(25) },
  { id: "enc-13", workspace_id: W, encounter_number: "ENC-2026-04390", patient_id: "pt-13", patient_name: "Reem Al-Faisal", patient_mrn: "MRN-101315", class: "outpatient", status: "discharged", department_id: "dept-02", department_name: "Cardiology", attending_provider_id: "prov-04", attending_provider_name: "Dr. Maha Al-Sanea", ward_id: null, bed_id: null, bed_label: null, admitted_at: null, discharged_at: hrs(47), chief_complaint_en: "Thyroid function review", chief_complaint_ar: "مراجعة وظائف الغدة الدرقية", admission_source: "referral", discharge_disposition: "home", los_hours: 1, isolation_required: false, insurance_policy_id: "pol-13", metadata: {}, created_at: hrs(48), updated_at: hrs(47) },
  { id: "enc-14", workspace_id: W, encounter_number: "ENC-2026-04322", patient_id: "pt-14", patient_name: "Saud Al-Amri", patient_mrn: "MRN-101402", class: "inpatient", status: "discharged", department_id: "dept-03", department_name: "General Surgery", attending_provider_id: "prov-02", attending_provider_name: "Dr. Faisal Al-Harthy", ward_id: "wd-02", bed_id: null, bed_label: "SA-04", admitted_at: hrs(98), discharged_at: hrs(26), chief_complaint_en: "Acute appendicitis", chief_complaint_ar: "التهاب زائدة دودية حاد", admission_source: "emergency", discharge_disposition: "home", los_hours: 72, isolation_required: false, insurance_policy_id: "pol-14", metadata: {}, created_at: hrs(99), updated_at: hrs(26) },
];

// ─── Allergies ────────────────────────────────────────────

export const DEMO_ALLERGIES: T<"allergies">[] = [
  { id: "alg-01", workspace_id: W, patient_id: "pt-01", substance_en: "Penicillin", substance_ar: "بنسلين", allergen_type: "drug", reaction_en: "Widespread maculopapular rash", reaction_ar: "طفح جلدي منتشر", severity: "moderate", kind: "allergy", onset_date: d(3000), status: "active", recorded_by: "Dr. Nasser Al-Juhani", metadata: {}, created_at: ts(1200), updated_at: ts(1200) },
  { id: "alg-02", workspace_id: W, patient_id: "pt-03", substance_en: "Sulfamethoxazole", substance_ar: "سلفاميثوكسازول", allergen_type: "drug", reaction_en: "Facial angioedema requiring adrenaline", reaction_ar: "وذمة وعائية في الوجه استدعت الأدرينالين", severity: "severe", kind: "allergy", onset_date: d(1800), status: "active", recorded_by: "Dr. Hala Al-Rasheed", metadata: {}, created_at: ts(2100), updated_at: ts(2100) },
  { id: "alg-03", workspace_id: W, patient_id: "pt-05", substance_en: "Peanut", substance_ar: "الفول السوداني", allergen_type: "food", reaction_en: "Anaphylaxis — airway compromise", reaction_ar: "تأق مع ضيق في المجرى التنفسي", severity: "fatal", kind: "allergy", onset_date: d(1500), status: "active", recorded_by: "Dr. Rana Al-Suwailem", metadata: { epipen_carried: true }, created_at: ts(900), updated_at: ts(900) },
  { id: "alg-04", workspace_id: W, patient_id: "pt-09", substance_en: "Iodinated contrast", substance_ar: "الصبغة اليودية", allergen_type: "contrast", reaction_en: "Urticaria within 20 minutes", reaction_ar: "شرى خلال ٢٠ دقيقة", severity: "moderate", kind: "allergy", onset_date: d(600), status: "active", recorded_by: "Dr. Tariq Al-Balawi", metadata: { premedication_protocol: true }, created_at: ts(800), updated_at: ts(800) },
  { id: "alg-05", workspace_id: W, patient_id: "pt-12", substance_en: "Aspirin", substance_ar: "أسبرين", allergen_type: "drug", reaction_en: "Bronchospasm", reaction_ar: "تشنج قصبي", severity: "severe", kind: "allergy", onset_date: d(2500), status: "active", recorded_by: "Dr. Nasser Al-Juhani", metadata: {}, created_at: ts(1100), updated_at: ts(1100) },
  { id: "alg-06", workspace_id: W, patient_id: "pt-02", substance_en: "Metoclopramide", substance_ar: "ميتوكلوبراميد", allergen_type: "drug", reaction_en: "Nausea and restlessness — tolerated poorly", reaction_ar: "غثيان وتململ مع سوء تحمل", severity: "mild", kind: "intolerance", onset_date: d(400), status: "active", recorded_by: "Dr. Faisal Al-Harthy", metadata: {}, created_at: ts(640), updated_at: ts(640) },
  { id: "alg-07", workspace_id: W, patient_id: "pt-06", substance_en: "Latex", substance_ar: "اللاتكس", allergen_type: "latex", reaction_en: "Contact dermatitis", reaction_ar: "التهاب جلد تماسي", severity: "mild", kind: "allergy", onset_date: d(900), status: "active", recorded_by: "Nurse Aisha Al-Dakhil", metadata: {}, created_at: ts(1500), updated_at: ts(1500) },
];

// ─── Diagnoses ────────────────────────────────────────────

export const DEMO_DIAGNOSES: T<"diagnoses">[] = [
  { id: "dx-01", workspace_id: W, encounter_id: "enc-01", patient_id: "pt-01", code_system: "icd11", code: "BA41.0", description_en: "Non-ST elevation myocardial infarction", description_ar: "احتشاء عضلة القلب دون ارتفاع ST", category: "principal", certainty: "confirmed", onset_date: d(0), resolved_date: null, status: "active", present_on_admission: true, diagnosed_by: "Dr. Hala Al-Rasheed", metadata: {}, created_at: hrs(8), updated_at: hrs(2) },
  { id: "dx-02", workspace_id: W, encounter_id: "enc-01", patient_id: "pt-01", code_system: "icd11", code: "BA00", description_en: "Essential hypertension", description_ar: "ارتفاع ضغط الدم الأساسي", category: "comorbidity", certainty: "confirmed", onset_date: d(2200), resolved_date: null, status: "active", present_on_admission: true, diagnosed_by: "Dr. Hala Al-Rasheed", metadata: {}, created_at: ts(2200), updated_at: hrs(8) },
  { id: "dx-03", workspace_id: W, encounter_id: "enc-02", patient_id: "pt-02", code_system: "icd11", code: "DC11.0", description_en: "Calculus of gallbladder with acute cholecystitis", description_ar: "حصوة المرارة مع التهاب حاد", category: "principal", certainty: "confirmed", onset_date: d(3), resolved_date: null, status: "active", present_on_admission: true, diagnosed_by: "Dr. Faisal Al-Harthy", metadata: {}, created_at: hrs(29), updated_at: hrs(29) },
  { id: "dx-04", workspace_id: W, encounter_id: "enc-03", patient_id: "pt-03", code_system: "icd11", code: "5A11", description_en: "Type 2 diabetes mellitus", description_ar: "داء السكري من النوع الثاني", category: "principal", certainty: "confirmed", onset_date: d(3600), resolved_date: null, status: "active", present_on_admission: null, diagnosed_by: "Dr. Hala Al-Rasheed", metadata: {}, created_at: ts(2100), updated_at: hrs(30) },
  { id: "dx-05", workspace_id: W, encounter_id: "enc-03", patient_id: "pt-03", code_system: "icd11", code: "GB61.3", description_en: "Chronic kidney disease, stage 4", description_ar: "مرض كلوي مزمن، المرحلة الرابعة", category: "comorbidity", certainty: "confirmed", onset_date: d(700), resolved_date: null, status: "active", present_on_admission: null, diagnosed_by: "Dr. Hala Al-Rasheed", metadata: { egfr: 26 }, created_at: ts(700), updated_at: hrs(30) },
  { id: "dx-06", workspace_id: W, encounter_id: "enc-06", patient_id: "pt-06", code_system: "icd11", code: "1G41", description_en: "Sepsis with septic shock", description_ar: "إنتان مع صدمة إنتانية", category: "principal", certainty: "confirmed", onset_date: d(3), resolved_date: null, status: "active", present_on_admission: true, diagnosed_by: "Dr. Omar Bin Salem", metadata: { source: "urinary" }, created_at: hrs(77), updated_at: hrs(4) },
  { id: "dx-07", workspace_id: W, encounter_id: "enc-06", patient_id: "pt-06", code_system: "icd11", code: "GB60.2", description_en: "Acute kidney injury, stage 2", description_ar: "قصور كلوي حاد، المرحلة الثانية", category: "complication", certainty: "confirmed", onset_date: d(2), resolved_date: null, status: "active", present_on_admission: false, diagnosed_by: "Dr. Omar Bin Salem", metadata: {}, created_at: hrs(50), updated_at: hrs(4) },
  { id: "dx-08", workspace_id: W, encounter_id: "enc-08", patient_id: "pt-08", code_system: "icd11", code: "NC92.2", description_en: "Fracture of shaft of tibia, closed", description_ar: "كسر في جسم عظم الساق، مغلق", category: "principal", certainty: "confirmed", onset_date: d(1), resolved_date: null, status: "active", present_on_admission: true, diagnosed_by: "Dr. Bandar Al-Otaibi", metadata: { laterality: "left" }, created_at: hrs(20), updated_at: hrs(20) },
  { id: "dx-09", workspace_id: W, encounter_id: "enc-05", patient_id: "pt-05", code_system: "icd11", code: "CA23.0", description_en: "Asthma with acute exacerbation", description_ar: "ربو مع نوبة حادة", category: "principal", certainty: "confirmed", onset_date: d(0), resolved_date: null, status: "active", present_on_admission: true, diagnosed_by: "Dr. Rana Al-Suwailem", metadata: {}, created_at: hrs(5), updated_at: hrs(2) },
  { id: "dx-10", workspace_id: W, encounter_id: "enc-12", patient_id: "pt-12", code_system: "icd11", code: "CA22.1", description_en: "COPD with acute exacerbation", description_ar: "انسداد رئوي مزمن مع نوبة حادة", category: "admitting", certainty: "provisional", onset_date: d(0), resolved_date: null, status: "active", present_on_admission: true, diagnosed_by: "Dr. Nasser Al-Juhani", metadata: {}, created_at: mins(60), updated_at: mins(25) },
  { id: "dx-11", workspace_id: W, encounter_id: "enc-14", patient_id: "pt-14", code_system: "icd11", code: "DB10", description_en: "Acute appendicitis", description_ar: "التهاب الزائدة الدودية الحاد", category: "discharge", certainty: "confirmed", onset_date: d(5), resolved_date: d(1), status: "resolved", present_on_admission: true, diagnosed_by: "Dr. Faisal Al-Harthy", metadata: {}, created_at: hrs(97), updated_at: hrs(26) },
  { id: "dx-12", workspace_id: W, encounter_id: "enc-09", patient_id: "pt-09", code_system: "icd11", code: "2B90.0", description_en: "Adenocarcinoma of colon", description_ar: "سرطان غدي في القولون", category: "principal", certainty: "confirmed", onset_date: d(400), resolved_date: null, status: "active", present_on_admission: null, diagnosed_by: "Dr. Ziad Al-Mansour", metadata: { stage: "IIIB" }, created_at: ts(400), updated_at: hrs(7) },
];

// ─── Vitals ───────────────────────────────────────────────

/**
 * A vitals series for the deteriorating ICU patient and the stable ones, so
 * the NEWS2 trend chart has something real to draw. Scores are left null and
 * computed by `computeNews2` at read time — storing them here would let the
 * seed and the algorithm drift apart.
 */
export const DEMO_VITALS: T<"vitals">[] = [
  // pt-06 (ICU, deteriorating then stabilising on treatment)
  { id: "vt-01", workspace_id: W, encounter_id: "enc-06", patient_id: "pt-06", recorded_at: hrs(72), recorded_by: "Nurse Aisha Al-Dakhil", temperature_c: 39.4, heart_rate: 128, respiratory_rate: 28, systolic_bp: 84, diastolic_bp: 48, spo2: 89, on_oxygen: true, blood_glucose: 11.2, pain_score: null, consciousness: "voice", weight_kg: 78, height_cm: 172, news2_score: null, news2_band: null, metadata: {}, created_at: hrs(72), updated_at: hrs(72) },
  { id: "vt-02", workspace_id: W, encounter_id: "enc-06", patient_id: "pt-06", recorded_at: hrs(48), recorded_by: "Nurse Aisha Al-Dakhil", temperature_c: 38.6, heart_rate: 116, respiratory_rate: 24, systolic_bp: 92, diastolic_bp: 54, spo2: 93, on_oxygen: true, blood_glucose: 9.4, pain_score: null, consciousness: "voice", weight_kg: 78, height_cm: 172, news2_score: null, news2_band: null, metadata: {}, created_at: hrs(48), updated_at: hrs(48) },
  { id: "vt-03", workspace_id: W, encounter_id: "enc-06", patient_id: "pt-06", recorded_at: hrs(24), recorded_by: "Nurse Aisha Al-Dakhil", temperature_c: 37.8, heart_rate: 102, respiratory_rate: 20, systolic_bp: 104, diastolic_bp: 62, spo2: 95, on_oxygen: true, blood_glucose: 7.8, pain_score: null, consciousness: "alert", weight_kg: 78, height_cm: 172, news2_score: null, news2_band: null, metadata: {}, created_at: hrs(24), updated_at: hrs(24) },
  { id: "vt-04", workspace_id: W, encounter_id: "enc-06", patient_id: "pt-06", recorded_at: hrs(4), recorded_by: "Nurse Aisha Al-Dakhil", temperature_c: 37.2, heart_rate: 94, respiratory_rate: 18, systolic_bp: 112, diastolic_bp: 68, spo2: 96, on_oxygen: true, blood_glucose: 6.9, pain_score: 2, consciousness: "alert", weight_kg: 78, height_cm: 172, news2_score: null, news2_band: null, metadata: {}, created_at: hrs(4), updated_at: hrs(4) },

  // pt-01 (CCU, stable but not well)
  { id: "vt-05", workspace_id: W, encounter_id: "enc-01", patient_id: "pt-01", recorded_at: hrs(9), recorded_by: "Nurse Aisha Al-Dakhil", temperature_c: 36.9, heart_rate: 96, respiratory_rate: 20, systolic_bp: 148, diastolic_bp: 92, spo2: 96, on_oxygen: false, blood_glucose: 6.4, pain_score: 7, consciousness: "alert", weight_kg: 91, height_cm: 176, news2_score: null, news2_band: null, metadata: {}, created_at: hrs(9), updated_at: hrs(9) },
  { id: "vt-06", workspace_id: W, encounter_id: "enc-01", patient_id: "pt-01", recorded_at: hrs(5), recorded_by: "Nurse Aisha Al-Dakhil", temperature_c: 36.7, heart_rate: 88, respiratory_rate: 18, systolic_bp: 138, diastolic_bp: 84, spo2: 97, on_oxygen: false, blood_glucose: 5.9, pain_score: 3, consciousness: "alert", weight_kg: 91, height_cm: 176, news2_score: null, news2_band: null, metadata: {}, created_at: hrs(5), updated_at: hrs(5) },
  { id: "vt-07", workspace_id: W, encounter_id: "enc-01", patient_id: "pt-01", recorded_at: hrs(1), recorded_by: "Nurse Aisha Al-Dakhil", temperature_c: 36.8, heart_rate: 82, respiratory_rate: 17, systolic_bp: 132, diastolic_bp: 80, spo2: 98, on_oxygen: false, blood_glucose: 5.6, pain_score: 1, consciousness: "alert", weight_kg: 91, height_cm: 176, news2_score: null, news2_band: null, metadata: {}, created_at: hrs(1), updated_at: hrs(1) },

  // pt-02 (post-op day 1, uneventful)
  { id: "vt-08", workspace_id: W, encounter_id: "enc-02", patient_id: "pt-02", recorded_at: hrs(12), recorded_by: "Nurse Sara Bin Ali", temperature_c: 37.4, heart_rate: 88, respiratory_rate: 16, systolic_bp: 118, diastolic_bp: 74, spo2: 97, on_oxygen: false, blood_glucose: null, pain_score: 4, consciousness: "alert", weight_kg: 68, height_cm: 161, news2_score: null, news2_band: null, metadata: {}, created_at: hrs(12), updated_at: hrs(12) },
  { id: "vt-09", workspace_id: W, encounter_id: "enc-02", patient_id: "pt-02", recorded_at: hrs(4), recorded_by: "Nurse Sara Bin Ali", temperature_c: 36.9, heart_rate: 76, respiratory_rate: 15, systolic_bp: 116, diastolic_bp: 72, spo2: 98, on_oxygen: false, blood_glucose: null, pain_score: 2, consciousness: "alert", weight_kg: 68, height_cm: 161, news2_score: null, news2_band: null, metadata: {}, created_at: hrs(4), updated_at: hrs(4) },

  // pt-05 (paediatric asthma, improving)
  { id: "vt-10", workspace_id: W, encounter_id: "enc-05", patient_id: "pt-05", recorded_at: hrs(5), recorded_by: "Nurse Dana Al-Muhaisen", temperature_c: 37.1, heart_rate: 132, respiratory_rate: 32, systolic_bp: 102, diastolic_bp: 64, spo2: 92, on_oxygen: true, blood_glucose: null, pain_score: 0, consciousness: "alert", weight_kg: 24, height_cm: 122, news2_score: null, news2_band: null, metadata: { note: "Paediatric — NEWS2 is not validated under 16; PEWS used on the ward" }, created_at: hrs(5), updated_at: hrs(5) },
  { id: "vt-11", workspace_id: W, encounter_id: "enc-05", patient_id: "pt-05", recorded_at: hrs(1), recorded_by: "Nurse Dana Al-Muhaisen", temperature_c: 36.8, heart_rate: 108, respiratory_rate: 24, systolic_bp: 104, diastolic_bp: 66, spo2: 96, on_oxygen: false, blood_glucose: null, pain_score: 0, consciousness: "alert", weight_kg: 24, height_cm: 122, news2_score: null, news2_band: null, metadata: {}, created_at: hrs(1), updated_at: hrs(1) },

  // pt-12 (ED, currently the sickest waiting patient)
  { id: "vt-12", workspace_id: W, encounter_id: "enc-12", patient_id: "pt-12", recorded_at: mins(80), recorded_by: "Nurse Khalid Al-Ruwais", temperature_c: 37.6, heart_rate: 118, respiratory_rate: 30, systolic_bp: 106, diastolic_bp: 68, spo2: 88, on_oxygen: true, blood_glucose: 8.1, pain_score: 2, consciousness: "alert", weight_kg: 64, height_cm: 168, news2_score: null, news2_band: null, metadata: {}, created_at: mins(80), updated_at: mins(80) },
  { id: "vt-13", workspace_id: W, encounter_id: "enc-12", patient_id: "pt-12", recorded_at: mins(20), recorded_by: "Nurse Khalid Al-Ruwais", temperature_c: 37.5, heart_rate: 110, respiratory_rate: 26, systolic_bp: 112, diastolic_bp: 70, spo2: 91, on_oxygen: true, blood_glucose: 7.6, pain_score: 2, consciousness: "alert", weight_kg: 64, height_cm: 168, news2_score: null, news2_band: null, metadata: {}, created_at: mins(20), updated_at: mins(20) },

  // pt-04 (maternity, stable)
  { id: "vt-14", workspace_id: W, encounter_id: "enc-04", patient_id: "pt-04", recorded_at: hrs(2), recorded_by: "Midwife Reem Al-Saleh", temperature_c: 36.6, heart_rate: 84, respiratory_rate: 16, systolic_bp: 124, diastolic_bp: 78, spo2: 99, on_oxygen: false, blood_glucose: 5.2, pain_score: 1, consciousness: "alert", weight_kg: 82, height_cm: 165, news2_score: null, news2_band: null, metadata: { fetal_heart_rate: 142 }, created_at: hrs(2), updated_at: hrs(2) },

  // pt-08 (orthopaedic, waiting for theatre)
  { id: "vt-15", workspace_id: W, encounter_id: "enc-08", patient_id: "pt-08", recorded_at: hrs(3), recorded_by: "Nurse Sara Bin Ali", temperature_c: 36.9, heart_rate: 92, respiratory_rate: 18, systolic_bp: 128, diastolic_bp: 76, spo2: 98, on_oxygen: false, blood_glucose: null, pain_score: 6, consciousness: "alert", weight_kg: 84, height_cm: 180, news2_score: null, news2_band: null, metadata: {}, created_at: hrs(3), updated_at: hrs(3) },
];

// ─── Clinical notes ───────────────────────────────────────

export const DEMO_CLINICAL_NOTES: T<"clinical_notes">[] = [
  { id: "note-01", workspace_id: W, encounter_id: "enc-01", patient_id: "pt-01", note_type: "admission", title_en: "Cardiology admission — NSTEMI", title_ar: "دخول قلبية — احتشاء دون ارتفاع ST", body_en: "58-year-old man, active smoker, known hypertension. Two hours of central crushing chest pain radiating to the left arm, associated with sweating and nausea. ECG shows T-wave inversion in the lateral leads, no ST elevation. First troponin 412 ng/L, second pending. Loaded with aspirin 300 mg and clopidogrel 600 mg in ED. Started on treatment-dose enoxaparin. Documented penicillin allergy — rash only, no airway involvement. Plan: admit to CCU, serial troponin, inpatient coronary angiography within 24 hours.", body_ar: "رجل ٥٨ عاماً، مدخن، مصاب بارتفاع ضغط الدم. ألم صدري ضاغط منذ ساعتين يمتد للذراع الأيسر مع تعرق وغثيان. تخطيط القلب يظهر انقلاب موجة T في الاتجاهات الجانبية دون ارتفاع ST. التروبونين الأول ٤١٢ والثاني قيد الانتظار. أُعطي أسبرين ٣٠٠ ملغ وكلوبيدوجريل ٦٠٠ ملغ في الطوارئ مع إينوكسابارين بجرعة علاجية. حساسية موثقة من البنسلين — طفح فقط. الخطة: دخول العناية القلبية مع تروبونين متسلسل وقسطرة خلال ٢٤ ساعة.", author_id: "prov-01", author_name: "Dr. Hala Al-Rasheed", author_role: "Consultant Cardiologist", status: "signed", signed_at: hrs(8), amends_note_id: null, confidential: false, metadata: {}, created_at: hrs(9), updated_at: hrs(8) },
  { id: "note-02", workspace_id: W, encounter_id: "enc-01", patient_id: "pt-01", note_type: "progress", title_en: "CCU ward round", title_ar: "جولة العناية القلبية", body_en: "Pain now 1/10 on the current regimen. Haemodynamically stable, no further ECG change. Second troponin 890 ng/L, consistent with the diagnosis. Angiography slot confirmed for tomorrow morning. Continue current therapy; discussed the procedure and consented.", body_ar: "الألم الآن ١/١٠ على العلاج الحالي. الحالة الديناميكية مستقرة دون تغير في تخطيط القلب. التروبونين الثاني ٨٩٠ متوافق مع التشخيص. تم تأكيد موعد القسطرة صباح الغد. استمرار العلاج الحالي مع شرح الإجراء وأخذ الموافقة.", author_id: "prov-01", author_name: "Dr. Hala Al-Rasheed", author_role: "Consultant Cardiologist", status: "signed", signed_at: hrs(2), amends_note_id: null, confidential: false, metadata: {}, created_at: hrs(2), updated_at: hrs(2) },
  { id: "note-03", workspace_id: W, encounter_id: "enc-02", patient_id: "pt-02", note_type: "operative", title_en: "Laparoscopic cholecystectomy", title_ar: "استئصال المرارة بالمنظار", body_en: "Four-port laparoscopic cholecystectomy under general anaesthesia. Critical view of safety achieved before clipping. Gallbladder moderately inflamed, no perforation. Cystic duct and artery clipped and divided. Specimen retrieved in a bag and sent to histopathology. Haemostasis confirmed, no drain. Estimated blood loss under 50 mL. Counts correct. Uncomplicated recovery.", body_ar: "استئصال المرارة بالمنظار بأربع فتحات تحت التخدير العام. تم تحقيق الرؤية الحرجة للأمان قبل وضع المشابك. المرارة ملتهبة بدرجة متوسطة دون انثقاب. تم قص القناة والشريان المراري. أُرسلت العينة لعلم الأمراض. تم التأكد من الإرقاء دون تركيب مصرف. الفقد المقدر أقل من ٥٠ مل. العدّ صحيح. تعافٍ دون مضاعفات.", author_id: "prov-02", author_name: "Dr. Faisal Al-Harthy", author_role: "Consultant Surgeon", status: "signed", signed_at: hrs(26), amends_note_id: null, confidential: false, metadata: {}, created_at: hrs(26), updated_at: hrs(26) },
  { id: "note-04", workspace_id: W, encounter_id: "enc-02", patient_id: "pt-02", note_type: "nursing", title_en: "Post-op day 1 nursing note", title_ar: "ملاحظة تمريضية بعد العملية بيوم", body_en: "Comfortable overnight, pain controlled on regular paracetamol. Tolerating free fluids and light diet. Mobilised to the bathroom independently. Wound sites clean and dry, no erythema. Passed urine normally. For consultant review with a view to discharge today.", body_ar: "مرتاحة طوال الليل مع سيطرة على الألم بالباراسيتامول المنتظم. تتحمل السوائل والغذاء الخفيف. تحركت للحمام بمفردها. مواضع الجرح نظيفة وجافة دون احمرار. التبول طبيعي. بانتظار مراجعة الاستشاري تمهيداً للخروج اليوم.", author_id: null, author_name: "Nurse Sara Bin Ali", author_role: "Staff Nurse", status: "signed", signed_at: hrs(4), amends_note_id: null, confidential: false, metadata: {}, created_at: hrs(4), updated_at: hrs(4) },
  { id: "note-05", workspace_id: W, encounter_id: "enc-06", patient_id: "pt-06", note_type: "progress", title_en: "ICU daily review — day 3", title_ar: "المراجعة اليومية للعناية المركزة — اليوم الثالث", body_en: "Urosepsis with septic shock, improving. Noradrenaline weaned from 0.28 to 0.06 mcg/kg/min overnight. Lactate down from 4.8 to 1.6. Temperature settled. Blood cultures grew E. coli sensitive to meropenem — continuing, day 3 of 7. Creatinine plateaued at 186; urine output 0.6 mL/kg/h. Still ventilated on pressure support, FiO2 0.35. Plan: sedation hold and spontaneous breathing trial this morning, aim to extubate today.", body_ar: "إنتان بولي مع صدمة إنتانية في تحسن. تم خفض النورأدرينالين من ٠٫٢٨ إلى ٠٫٠٦ خلال الليل. انخفض اللاكتات من ٤٫٨ إلى ١٫٦. استقرت الحرارة. أظهرت مزارع الدم إشريكية قولونية حساسة للميروبينيم — استمرار العلاج، اليوم الثالث من سبعة. استقر الكرياتينين عند ١٨٦ وإدرار البول ٠٫٦ مل/كغ/ساعة. لا يزال على التنفس الصناعي بدعم الضغط. الخطة: إيقاف التخدير مع تجربة تنفس تلقائي صباحاً بهدف نزع الأنبوب اليوم.", author_id: "prov-06", author_name: "Dr. Omar Bin Salem", author_role: "Consultant Intensivist", status: "signed", signed_at: hrs(4), amends_note_id: null, confidential: false, metadata: {}, created_at: hrs(4), updated_at: hrs(4) },
  { id: "note-06", workspace_id: W, encounter_id: "enc-03", patient_id: "pt-03", note_type: "consult", title_en: "Diabetes and renal review", title_ar: "مراجعة السكري والكلى", body_en: "HbA1c 8.4%, up from 7.6% six months ago. eGFR has fallen to 26 from 34 over the same period. Metformin stopped today — contraindicated below eGFR 30. Switched to linagliptin, which needs no renal adjustment. Documented sulfonamide allergy with angioedema, so gliclazide and any sulfonylurea are excluded. Referred to nephrology for access planning discussion. Repeat renal function in four weeks.", body_ar: "الهيموغلوبين السكري ٨٫٤٪ مرتفعاً من ٧٫٦٪ قبل ستة أشهر. انخفض معدل الترشيح إلى ٢٦ من ٣٤ في نفس الفترة. أُوقف الميتفورمين اليوم لكونه ممنوعاً تحت معدل ترشيح ٣٠. تم التحويل إلى ليناغليبتين الذي لا يحتاج تعديلاً كلوياً. الحساسية الموثقة من السلفوناميد مع وذمة وعائية تستبعد الغليكلازيد وأي سلفونيل يوريا. تم التحويل لأمراض الكلى لمناقشة تخطيط الوصول الوعائي. إعادة وظائف الكلى بعد أربعة أسابيع.", author_id: "prov-01", author_name: "Dr. Hala Al-Rasheed", author_role: "Consultant", status: "signed", signed_at: hrs(30), amends_note_id: null, confidential: false, metadata: {}, created_at: hrs(30), updated_at: hrs(30) },
  { id: "note-07", workspace_id: W, encounter_id: "enc-12", patient_id: "pt-12", note_type: "triage", title_en: "ED triage assessment", title_ar: "تقييم الفرز في الطوارئ", body_en: "Arrived by ambulance with two days of worsening breathlessness on a background of severe COPD. Speaking in short phrases, using accessory muscles. SpO2 88% on air, brought up to 91% on 28% Venturi — target range 88–92% given the CO2 retention risk. Nebulised salbutamol given at triage. Documented aspirin allergy with bronchospasm. Triage category 2, moved directly to majors.", body_ar: "وصل بالإسعاف مع ضيق تنفس متزايد منذ يومين على خلفية انسداد رئوي مزمن شديد. يتحدث بجمل قصيرة مع استخدام العضلات المساعدة. التشبع ٨٨٪ على الهواء وارتفع إلى ٩١٪ على قناع فنتوري ٢٨٪ — النطاق المستهدف ٨٨–٩٢٪ بسبب خطر احتباس ثاني أكسيد الكربون. أُعطي سالبوتامول بالبخاخ عند الفرز. حساسية موثقة من الأسبرين مع تشنج قصبي. تصنيف الفرز ٢ ونُقل مباشرة إلى قسم الحالات الكبرى.", author_id: null, author_name: "Nurse Khalid Al-Ruwais", author_role: "Triage Nurse", status: "signed", signed_at: mins(78), amends_note_id: null, confidential: false, metadata: {}, created_at: mins(80), updated_at: mins(78) },
  { id: "note-08", workspace_id: W, encounter_id: "enc-14", patient_id: "pt-14", note_type: "discharge", title_en: "Discharge summary — appendicectomy", title_ar: "ملخص الخروج — استئصال الزائدة", body_en: "Admitted with 12 hours of right iliac fossa pain. CT confirmed acute appendicitis without perforation. Laparoscopic appendicectomy performed the same evening; histology confirmed acute appendicitis. Recovery uneventful, apyrexial throughout, tolerating diet and mobilising. Discharged on day 3 with simple analgesia. Wound review in the community at 7 days, sutures dissolvable. Return immediately if fever, increasing pain or wound discharge.", body_ar: "دخل بألم في الحفرة الحرقفية اليمنى منذ ١٢ ساعة. أكدت الأشعة المقطعية التهاب الزائدة الحاد دون انثقاب. أُجري استئصال الزائدة بالمنظار في نفس المساء وأكد الفحص النسيجي التشخيص. التعافي دون مضاعفات مع غياب الحمى وتحمل الغذاء والحركة. خرج في اليوم الثالث بمسكنات بسيطة. مراجعة الجرح في الرعاية الأولية بعد سبعة أيام والغرز ذاتية الذوبان. العودة فوراً عند الحمى أو زيادة الألم أو إفرازات الجرح.", author_id: "prov-02", author_name: "Dr. Faisal Al-Harthy", author_role: "Consultant Surgeon", status: "signed", signed_at: hrs(26), amends_note_id: null, confidential: false, metadata: {}, created_at: hrs(27), updated_at: hrs(26) },
  { id: "note-09", workspace_id: W, encounter_id: "enc-08", patient_id: "pt-08", note_type: "progress", title_en: "Pre-operative review", title_ar: "مراجعة ما قبل العملية", body_en: "Closed left tibial shaft fracture from a road traffic accident. Neurovascularly intact, compartments soft, pain controlled in a backslab. Fasted since midnight. Listed for intramedullary nailing on today's trauma list, currently second on the list. Consent taken, side marked. Group and save sent, two units held.", body_ar: "كسر مغلق في جسم عظم الساق الأيسر نتيجة حادث مروري. الأوعية والأعصاب سليمة والحجيرات لينة والألم مسيطر عليه بالجبيرة الخلفية. صائم منذ منتصف الليل. مُدرج لتثبيت داخل النخاع على قائمة الرضوح اليوم وهو ثاني الترتيب. أُخذت الموافقة وعُلّم الجانب. أُرسلت فصيلة الدم مع حجز وحدتين.", author_id: "prov-09", author_name: "Dr. Bandar Al-Otaibi", author_role: "Consultant Orthopaedic Surgeon", status: "signed", signed_at: hrs(3), amends_note_id: null, confidential: false, metadata: {}, created_at: hrs(3), updated_at: hrs(3) },
  { id: "note-10", workspace_id: W, encounter_id: "enc-05", patient_id: "pt-05", note_type: "progress", title_en: "Paediatric review", title_ar: "مراجعة طب الأطفال", body_en: "Seven-year-old with a known asthma diagnosis, presented with an acute exacerbation after a viral upper respiratory infection. Initially required back-to-back salbutamol and ipratropium with oxygen. Now on air with SpO2 96%, respiratory rate down to 24, minimal wheeze. Oral prednisolone day 1 of 3. Observe a further four hours; if he remains stable on four-hourly salbutamol, discharge with a written asthma plan and a spacer technique check.", body_ar: "طفل عمره سبع سنوات مصاب بربو معروف، حضر بنوبة حادة بعد التهاب فيروسي في الجهاز التنفسي العلوي. احتاج في البداية سالبوتامول وإبراتروبيوم متتاليين مع الأكسجين. الآن على هواء الغرفة بتشبع ٩٦٪ ومعدل تنفس ٢٤ مع صفير بسيط. بريدنيزولون فموي اليوم الأول من ثلاثة. المراقبة أربع ساعات إضافية، وإن بقي مستقراً على السالبوتامول كل أربع ساعات يخرج بخطة ربو مكتوبة ومراجعة تقنية استخدام الفاصل.", author_id: "prov-08", author_name: "Dr. Rana Al-Suwailem", author_role: "Consultant Paediatrician", status: "signed", signed_at: hrs(1), amends_note_id: null, confidential: false, metadata: {}, created_at: hrs(1), updated_at: hrs(1) },
];
