/**
 * Clinical Demo Seed — theatres, emergency, revenue and operations.
 *
 * The third part of the cohort. The numbers here are chosen so the
 * operational dashboards show something worth looking at: an ED with a
 * genuine breach, a theatre list with a cancellation, a claims queue with
 * denials to work, and an interface engine with a dead-letter queue.
 */

import type { Database } from "@/domain/types";

type T<K extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][K]["Row"];

const W = "demo";
const d = (daysAgo: number) => new Date(Date.now() - daysAgo * 86_400_000).toISOString().slice(0, 10);
const ts = (daysAgo: number) => new Date(Date.now() - daysAgo * 86_400_000).toISOString();
const hrs = (hoursAgo: number) => new Date(Date.now() - hoursAgo * 3_600_000).toISOString();
const mins = (minutesAgo: number) => new Date(Date.now() - minutesAgo * 60_000).toISOString();
const inHrs = (hoursAhead: number) => new Date(Date.now() + hoursAhead * 3_600_000).toISOString();
const inDays = (daysAhead: number) => new Date(Date.now() + daysAhead * 86_400_000).toISOString().slice(0, 10);
const today = () => new Date().toISOString().slice(0, 10);

/** The WHO Surgical Safety Checklist, as stored on a case. */
const whoChecklist = (signIn: boolean, timeOut: boolean, signOut: boolean) => ({
  sign_in: { completed: signIn, items: ["Patient identity confirmed", "Site marked", "Anaesthesia check complete", "Pulse oximeter on", "Allergy checked", "Airway risk assessed"] },
  time_out: { completed: timeOut, items: ["Team introductions", "Patient, site and procedure confirmed", "Antibiotic prophylaxis given", "Critical steps anticipated", "Imaging displayed"] },
  sign_out: { completed: signOut, items: ["Procedure recorded", "Instrument and swab counts correct", "Specimen labelled", "Equipment problems noted", "Recovery concerns discussed"] },
});

// ─── Operating theatres ───────────────────────────────────

export const DEMO_OT_CASES: T<"ot_cases">[] = [
  { id: "ot-01", workspace_id: W, case_number: "OT-2026-02201", patient_id: "pt-02", patient_name: "Maryam Al-Ghamdi", patient_mrn: "MRN-100388", encounter_id: "enc-02", theatre: "Theatre 1", procedure_en: "Laparoscopic cholecystectomy", procedure_ar: "استئصال المرارة بالمنظار", procedure_code: "47562", laterality: "na", surgeon_id: "prov-02", surgeon_name: "Dr. Faisal Al-Harthy", assistant_name: "Dr. Sultan Al-Nasser", anaesthetist_name: "Dr. Yasser Al-Habib", scrub_nurse_name: "Nurse Amani Al-Zaid", circulating_nurse_name: "Nurse Latifa Al-Harbi", anaesthesia_type: "general", asa_grade: 2, urgency: "elective", status: "completed", scheduled_start: hrs(28), scheduled_end: hrs(26.5), actual_start: hrs(27.8), actual_end: hrs(26.2), duration_minutes: 96, turnover_minutes: 24, cancellation_reason: null, checklist: whoChecklist(true, true, true), blood_requested_units: 0, implants_used: [], specimen_sent: true, estimated_blood_loss_ml: 45, post_op_destination: "ward", notes_en: "Critical view of safety achieved. No bile leak. Uncomplicated.", metadata: {}, created_at: ts(6), updated_at: hrs(26) },
  { id: "ot-02", workspace_id: W, case_number: "OT-2026-02255", patient_id: "pt-08", patient_name: "Ibrahim Al-Zahrani", patient_mrn: "MRN-100822", encounter_id: "enc-08", theatre: "Theatre 3", procedure_en: "Intramedullary nailing, left tibia", procedure_ar: "تثبيت داخل النخاع لعظم الساق الأيسر", procedure_code: "27759", laterality: "left", surgeon_id: "prov-09", surgeon_name: "Dr. Bandar Al-Otaibi", assistant_name: "Dr. Meshal Al-Dosari", anaesthetist_name: "Dr. Yasser Al-Habib", scrub_nurse_name: "Nurse Amani Al-Zaid", circulating_nurse_name: "Nurse Latifa Al-Harbi", anaesthesia_type: "general", asa_grade: 1, urgency: "urgent", status: "pre_op", scheduled_start: inHrs(2), scheduled_end: inHrs(4), actual_start: null, actual_end: null, duration_minutes: null, turnover_minutes: null, cancellation_reason: null, checklist: whoChecklist(true, false, false), blood_requested_units: 2, implants_used: [], specimen_sent: false, estimated_blood_loss_ml: null, post_op_destination: "ward", notes_en: "Second on the trauma list. Group and save valid, two units crossmatched.", metadata: {}, created_at: hrs(18), updated_at: hrs(1) },
  { id: "ot-03", workspace_id: W, case_number: "OT-2026-02261", patient_id: "pt-04", patient_name: "Noura Al-Qahtani", patient_mrn: "MRN-100512", encounter_id: "enc-04", theatre: "Theatre 2 (Obstetric)", procedure_en: "Elective lower segment caesarean section", procedure_ar: "عملية قيصرية مخططة", procedure_code: "59510", laterality: "na", surgeon_id: "prov-07", surgeon_name: "Dr. Amal Al-Shamrani", assistant_name: "Dr. Wafa Al-Turki", anaesthetist_name: "Dr. Yasser Al-Habib", scrub_nurse_name: "Nurse Ghada Al-Mutlaq", circulating_nurse_name: "Nurse Sarah Al-Qahtani", anaesthesia_type: "spinal", asa_grade: 2, urgency: "elective", status: "scheduled", scheduled_start: inHrs(3), scheduled_end: inHrs(4.5), actual_start: null, actual_end: null, duration_minutes: null, turnover_minutes: null, cancellation_reason: null, checklist: whoChecklist(false, false, false), blood_requested_units: 2, implants_used: [], specimen_sent: false, estimated_blood_loss_ml: null, post_op_destination: "ward", notes_en: "Term, cephalic. Previous caesarean section.", metadata: { gestation_weeks: 39 }, created_at: hrs(13), updated_at: hrs(13) },
  { id: "ot-04", workspace_id: W, case_number: "OT-2026-02244", patient_id: "pt-07", patient_name: "Sara Al-Mutairi", patient_mrn: "MRN-100714", encounter_id: "enc-07", theatre: "Theatre 4 (Day case)", procedure_en: "Phacoemulsification with intraocular lens, right eye", procedure_ar: "استحلاب العدسة مع زرع عدسة، العين اليمنى", procedure_code: "66984", laterality: "right", surgeon_id: "prov-02", surgeon_name: "Dr. Faisal Al-Harthy", assistant_name: null, anaesthetist_name: null, scrub_nurse_name: "Nurse Ghada Al-Mutlaq", circulating_nurse_name: null, anaesthesia_type: "local", asa_grade: 2, urgency: "elective", status: "completed", scheduled_start: hrs(31), scheduled_end: hrs(30.5), actual_start: hrs(31), actual_end: hrs(30.4), duration_minutes: 36, turnover_minutes: 18, cancellation_reason: null, checklist: whoChecklist(true, true, true), blood_requested_units: 0, implants_used: [{ type: "IOL", model: "AcrySof IQ SN60WF", power: "21.5 D", serial: "IOL-88213" }], specimen_sent: false, estimated_blood_loss_ml: 0, post_op_destination: "day_case_discharge", notes_en: "Uncomplicated. Lens in the bag, well centred.", metadata: {}, created_at: ts(9), updated_at: hrs(30) },
  { id: "ot-05", workspace_id: W, case_number: "OT-2026-02270", patient_id: "pt-13", patient_name: "Reem Al-Faisal", patient_mrn: "MRN-101315", encounter_id: null, theatre: "Theatre 1", procedure_en: "Total thyroidectomy", procedure_ar: "استئصال الغدة الدرقية بالكامل", procedure_code: "60240", laterality: "na", surgeon_id: "prov-02", surgeon_name: "Dr. Faisal Al-Harthy", assistant_name: null, anaesthetist_name: null, scrub_nurse_name: null, circulating_nurse_name: null, anaesthesia_type: "general", asa_grade: 2, urgency: "elective", status: "cancelled", scheduled_start: hrs(30), scheduled_end: hrs(27), actual_start: null, actual_end: null, duration_minutes: null, turnover_minutes: null, cancellation_reason: "Theatre 1 anaesthetic machine failed the pre-use check — see BIOM-WO-0229. Rescheduled.", checklist: whoChecklist(false, false, false), blood_requested_units: 0, implants_used: [], specimen_sent: false, estimated_blood_loss_ml: null, post_op_destination: "ward", notes_en: null, metadata: { cancellation_category: "equipment" }, created_at: ts(12), updated_at: hrs(31) },
  { id: "ot-06", workspace_id: W, case_number: "OT-2026-02280", patient_id: "pt-14", patient_name: "Saud Al-Amri", patient_mrn: "MRN-101402", encounter_id: "enc-14", theatre: "Theatre 3", procedure_en: "Laparoscopic appendicectomy", procedure_ar: "استئصال الزائدة بالمنظار", procedure_code: "44970", laterality: "na", surgeon_id: "prov-02", surgeon_name: "Dr. Faisal Al-Harthy", assistant_name: "Dr. Sultan Al-Nasser", anaesthetist_name: "Dr. Yasser Al-Habib", scrub_nurse_name: "Nurse Amani Al-Zaid", circulating_nurse_name: "Nurse Latifa Al-Harbi", anaesthesia_type: "general", asa_grade: 1, urgency: "emergency", status: "completed", scheduled_start: hrs(94), scheduled_end: hrs(92.5), actual_start: hrs(93.6), actual_end: hrs(92.4), duration_minutes: 72, turnover_minutes: 30, cancellation_reason: null, checklist: whoChecklist(true, true, true), blood_requested_units: 0, implants_used: [], specimen_sent: true, estimated_blood_loss_ml: 30, post_op_destination: "ward", notes_en: "Inflamed but not perforated. Specimen to histology.", metadata: {}, created_at: ts(4), updated_at: hrs(92) },
  { id: "ot-07", workspace_id: W, case_number: "OT-2026-02291", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", patient_mrn: "MRN-100241", encounter_id: "enc-01", theatre: "Cath Lab 1", procedure_en: "Coronary angiography ± PCI", procedure_ar: "قسطرة تشخيصية مع احتمال توسيع", procedure_code: "93458", laterality: "na", surgeon_id: "prov-01", surgeon_name: "Dr. Hala Al-Rasheed", assistant_name: null, anaesthetist_name: null, scrub_nurse_name: "Nurse Mona Al-Faraj", circulating_nurse_name: null, anaesthesia_type: "sedation", asa_grade: 3, urgency: "urgent", status: "scheduled", scheduled_start: inHrs(14), scheduled_end: inHrs(16), actual_start: null, actual_end: null, duration_minutes: null, turnover_minutes: null, cancellation_reason: null, checklist: whoChecklist(false, false, false), blood_requested_units: 0, implants_used: [], specimen_sent: false, estimated_blood_loss_ml: null, post_op_destination: "ward", notes_en: "NSTEMI, rising troponin. Radial approach planned.", metadata: {}, created_at: hrs(2), updated_at: hrs(2) },
];

// ─── Emergency department ─────────────────────────────────

export const DEMO_ED_VISITS: T<"ed_visits">[] = [
  { id: "ed-01", workspace_id: W, encounter_id: "enc-12", patient_id: "pt-12", patient_name: "Turki Al-Malki", patient_mrn: "MRN-101208", arrival_at: mins(95), arrival_mode: "ambulance", triage_level: 2, triage_at: mins(88), triage_nurse: "Nurse Khalid Al-Ruwais", complaint_en: "Increasing breathlessness, known severe COPD", complaint_ar: "ضيق تنفس متزايد مع انسداد رئوي مزمن شديد", area: "majors", status: "in_treatment", seen_at: mins(78), seen_by: "Dr. Nasser Al-Juhani", door_to_doctor_minutes: 17, total_los_minutes: null, disposition: null, disposition_at: null, admitted_to_ward_id: null, boarding_since: null, is_trauma: false, metadata: { news2_on_arrival: 9 }, created_at: mins(95), updated_at: mins(25) },
  { id: "ed-02", workspace_id: W, encounter_id: "enc-10", patient_id: "pt-10", patient_name: "Majed Al-Rashid", patient_mrn: "MRN-101034", arrival_at: mins(50), arrival_mode: "walk_in", triage_level: 4, triage_at: mins(44), triage_nurse: "Nurse Khalid Al-Ruwais", complaint_en: "Inversion ankle injury, unable to weight bear", complaint_ar: "التواء في الكاحل مع عدم القدرة على المشي", area: "fast_track", status: "awaiting_results", seen_at: mins(30), seen_by: "Dr. Rakan Al-Shammari", door_to_doctor_minutes: 20, total_los_minutes: null, disposition: null, disposition_at: null, admitted_to_ward_id: null, boarding_since: null, is_trauma: false, metadata: { ottawa_rules_positive: true, awaiting: "Ankle X-ray" }, created_at: mins(50), updated_at: mins(30) },
  { id: "ed-03", workspace_id: W, encounter_id: "enc-01", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", patient_mrn: "MRN-100241", arrival_at: hrs(12), arrival_mode: "ambulance", triage_level: 2, triage_at: hrs(11.9), triage_nurse: "Nurse Khalid Al-Ruwais", complaint_en: "Central chest pain radiating to the left arm", complaint_ar: "ألم صدري مركزي يمتد للذراع الأيسر", area: "departed", status: "departed", seen_at: hrs(11.8), seen_by: "Dr. Nasser Al-Juhani", door_to_doctor_minutes: 12, total_los_minutes: 180, disposition: "admitted", disposition_at: hrs(9), admitted_to_ward_id: "wd-01", boarding_since: null, is_trauma: false, metadata: {}, created_at: hrs(12), updated_at: hrs(9) },
  { id: "ed-04", workspace_id: W, encounter_id: "enc-05", patient_id: "pt-05", patient_name: "Yousef Al-Dosari", patient_mrn: "MRN-100603", arrival_at: hrs(7), arrival_mode: "walk_in", triage_level: 3, triage_at: hrs(6.9), triage_nurse: "Nurse Khalid Al-Ruwais", complaint_en: "Wheeze and difficulty breathing, known asthma", complaint_ar: "صفير وصعوبة تنفس مع ربو معروف", area: "departed", status: "departed", seen_at: hrs(6.6), seen_by: "Dr. Rana Al-Suwailem", door_to_doctor_minutes: 24, total_los_minutes: 120, disposition: "admitted", disposition_at: hrs(5), admitted_to_ward_id: "wd-05", boarding_since: null, is_trauma: false, metadata: {}, created_at: hrs(7), updated_at: hrs(5) },
  { id: "ed-05", workspace_id: W, encounter_id: "enc-08", patient_id: "pt-08", patient_name: "Ibrahim Al-Zahrani", patient_mrn: "MRN-100822", arrival_at: hrs(23), arrival_mode: "ambulance", triage_level: 2, triage_at: hrs(22.9), triage_nurse: "Nurse Khalid Al-Ruwais", complaint_en: "Left leg deformity after road traffic accident", complaint_ar: "تشوه في الساق اليسرى بعد حادث مروري", area: "departed", status: "departed", seen_at: hrs(22.8), seen_by: "Dr. Nasser Al-Juhani", door_to_doctor_minutes: 8, total_los_minutes: 180, disposition: "admitted", disposition_at: hrs(20), admitted_to_ward_id: "wd-02", boarding_since: hrs(21.5), is_trauma: true, metadata: { trauma_team_activated: true }, created_at: hrs(23), updated_at: hrs(20) },
  // The breach: a triage 3 waiting well past target with nowhere to go.
  { id: "ed-06", workspace_id: W, encounter_id: "enc-10", patient_id: "pt-10", patient_name: "Waleed Al-Harbi", patient_mrn: "MRN-101511", arrival_at: mins(210), arrival_mode: "walk_in", triage_level: 3, triage_at: mins(198), triage_nurse: "Nurse Khalid Al-Ruwais", complaint_en: "Abdominal pain, vomiting for two days", complaint_ar: "ألم بطني وقيء منذ يومين", area: "waiting", status: "waiting", seen_at: null, seen_by: null, door_to_doctor_minutes: null, total_los_minutes: null, disposition: null, disposition_at: null, admitted_to_ward_id: null, boarding_since: null, is_trauma: false, metadata: { breach: true, target_minutes: 30, waited_minutes: 198 }, created_at: mins(210), updated_at: mins(198) },
  { id: "ed-07", workspace_id: W, encounter_id: "enc-10", patient_id: "pt-10", patient_name: "Aisha Al-Kathiri", patient_mrn: "MRN-101522", arrival_at: mins(140), arrival_mode: "walk_in", triage_level: 5, triage_at: mins(132), triage_nurse: "Nurse Khalid Al-Ruwais", complaint_en: "Repeat prescription request, sore throat", complaint_ar: "طلب إعادة وصفة مع التهاب حلق", area: "waiting", status: "waiting", seen_at: null, seen_by: null, door_to_doctor_minutes: null, total_los_minutes: null, disposition: null, disposition_at: null, admitted_to_ward_id: null, boarding_since: null, is_trauma: false, metadata: { suitable_for_redirection: true }, created_at: mins(140), updated_at: mins(132) },
  { id: "ed-08", workspace_id: W, encounter_id: "enc-10", patient_id: "pt-10", patient_name: "Mansour Al-Ghanim", patient_mrn: "MRN-101533", arrival_at: mins(320), arrival_mode: "ambulance", triage_level: 1, triage_at: mins(319), triage_nurse: "Nurse Khalid Al-Ruwais", complaint_en: "Out-of-hospital cardiac arrest, ROSC achieved", complaint_ar: "سكتة قلبية خارج المستشفى مع عودة الدورة الدموية", area: "resus", status: "in_treatment", seen_at: mins(319), seen_by: "Dr. Nasser Al-Juhani", door_to_doctor_minutes: 1, total_los_minutes: null, disposition: null, disposition_at: null, admitted_to_ward_id: null, boarding_since: mins(180), is_trauma: false, metadata: { awaiting_icu_bed: true, boarding_hours: 3 }, created_at: mins(320), updated_at: mins(60) },
  { id: "ed-09", workspace_id: W, encounter_id: "enc-10", patient_id: "pt-10", patient_name: "Dalal Al-Suhaimi", patient_mrn: "MRN-101544", arrival_at: hrs(6), arrival_mode: "walk_in", triage_level: 4, triage_at: hrs(5.8), triage_nurse: "Nurse Khalid Al-Ruwais", complaint_en: "Laceration to the left hand", complaint_ar: "جرح قطعي في اليد اليسرى", area: "departed", status: "departed", seen_at: hrs(5.2), seen_by: "Dr. Rakan Al-Shammari", door_to_doctor_minutes: 48, total_los_minutes: 105, disposition: "discharged", disposition_at: hrs(4.2), admitted_to_ward_id: null, boarding_since: null, is_trauma: false, metadata: { sutures: 4 }, created_at: hrs(6), updated_at: hrs(4.2) },
  { id: "ed-10", workspace_id: W, encounter_id: "enc-10", patient_id: "pt-10", patient_name: "Faris Al-Dhaheri", patient_mrn: "MRN-101555", arrival_at: hrs(9), arrival_mode: "walk_in", triage_level: 4, triage_at: hrs(8.7), triage_nurse: "Nurse Khalid Al-Ruwais", complaint_en: "Headache, three days", complaint_ar: "صداع منذ ثلاثة أيام", area: "departed", status: "left_without_being_seen", seen_at: null, seen_by: null, door_to_doctor_minutes: null, total_los_minutes: 145, disposition: "lwbs", disposition_at: hrs(6.6), admitted_to_ward_id: null, boarding_since: null, is_trauma: false, metadata: { waited_minutes: 145 }, created_at: hrs(9), updated_at: hrs(6.6) },
];

// ─── Appointments ─────────────────────────────────────────

export const DEMO_APPOINTMENTS: T<"appointments">[] = [
  { id: "appt-01", workspace_id: W, appointment_number: "APT-2026-99120", patient_id: "pt-03", patient_name: "Fatima Al-Harbi", patient_mrn: "MRN-100455", patient_phone: "+966-50-664-7788", provider_id: "prov-01", provider_name: "Dr. Hala Al-Rasheed", department_id: "dept-02", department_name: "Cardiology", clinic_room: "Clinic 3A", appointment_type: "follow_up", slot_start: hrs(31), slot_end: hrs(30.5), duration_minutes: 30, status: "completed", reason_en: "Diabetes and renal review", reason_ar: "مراجعة السكري والكلى", booked_by: "Reception — Amal Al-Duwaish", booked_at: ts(28), reminder_sent_at: ts(1), confirmed_at: ts(1), arrived_at: hrs(31.3), cancellation_reason: null, rescheduled_from_id: null, is_telehealth: false, insurance_policy_id: "pol-03", metadata: {}, created_at: ts(28), updated_at: hrs(30) },
  { id: "appt-02", workspace_id: W, appointment_number: "APT-2026-99244", patient_id: "pt-11", patient_name: "Layla Al-Anazi", patient_mrn: "MRN-101120", patient_phone: "+966-50-667-8899", provider_id: "prov-14", provider_name: "Dr. Lina Al-Yousef", department_id: "dept-13", department_name: "Dermatology", clinic_room: null, appointment_type: "telehealth", slot_start: hrs(3), slot_end: hrs(2.75), duration_minutes: 15, status: "completed", reason_en: "Eczema follow-up", reason_ar: "متابعة الإكزيما", booked_by: "Patient portal", booked_at: ts(10), reminder_sent_at: ts(1), confirmed_at: ts(1), arrived_at: hrs(3.05), cancellation_reason: null, rescheduled_from_id: null, is_telehealth: true, insurance_policy_id: "pol-11", metadata: {}, created_at: ts(10), updated_at: hrs(2.75) },
  { id: "appt-03", workspace_id: W, appointment_number: "APT-2026-99301", patient_id: "pt-13", patient_name: "Reem Al-Faisal", patient_mrn: "MRN-101315", patient_phone: "+966-50-334-1122", provider_id: "prov-01", provider_name: "Dr. Hala Al-Rasheed", department_id: "dept-02", department_name: "Cardiology", clinic_room: "Clinic 3B", appointment_type: "follow_up", slot_start: inHrs(28), slot_end: inHrs(28.5), duration_minutes: 30, status: "confirmed", reason_en: "Thyroid function recheck", reason_ar: "إعادة فحص وظائف الغدة الدرقية", booked_by: "Reception — Amal Al-Duwaish", booked_at: hrs(46), reminder_sent_at: hrs(4), confirmed_at: hrs(3.5), arrived_at: null, cancellation_reason: null, rescheduled_from_id: null, is_telehealth: false, insurance_policy_id: "pol-13", metadata: {}, created_at: hrs(46), updated_at: hrs(3.5) },
  { id: "appt-04", workspace_id: W, appointment_number: "APT-2026-99355", patient_id: "pt-09", patient_name: "Hessa Al-Subaie", patient_mrn: "MRN-100901", patient_phone: "+966-50-887-9900", provider_id: "prov-13", provider_name: "Dr. Ziad Al-Mansour", department_id: "dept-12", department_name: "Oncology Day Unit", clinic_room: "Day Unit Bay 4", appointment_type: "procedure", slot_start: hrs(8), slot_end: hrs(3), duration_minutes: 300, status: "in_progress", reason_en: "FOLFOX cycle 4", reason_ar: "الدورة الرابعة من فولفوكس", booked_by: "Oncology scheduling", booked_at: ts(14), reminder_sent_at: ts(1), confirmed_at: ts(2), arrived_at: hrs(8.1), cancellation_reason: null, rescheduled_from_id: null, is_telehealth: false, insurance_policy_id: "pol-09", metadata: {}, created_at: ts(14), updated_at: hrs(6) },
  { id: "appt-05", workspace_id: W, appointment_number: "APT-2026-99401", patient_id: "pt-07", patient_name: "Sara Al-Mutairi", patient_mrn: "MRN-100714", patient_phone: "+966-50-998-2233", provider_id: "prov-02", provider_name: "Dr. Faisal Al-Harthy", department_id: "dept-03", department_name: "General Surgery", clinic_room: "Clinic 4A", appointment_type: "review", slot_start: inHrs(160), slot_end: inHrs(160.25), duration_minutes: 15, status: "booked", reason_en: "Post-cataract review, right eye", reason_ar: "مراجعة بعد عملية المياه البيضاء للعين اليمنى", booked_by: "Day unit discharge", booked_at: hrs(26), reminder_sent_at: null, confirmed_at: null, arrived_at: null, cancellation_reason: null, rescheduled_from_id: null, is_telehealth: false, insurance_policy_id: "pol-07", metadata: {}, created_at: hrs(26), updated_at: hrs(26) },
  { id: "appt-06", workspace_id: W, appointment_number: "APT-2026-99422", patient_id: "pt-14", patient_name: "Saud Al-Amri", patient_mrn: "MRN-101402", patient_phone: "+966-50-445-9988", provider_id: "prov-02", provider_name: "Dr. Faisal Al-Harthy", department_id: "dept-03", department_name: "General Surgery", clinic_room: "Clinic 4A", appointment_type: "review", slot_start: inHrs(150), slot_end: inHrs(150.25), duration_minutes: 15, status: "booked", reason_en: "Post-appendicectomy wound review", reason_ar: "مراجعة جرح استئصال الزائدة", booked_by: "Ward discharge", booked_at: hrs(26), reminder_sent_at: null, confirmed_at: null, arrived_at: null, cancellation_reason: null, rescheduled_from_id: null, is_telehealth: false, insurance_policy_id: "pol-14", metadata: {}, created_at: hrs(26), updated_at: hrs(26) },
  { id: "appt-07", workspace_id: W, appointment_number: "APT-2026-99188", patient_id: "pt-05", patient_name: "Yousef Al-Dosari", patient_mrn: "MRN-100603", patient_phone: "+966-50-221-3344", provider_id: "prov-08", provider_name: "Dr. Rana Al-Suwailem", department_id: "dept-06", department_name: "Paediatrics", clinic_room: "Paeds Clinic 1", appointment_type: "follow_up", slot_start: ts(3), slot_end: ts(3), duration_minutes: 20, status: "no_show", reason_en: "Asthma control review", reason_ar: "مراجعة السيطرة على الربو", booked_by: "Reception — Amal Al-Duwaish", booked_at: ts(35), reminder_sent_at: ts(4), confirmed_at: null, arrived_at: null, cancellation_reason: null, rescheduled_from_id: null, is_telehealth: false, insurance_policy_id: "pol-05", metadata: { note: "Missed review preceded this week's exacerbation" }, created_at: ts(35), updated_at: ts(3) },
  { id: "appt-08", workspace_id: W, appointment_number: "APT-2026-99455", patient_id: "pt-11", patient_name: "Layla Al-Anazi", patient_mrn: "MRN-101120", patient_phone: "+966-50-667-8899", provider_id: "prov-14", provider_name: "Dr. Lina Al-Yousef", department_id: "dept-13", department_name: "Dermatology", clinic_room: null, appointment_type: "telehealth", slot_start: inHrs(720), slot_end: inHrs(720.25), duration_minutes: 15, status: "booked", reason_en: "Six-week eczema review", reason_ar: "مراجعة الإكزيما بعد ستة أسابيع", booked_by: "Patient portal", booked_at: hrs(2.7), reminder_sent_at: null, confirmed_at: null, arrived_at: null, cancellation_reason: null, rescheduled_from_id: null, is_telehealth: true, insurance_policy_id: "pol-11", metadata: {}, created_at: hrs(2.7), updated_at: hrs(2.7) },
  { id: "appt-09", workspace_id: W, appointment_number: "APT-2026-99470", patient_id: "pt-03", patient_name: "Fatima Al-Harbi", patient_mrn: "MRN-100455", patient_phone: "+966-50-664-7788", provider_id: "prov-01", provider_name: "Dr. Hala Al-Rasheed", department_id: "dept-02", department_name: "Cardiology", clinic_room: "Clinic 3A", appointment_type: "follow_up", slot_start: inHrs(672), slot_end: inHrs(672.5), duration_minutes: 30, status: "booked", reason_en: "Repeat renal function after four weeks", reason_ar: "إعادة وظائف الكلى بعد أربعة أسابيع", booked_by: "Dr. Hala Al-Rasheed", booked_at: hrs(30), reminder_sent_at: null, confirmed_at: null, arrived_at: null, cancellation_reason: null, rescheduled_from_id: null, is_telehealth: false, insurance_policy_id: "pol-03", metadata: {}, created_at: hrs(30), updated_at: hrs(30) },
  { id: "appt-10", workspace_id: W, appointment_number: "APT-2026-99099", patient_id: "pt-13", patient_name: "Reem Al-Faisal", patient_mrn: "MRN-101315", patient_phone: "+966-50-334-1122", provider_id: "prov-04", provider_name: "Dr. Maha Al-Sanea", department_id: "dept-02", department_name: "Cardiology", clinic_room: "Clinic 3B", appointment_type: "follow_up", slot_start: hrs(48), slot_end: hrs(47.5), duration_minutes: 30, status: "completed", reason_en: "Thyroid function review", reason_ar: "مراجعة وظائف الغدة الدرقية", booked_by: "Reception — Amal Al-Duwaish", booked_at: ts(40), reminder_sent_at: ts(3), confirmed_at: ts(3), arrived_at: hrs(48.1), cancellation_reason: null, rescheduled_from_id: null, is_telehealth: false, insurance_policy_id: "pol-13", metadata: {}, created_at: ts(40), updated_at: hrs(47.5) },
];

// ─── Insurance & revenue cycle ────────────────────────────

export const DEMO_INSURANCE_POLICIES: T<"insurance_policies">[] = [
  { id: "pol-01", workspace_id: W, patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", payer_id: "pay-01", payer_name: "Bupa Arabia", policy_number: "BUP-4471209", plan_name: "Bupa Gold Inpatient", coverage_rank: "primary", policy_holder_name: "Khalid Al-Otaibi", relationship_to_holder: "self", effective_from: d(300), effective_to: inDays(65), coverage_percent: 90, copay_amount: 100, deductible_amount: 500, deductible_met: 500, annual_limit: 500000, eligibility_status: "verified", eligibility_checked_at: hrs(11), requires_pre_auth: true, status: "active", metadata: {}, created_at: ts(300), updated_at: hrs(11) },
  { id: "pol-02", workspace_id: W, patient_id: "pt-02", patient_name: "Maryam Al-Ghamdi", payer_id: "pay-02", payer_name: "Tawuniya", policy_number: "TAW-8812004", plan_name: "Tawuniya Comprehensive", coverage_rank: "primary", policy_holder_name: "Saeed Al-Ghamdi", relationship_to_holder: "spouse", effective_from: d(400), effective_to: inDays(330), coverage_percent: 80, copay_amount: 150, deductible_amount: 1000, deductible_met: 1000, annual_limit: 300000, eligibility_status: "verified", eligibility_checked_at: hrs(30), requires_pre_auth: true, status: "active", metadata: {}, created_at: ts(400), updated_at: hrs(30) },
  { id: "pol-03", workspace_id: W, patient_id: "pt-03", patient_name: "Fatima Al-Harbi", payer_id: "pay-03", payer_name: "MedGulf", policy_number: "MG-2290117", plan_name: "MedGulf Senior Care", coverage_rank: "primary", policy_holder_name: "Fatima Al-Harbi", relationship_to_holder: "self", effective_from: d(200), effective_to: inDays(165), coverage_percent: 85, copay_amount: 75, deductible_amount: 400, deductible_met: 260, annual_limit: 250000, eligibility_status: "verified", eligibility_checked_at: hrs(31), requires_pre_auth: false, status: "active", metadata: {}, created_at: ts(200), updated_at: hrs(31) },
  { id: "pol-04", workspace_id: W, patient_id: "pt-04", patient_name: "Noura Al-Qahtani", payer_id: "pay-01", payer_name: "Bupa Arabia", policy_number: "BUP-4490882", plan_name: "Bupa Maternity Plus", coverage_rank: "primary", policy_holder_name: "Sultan Al-Qahtani", relationship_to_holder: "spouse", effective_from: d(280), effective_to: inDays(85), coverage_percent: 100, copay_amount: 0, deductible_amount: 0, deductible_met: 0, annual_limit: 120000, eligibility_status: "verified", eligibility_checked_at: hrs(15), requires_pre_auth: true, status: "active", metadata: { maternity_preauth: "PA-2026-3391" }, created_at: ts(280), updated_at: hrs(15) },
  { id: "pol-05", workspace_id: W, patient_id: "pt-05", patient_name: "Yousef Al-Dosari", payer_id: "pay-02", payer_name: "Tawuniya", policy_number: "TAW-8830115", plan_name: "Tawuniya Family", coverage_rank: "primary", policy_holder_name: "Hind Al-Dosari", relationship_to_holder: "child", effective_from: d(500), effective_to: inDays(230), coverage_percent: 90, copay_amount: 50, deductible_amount: 300, deductible_met: 300, annual_limit: 200000, eligibility_status: "verified", eligibility_checked_at: hrs(6), requires_pre_auth: false, status: "active", metadata: {}, created_at: ts(500), updated_at: hrs(6) },
  { id: "pol-06", workspace_id: W, patient_id: "pt-06", patient_name: "Abdullah Al-Shehri", payer_id: "pay-04", payer_name: "Ministry of Health", policy_number: "MOH-1011223344", plan_name: "National Citizen Coverage", coverage_rank: "primary", policy_holder_name: "Abdullah Al-Shehri", relationship_to_holder: "self", effective_from: d(3000), effective_to: null, coverage_percent: 100, copay_amount: 0, deductible_amount: 0, deductible_met: 0, annual_limit: null, eligibility_status: "verified", eligibility_checked_at: hrs(78), requires_pre_auth: false, status: "active", metadata: {}, created_at: ts(1500), updated_at: hrs(78) },
  { id: "pol-07", workspace_id: W, patient_id: "pt-07", patient_name: "Sara Al-Mutairi", payer_id: "pay-03", payer_name: "MedGulf", policy_number: "MG-2291884", plan_name: "MedGulf Standard", coverage_rank: "primary", policy_holder_name: "Sara Al-Mutairi", relationship_to_holder: "self", effective_from: d(380), effective_to: inDays(-5), coverage_percent: 80, copay_amount: 100, deductible_amount: 500, deductible_met: 500, annual_limit: 150000, eligibility_status: "inactive", eligibility_checked_at: hrs(34), requires_pre_auth: true, status: "expired", metadata: { note: "Policy lapsed five days ago — claim at risk" }, created_at: ts(380), updated_at: hrs(34) },
  { id: "pol-08", workspace_id: W, patient_id: "pt-08", patient_name: "Ibrahim Al-Zahrani", payer_id: "pay-05", payer_name: "Al Rajhi Takaful", policy_number: "ART-5580912", plan_name: "Takaful Corporate", coverage_rank: "primary", policy_holder_name: "Ibrahim Al-Zahrani", relationship_to_holder: "self", effective_from: d(150), effective_to: inDays(215), coverage_percent: 90, copay_amount: 0, deductible_amount: 0, deductible_met: 0, annual_limit: 400000, eligibility_status: "verified", eligibility_checked_at: hrs(21), requires_pre_auth: true, status: "active", metadata: { rta_third_party: true }, created_at: ts(150), updated_at: hrs(21) },
  { id: "pol-09", workspace_id: W, patient_id: "pt-09", patient_name: "Hessa Al-Subaie", payer_id: "pay-01", payer_name: "Bupa Arabia", policy_number: "BUP-4402277", plan_name: "Bupa Platinum", coverage_rank: "primary", policy_holder_name: "Hessa Al-Subaie", relationship_to_holder: "self", effective_from: d(600), effective_to: inDays(130), coverage_percent: 100, copay_amount: 0, deductible_amount: 0, deductible_met: 0, annual_limit: 1000000, eligibility_status: "verified", eligibility_checked_at: hrs(8), requires_pre_auth: true, status: "active", metadata: { oncology_preauth: "PA-2026-2201" }, created_at: ts(600), updated_at: hrs(8) },
  { id: "pol-11", workspace_id: W, patient_id: "pt-11", patient_name: "Layla Al-Anazi", payer_id: "pay-02", payer_name: "Tawuniya", policy_number: "TAW-8841190", plan_name: "Tawuniya Essential", coverage_rank: "primary", policy_holder_name: "Layla Al-Anazi", relationship_to_holder: "self", effective_from: d(180), effective_to: inDays(185), coverage_percent: 70, copay_amount: 120, deductible_amount: 800, deductible_met: 240, annual_limit: 100000, eligibility_status: "verified", eligibility_checked_at: hrs(4), requires_pre_auth: false, status: "active", metadata: {}, created_at: ts(180), updated_at: hrs(4) },
  { id: "pol-12", workspace_id: W, patient_id: "pt-12", patient_name: "Turki Al-Malki", payer_id: "pay-04", payer_name: "Ministry of Health", policy_number: "MOH-1099001122", plan_name: "National Citizen Coverage", coverage_rank: "primary", policy_holder_name: "Turki Al-Malki", relationship_to_holder: "self", effective_from: d(3000), effective_to: null, coverage_percent: 100, copay_amount: 0, deductible_amount: 0, deductible_met: 0, annual_limit: null, eligibility_status: "pending", eligibility_checked_at: null, requires_pre_auth: false, status: "active", metadata: { note: "Eligibility check queued — arrived by ambulance" }, created_at: ts(1100), updated_at: mins(90) },
  { id: "pol-13", workspace_id: W, patient_id: "pt-13", patient_name: "Reem Al-Faisal", payer_id: "pay-05", payer_name: "Al Rajhi Takaful", policy_number: "ART-5591044", plan_name: "Takaful Individual", coverage_rank: "primary", policy_holder_name: "Reem Al-Faisal", relationship_to_holder: "self", effective_from: d(450), effective_to: inDays(280), coverage_percent: 80, copay_amount: 100, deductible_amount: 600, deductible_met: 600, annual_limit: 180000, eligibility_status: "verified", eligibility_checked_at: hrs(48), requires_pre_auth: false, status: "active", metadata: {}, created_at: ts(450), updated_at: hrs(48) },
  { id: "pol-14", workspace_id: W, patient_id: "pt-14", patient_name: "Saud Al-Amri", payer_id: "pay-03", payer_name: "MedGulf", policy_number: "MG-2288001", plan_name: "MedGulf Comprehensive", coverage_rank: "primary", policy_holder_name: "Saud Al-Amri", relationship_to_holder: "self", effective_from: d(320), effective_to: inDays(45), coverage_percent: 85, copay_amount: 100, deductible_amount: 500, deductible_met: 500, annual_limit: 300000, eligibility_status: "verified", eligibility_checked_at: hrs(99), requires_pre_auth: false, status: "active", metadata: {}, created_at: ts(320), updated_at: hrs(99) },
];

export const DEMO_CHARGE_ITEMS: T<"charge_items">[] = [
  { id: "chg-01", workspace_id: W, encounter_id: "enc-14", patient_id: "pt-14", invoice_id: "inv-h01", cpt_code: "44970", description_en: "Laparoscopic appendicectomy", description_ar: "استئصال الزائدة بالمنظار", category: "theatre", quantity: 1, unit_price: 14500, total: 14500, contracted_price: 12800, discount_amount: 0, department_id: "dept-11", department_name: "Operating Theatres", source_type: "ot_case", source_id: "ot-06", charged_at: hrs(92), posted: true, metadata: {}, created_at: hrs(92), updated_at: hrs(30) },
  { id: "chg-02", workspace_id: W, encounter_id: "enc-14", patient_id: "pt-14", invoice_id: "inv-h01", cpt_code: "99232", description_en: "Inpatient bed day, general ward", description_ar: "يوم إقامة في جناح عام", category: "bed", quantity: 3, unit_price: 1200, total: 3600, contracted_price: 3300, discount_amount: 0, department_id: "dept-03", department_name: "General Surgery", source_type: "encounter", source_id: "enc-14", charged_at: hrs(30), posted: true, metadata: {}, created_at: hrs(30), updated_at: hrs(30) },
  { id: "chg-03", workspace_id: W, encounter_id: "enc-14", patient_id: "pt-14", invoice_id: "inv-h01", cpt_code: "74177", description_en: "CT abdomen and pelvis with contrast", description_ar: "أشعة مقطعية للبطن والحوض بالصبغة", category: "imaging", quantity: 1, unit_price: 2400, total: 2400, contracted_price: 2100, discount_amount: 0, department_id: "dept-09", department_name: "Radiology", source_type: "imaging_order", source_id: null, charged_at: hrs(96), posted: true, metadata: {}, created_at: hrs(96), updated_at: hrs(30) },
  { id: "chg-04", workspace_id: W, encounter_id: "enc-14", patient_id: "pt-14", invoice_id: "inv-h01", cpt_code: null, description_en: "Discharge medication", description_ar: "أدوية الخروج", category: "medication", quantity: 1, unit_price: 56, total: 56, contracted_price: 56, discount_amount: 0, department_id: "dept-10", department_name: "Pharmacy", source_type: "dispense", source_id: "disp-01", charged_at: hrs(25), posted: true, metadata: {}, created_at: hrs(25), updated_at: hrs(25) },
  { id: "chg-05", workspace_id: W, encounter_id: "enc-01", patient_id: "pt-01", invoice_id: null, cpt_code: "99223", description_en: "Initial inpatient consultation, high complexity", description_ar: "استشارة دخول أولية عالية التعقيد", category: "consultation", quantity: 1, unit_price: 1800, total: 1800, contracted_price: 1620, discount_amount: 0, department_id: "dept-02", department_name: "Cardiology", source_type: "encounter", source_id: "enc-01", charged_at: hrs(9), posted: false, metadata: {}, created_at: hrs(9), updated_at: hrs(9) },
  { id: "chg-06", workspace_id: W, encounter_id: "enc-01", patient_id: "pt-01", invoice_id: null, cpt_code: "84484", description_en: "Troponin T assay", description_ar: "فحص تروبونين T", category: "lab", quantity: 3, unit_price: 180, total: 540, contracted_price: 480, discount_amount: 0, department_id: "dept-08", department_name: "Laboratory", source_type: "lab_order", source_id: "lab-01", charged_at: hrs(10), posted: false, metadata: {}, created_at: hrs(10), updated_at: hrs(1) },
  { id: "chg-07", workspace_id: W, encounter_id: "enc-01", patient_id: "pt-01", invoice_id: null, cpt_code: "71046", description_en: "Chest X-ray, two views", description_ar: "أشعة صدر بمنظورين", category: "imaging", quantity: 1, unit_price: 320, total: 320, contracted_price: 290, discount_amount: 0, department_id: "dept-09", department_name: "Radiology", source_type: "imaging_order", source_id: "img-01", charged_at: hrs(10), posted: false, metadata: {}, created_at: hrs(10), updated_at: hrs(10) },
  { id: "chg-08", workspace_id: W, encounter_id: "enc-01", patient_id: "pt-01", invoice_id: null, cpt_code: null, description_en: "Coronary care bed day", description_ar: "يوم إقامة في العناية القلبية", category: "bed", quantity: 1, unit_price: 3200, total: 3200, contracted_price: 2900, discount_amount: 0, department_id: "dept-02", department_name: "Cardiology", source_type: "encounter", source_id: "enc-01", charged_at: hrs(1), posted: false, metadata: {}, created_at: hrs(1), updated_at: hrs(1) },
  { id: "chg-09", workspace_id: W, encounter_id: "enc-02", patient_id: "pt-02", invoice_id: "inv-h02", cpt_code: "47562", description_en: "Laparoscopic cholecystectomy", description_ar: "استئصال المرارة بالمنظار", category: "theatre", quantity: 1, unit_price: 18500, total: 18500, contracted_price: 16200, discount_amount: 0, department_id: "dept-11", department_name: "Operating Theatres", source_type: "ot_case", source_id: "ot-01", charged_at: hrs(26), posted: true, metadata: {}, created_at: hrs(26), updated_at: hrs(26) },
  { id: "chg-10", workspace_id: W, encounter_id: "enc-09", patient_id: "pt-09", invoice_id: null, cpt_code: "96413", description_en: "Chemotherapy administration, first hour", description_ar: "إعطاء العلاج الكيميائي، الساعة الأولى", category: "procedure", quantity: 1, unit_price: 900, total: 900, contracted_price: 900, discount_amount: 0, department_id: "dept-12", department_name: "Oncology Day Unit", source_type: "clinical_order", source_id: "ord-27", charged_at: hrs(6), posted: false, metadata: {}, created_at: hrs(6), updated_at: hrs(6) },
  { id: "chg-11", workspace_id: W, encounter_id: "enc-09", patient_id: "pt-09", invoice_id: null, cpt_code: "J9263", description_en: "Oxaliplatin 150 mg", description_ar: "أوكزاليبلاتين ١٥٠ ملغ", category: "medication", quantity: 1, unit_price: 1860, total: 1860, contracted_price: 1860, discount_amount: 0, department_id: "dept-10", department_name: "Pharmacy", source_type: "dispense", source_id: "disp-06", charged_at: hrs(6.5), posted: false, metadata: {}, created_at: hrs(6.5), updated_at: hrs(6.5) },
  { id: "chg-12", workspace_id: W, encounter_id: "enc-07", patient_id: "pt-07", invoice_id: "inv-h03", cpt_code: "66984", description_en: "Cataract extraction with IOL, right", description_ar: "استخراج المياه البيضاء مع عدسة، اليمنى", category: "theatre", quantity: 1, unit_price: 11200, total: 11200, contracted_price: 9800, discount_amount: 0, department_id: "dept-11", department_name: "Operating Theatres", source_type: "ot_case", source_id: "ot-04", charged_at: hrs(30), posted: true, metadata: {}, created_at: hrs(30), updated_at: hrs(30) },
];

export const DEMO_CLAIMS: T<"claims">[] = [
  { id: "clm-01", workspace_id: W, claim_number: "CLM-2026-71120", encounter_id: "enc-14", invoice_id: "inv-h01", patient_id: "pt-14", patient_name: "Saud Al-Amri", payer_id: "pay-03", payer_name: "MedGulf", policy_number: "MG-2288001", claim_type: "institutional", diagnosis_codes: ["DB10"], procedure_codes: ["44970", "74177"], claimed_amount: 20556, approved_amount: null, paid_amount: null, patient_responsibility: null, currency: "SAR", status: "submitted", submitted_at: hrs(24), adjudicated_at: null, paid_at: null, denial_code: null, denial_reason_en: null, denial_reason_ar: null, appeal_count: 0, ar_days: 1, submitted_by: "RCM — Waleed Al-Sudairi", metadata: {}, created_at: hrs(26), updated_at: hrs(24) },
  { id: "clm-02", workspace_id: W, claim_number: "CLM-2026-70884", encounter_id: "enc-02", invoice_id: "inv-h02", patient_id: "pt-02", patient_name: "Maryam Al-Ghamdi", payer_id: "pay-02", payer_name: "Tawuniya", policy_number: "TAW-8812004", claim_type: "institutional", diagnosis_codes: ["DC11.0"], procedure_codes: ["47562"], claimed_amount: 18500, approved_amount: 16200, paid_amount: 16200, patient_responsibility: 2300, currency: "SAR", status: "paid", submitted_at: ts(5), adjudicated_at: ts(2), paid_at: ts(1), denial_code: null, denial_reason_en: null, denial_reason_ar: null, appeal_count: 0, ar_days: 4, submitted_by: "RCM — Waleed Al-Sudairi", metadata: { contractual_adjustment: 2300 }, created_at: ts(5), updated_at: ts(1) },
  { id: "clm-03", workspace_id: W, claim_number: "CLM-2026-70551", encounter_id: "enc-07", invoice_id: "inv-h03", patient_id: "pt-07", patient_name: "Sara Al-Mutairi", payer_id: "pay-03", payer_name: "MedGulf", policy_number: "MG-2291884", claim_type: "institutional", diagnosis_codes: ["9B10.2"], procedure_codes: ["66984"], claimed_amount: 11200, approved_amount: 0, paid_amount: 0, patient_responsibility: 11200, currency: "SAR", status: "denied", submitted_at: ts(2), adjudicated_at: hrs(20), paid_at: null, denial_code: "CO-27", denial_reason_en: "Expenses incurred after coverage terminated. Policy lapsed five days before the date of service.", denial_reason_ar: "نفقات بعد انتهاء التغطية. انتهت الوثيقة قبل خمسة أيام من تاريخ الخدمة.", appeal_count: 0, ar_days: 2, submitted_by: "RCM — Waleed Al-Sudairi", metadata: { actionable: true, root_cause: "Eligibility not re-verified at booking" }, created_at: ts(2), updated_at: hrs(20) },
  { id: "clm-04", workspace_id: W, claim_number: "CLM-2026-69902", encounter_id: "enc-09", invoice_id: null, patient_id: "pt-09", patient_name: "Hessa Al-Subaie", payer_id: "pay-01", payer_name: "Bupa Arabia", policy_number: "BUP-4402277", claim_type: "pre_authorisation", diagnosis_codes: ["2B90.0"], procedure_codes: ["96413", "J9263"], claimed_amount: 2760, approved_amount: 2760, paid_amount: null, patient_responsibility: 0, currency: "SAR", status: "approved", submitted_at: ts(16), adjudicated_at: ts(14), paid_at: null, denial_code: null, denial_reason_en: null, denial_reason_ar: null, appeal_count: 0, ar_days: 14, submitted_by: "RCM — Noura Al-Mansouri", metadata: { preauth_reference: "PA-2026-2201", cycles_approved: 12 }, created_at: ts(16), updated_at: ts(14) },
  { id: "clm-05", workspace_id: W, claim_number: "CLM-2026-68440", encounter_id: "enc-13", invoice_id: null, patient_id: "pt-13", patient_name: "Reem Al-Faisal", payer_id: "pay-05", payer_name: "Al Rajhi Takaful", policy_number: "ART-5591044", claim_type: "professional", diagnosis_codes: ["5A00"], procedure_codes: ["99213", "84443"], claimed_amount: 780, approved_amount: 520, paid_amount: 520, patient_responsibility: 260, currency: "SAR", status: "partially_paid", submitted_at: ts(30), adjudicated_at: ts(24), paid_at: ts(20), denial_code: "PR-45", denial_reason_en: "Charge exceeds the fee schedule allowance for this service.", denial_reason_ar: "الرسوم تتجاوز جدول الأتعاب المعتمد لهذه الخدمة.", appeal_count: 1, ar_days: 10, submitted_by: "RCM — Noura Al-Mansouri", metadata: { appeal_status: "under review" }, created_at: ts(30), updated_at: ts(20) },
  { id: "clm-06", workspace_id: W, claim_number: "CLM-2026-71205", encounter_id: "enc-01", invoice_id: null, patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", payer_id: "pay-01", payer_name: "Bupa Arabia", policy_number: "BUP-4471209", claim_type: "pre_authorisation", diagnosis_codes: ["BA41.0"], procedure_codes: ["93458"], claimed_amount: 26000, approved_amount: null, paid_amount: null, patient_responsibility: null, currency: "SAR", status: "in_review", submitted_at: hrs(2), adjudicated_at: null, paid_at: null, denial_code: null, denial_reason_en: null, denial_reason_ar: null, appeal_count: 0, ar_days: 0, submitted_by: "RCM — Waleed Al-Sudairi", metadata: { urgency: "Procedure booked in 14 hours — chase if not adjudicated in 6" }, created_at: hrs(2), updated_at: hrs(2) },
  { id: "clm-07", workspace_id: W, claim_number: "CLM-2026-67120", encounter_id: "enc-06", invoice_id: null, patient_id: "pt-06", patient_name: "Abdullah Al-Shehri", payer_id: "pay-04", payer_name: "Ministry of Health", policy_number: "MOH-1011223344", claim_type: "institutional", diagnosis_codes: ["1G41", "GB60.2"], procedure_codes: ["99291"], claimed_amount: 48200, approved_amount: null, paid_amount: null, patient_responsibility: 0, currency: "SAR", status: "draft", submitted_at: null, adjudicated_at: null, paid_at: null, denial_code: null, denial_reason_en: null, denial_reason_ar: null, appeal_count: 0, ar_days: null, submitted_by: null, metadata: { note: "Held until discharge — ICU stay ongoing" }, created_at: hrs(48), updated_at: hrs(4) },
  { id: "clm-08", workspace_id: W, claim_number: "CLM-2026-66880", encounter_id: "enc-08", invoice_id: null, patient_id: "pt-08", patient_name: "Ibrahim Al-Zahrani", payer_id: "pay-05", payer_name: "Al Rajhi Takaful", policy_number: "ART-5580912", claim_type: "pre_authorisation", diagnosis_codes: ["NC92.2"], procedure_codes: ["27759"], claimed_amount: 32000, approved_amount: 32000, paid_amount: null, patient_responsibility: 0, currency: "SAR", status: "approved", submitted_at: hrs(18), adjudicated_at: hrs(9), paid_at: null, denial_code: null, denial_reason_en: null, denial_reason_ar: null, appeal_count: 0, ar_days: 0, submitted_by: "RCM — Waleed Al-Sudairi", metadata: { preauth_reference: "PA-2026-3410", third_party_recovery: true }, created_at: hrs(18), updated_at: hrs(9) },
  { id: "clm-09", workspace_id: W, claim_number: "CLM-2026-65440", encounter_id: "enc-03", invoice_id: null, patient_id: "pt-03", patient_name: "Fatima Al-Harbi", payer_id: "pay-03", payer_name: "MedGulf", policy_number: "MG-2290117", claim_type: "professional", diagnosis_codes: ["5A11", "GB61.3"], procedure_codes: ["99214", "80069"], claimed_amount: 1240, approved_amount: null, paid_amount: null, patient_responsibility: null, currency: "SAR", status: "ready", submitted_at: null, adjudicated_at: null, paid_at: null, denial_code: null, denial_reason_en: null, denial_reason_ar: null, appeal_count: 0, ar_days: null, submitted_by: null, metadata: { coding_verified: true }, created_at: hrs(29), updated_at: hrs(28) },
  { id: "clm-10", workspace_id: W, claim_number: "CLM-2026-64100", encounter_id: "enc-05", invoice_id: null, patient_id: "pt-05", patient_name: "Yousef Al-Dosari", payer_id: "pay-02", payer_name: "Tawuniya", policy_number: "TAW-8830115", claim_type: "institutional", diagnosis_codes: ["CA23.0"], procedure_codes: ["99218"], claimed_amount: 4600, approved_amount: null, paid_amount: null, patient_responsibility: null, currency: "SAR", status: "acknowledged", submitted_at: hrs(3), adjudicated_at: null, paid_at: null, denial_code: null, denial_reason_en: null, denial_reason_ar: null, appeal_count: 0, ar_days: 0, submitted_by: "RCM — Noura Al-Mansouri", metadata: {}, created_at: hrs(4), updated_at: hrs(3) },
];

// ─── Biomedical engineering ───────────────────────────────

export const DEMO_BIOMED_ASSETS: T<"biomed_assets">[] = [
  { id: "asset-01", workspace_id: W, asset_tag: "BIO-VENT-0012", name_en: "ICU ventilator", name_ar: "جهاز تنفس صناعي للعناية", category: "ventilator", manufacturer: "Dräger", model: "Evita V800", serial_number: "DRG-88120441", ward_id: "wd-03", location: "ICU bed 2", department_id: "dept-04", purchase_date: d(900), purchase_cost: 185000, warranty_expiry: d(-190), install_date: d(880), risk_class: "high", pm_frequency_days: 90, last_pm_at: ts(62), next_pm_due: d(-28), last_calibration_at: ts(62), calibration_due: d(-28), status: "in_service", downtime_hours_ytd: 6, assigned_technician: "Eng. Mishal Al-Ruwaili", metadata: { in_use_by: "pt-06" }, created_at: ts(900), updated_at: hrs(1) },
  { id: "asset-02", workspace_id: W, asset_tag: "BIO-DEFIB-0004", name_en: "Defibrillator, biphasic", name_ar: "جهاز صدمات كهربائية ثنائي الطور", category: "defibrillator", manufacturer: "Philips", model: "HeartStart XL+", serial_number: "PHL-77201883", ward_id: "wd-01", location: "CCU resus trolley", department_id: "dept-02", purchase_date: d(1400), purchase_cost: 42000, warranty_expiry: d(280), install_date: d(1390), risk_class: "high", pm_frequency_days: 180, last_pm_at: ts(200), next_pm_due: d(20), last_calibration_at: ts(200), calibration_due: d(20), status: "in_service", downtime_hours_ytd: 0, assigned_technician: "Eng. Mishal Al-Ruwaili", metadata: { daily_check: "passed" }, created_at: ts(1400), updated_at: hrs(8) },
  { id: "asset-03", workspace_id: W, asset_tag: "BIO-ANAES-0002", name_en: "Anaesthesia machine", name_ar: "جهاز تخدير", category: "anaesthesia", manufacturer: "GE Healthcare", model: "Aisys CS²", serial_number: "GE-55120990", ward_id: null, location: "Theatre 1", department_id: "dept-11", purchase_date: d(1100), purchase_cost: 320000, warranty_expiry: d(-40), install_date: d(1080), risk_class: "high", pm_frequency_days: 90, last_pm_at: ts(95), next_pm_due: d(-5), last_calibration_at: ts(95), calibration_due: d(-5), status: "under_maintenance", downtime_hours_ytd: 34, assigned_technician: "Eng. Mishal Al-Ruwaili", metadata: { cancelled_case: "ot-05", note: "Failed pre-use leak test" }, created_at: ts(1100), updated_at: hrs(30) },
  { id: "asset-04", workspace_id: W, asset_tag: "BIO-PUMP-0088", name_en: "Volumetric infusion pump", name_ar: "مضخة تسريب حجمية", category: "infusion_pump", manufacturer: "B. Braun", model: "Infusomat Space", serial_number: "BB-33091177", ward_id: "wd-03", location: "ICU bed 2", department_id: "dept-04", purchase_date: d(600), purchase_cost: 9800, warranty_expiry: d(130), install_date: d(590), risk_class: "medium", pm_frequency_days: 180, last_pm_at: ts(90), next_pm_due: d(90), last_calibration_at: ts(90), calibration_due: d(90), status: "in_service", downtime_hours_ytd: 2, assigned_technician: "Eng. Tariq Al-Sulami", metadata: { drug_library_version: "2026.2" }, created_at: ts(600), updated_at: hrs(1) },
  { id: "asset-05", workspace_id: W, asset_tag: "BIO-CT-0001", name_en: "CT scanner, 128-slice", name_ar: "جهاز أشعة مقطعية ١٢٨ شريحة", category: "imaging", manufacturer: "Siemens Healthineers", model: "SOMATOM go.Top", serial_number: "SIE-11200455", ward_id: null, location: "Radiology, CT-1", department_id: "dept-09", purchase_date: d(1600), purchase_cost: 4200000, warranty_expiry: d(400), install_date: d(1540), risk_class: "high", pm_frequency_days: 90, last_pm_at: ts(30), next_pm_due: d(60), last_calibration_at: ts(30), calibration_due: d(60), status: "in_service", downtime_hours_ytd: 18, assigned_technician: "Vendor — Siemens Service", metadata: { tube_life_percent: 62 }, created_at: ts(1600), updated_at: ts(30) },
  { id: "asset-06", workspace_id: W, asset_tag: "BIO-MON-0141", name_en: "Patient monitor, multiparameter", name_ar: "جهاز مراقبة متعدد المؤشرات", category: "monitor", manufacturer: "Philips", model: "IntelliVue MX750", serial_number: "PHL-88104412", ward_id: "wd-01", location: "CCU bed 1", department_id: "dept-02", purchase_date: d(500), purchase_cost: 38000, warranty_expiry: d(230), install_date: d(490), risk_class: "medium", pm_frequency_days: 365, last_pm_at: ts(180), next_pm_due: d(185), last_calibration_at: ts(180), calibration_due: d(185), status: "in_service", downtime_hours_ytd: 0, assigned_technician: "Eng. Tariq Al-Sulami", metadata: {}, created_at: ts(500), updated_at: hrs(9) },
  { id: "asset-07", workspace_id: W, asset_tag: "BIO-DIAL-0003", name_en: "Haemodialysis machine", name_ar: "جهاز غسيل كلوي", category: "dialysis", manufacturer: "Fresenius", model: "5008S CorDiax", serial_number: "FRS-66201188", ward_id: "wd-03", location: "ICU store", department_id: "dept-04", purchase_date: d(800), purchase_cost: 128000, warranty_expiry: d(-60), install_date: d(780), risk_class: "high", pm_frequency_days: 90, last_pm_at: ts(120), next_pm_due: d(-30), last_calibration_at: ts(120), calibration_due: d(-30), status: "awaiting_parts", downtime_hours_ytd: 96, assigned_technician: "Eng. Mishal Al-Ruwaili", metadata: { part_on_order: "Conductivity cell, ETA 6 days" }, created_at: ts(800), updated_at: ts(4) },
  { id: "asset-08", workspace_id: W, asset_tag: "BIO-VENT-0018", name_en: "Transport ventilator", name_ar: "جهاز تنفس للنقل", category: "ventilator", manufacturer: "Hamilton Medical", model: "HAMILTON-T1", serial_number: "HAM-99120033", ward_id: null, location: "ED resus", department_id: "dept-01", purchase_date: d(400), purchase_cost: 76000, warranty_expiry: d(330), install_date: d(390), risk_class: "high", pm_frequency_days: 90, last_pm_at: ts(20), next_pm_due: d(70), last_calibration_at: ts(20), calibration_due: d(70), status: "in_service", downtime_hours_ytd: 4, assigned_technician: "Eng. Tariq Al-Sulami", metadata: {}, created_at: ts(400), updated_at: ts(20) },
  { id: "asset-09", workspace_id: W, asset_tag: "BIO-STER-0006", name_en: "Steam steriliser", name_ar: "معقم بالبخار", category: "sterilisation", manufacturer: "Getinge", model: "GSS67H", serial_number: "GET-44012299", ward_id: null, location: "CSSD", department_id: "dept-11", purchase_date: d(2000), purchase_cost: 290000, warranty_expiry: d(-500), install_date: d(1960), risk_class: "high", pm_frequency_days: 90, last_pm_at: ts(45), next_pm_due: d(45), last_calibration_at: ts(45), calibration_due: d(45), status: "in_service", downtime_hours_ytd: 22, assigned_technician: "Eng. Mishal Al-Ruwaili", metadata: { bowie_dick_test: "passed today" }, created_at: ts(2000), updated_at: hrs(10) },
  { id: "asset-10", workspace_id: W, asset_tag: "BIO-MON-0098", name_en: "Patient monitor, transport", name_ar: "جهاز مراقبة للنقل", category: "monitor", manufacturer: "Mindray", model: "uMEC12", serial_number: "MDR-22110044", ward_id: "wd-06", location: "Isolation bay 3", department_id: "dept-04", purchase_date: d(1200), purchase_cost: 14000, warranty_expiry: d(-300), install_date: d(1180), risk_class: "medium", pm_frequency_days: 365, last_pm_at: ts(400), next_pm_due: d(-35), last_calibration_at: ts(400), calibration_due: d(-35), status: "out_of_service", downtime_hours_ytd: 210, assigned_technician: "Eng. Tariq Al-Sulami", metadata: { fault: "Intermittent SpO2 reading — withdrawn from service" }, created_at: ts(1200), updated_at: ts(9) },
];

export const DEMO_MAINTENANCE_ORDERS: T<"maintenance_orders">[] = [
  { id: "bwo-01", workspace_id: W, work_order_number: "BIOM-WO-0229", asset_id: "asset-03", asset_tag: "BIO-ANAES-0002", asset_name: "Anaesthesia machine", maintenance_type: "corrective", priority: "critical", status: "in_progress", reported_by: "Dr. Yasser Al-Habib", reported_at: hrs(31), fault_description_en: "Failed the automated pre-use leak test twice. Circuit compliance out of range.", fault_description_ar: "فشل اختبار التسرب الآلي قبل الاستخدام مرتين مع خروج مطاوعة الدائرة عن النطاق.", assigned_to: "Eng. Mishal Al-Ruwaili", scheduled_at: hrs(30), started_at: hrs(29), completed_at: null, findings_en: "Perished inspiratory limb seal. Replacement seal kit fitted; awaiting full calibration and safety test before release.", action_taken_en: "Seal kit replaced.", parts_used: [{ part: "Inspiratory seal kit", code: "GE-8004521", qty: 1 }], labour_hours: 3.5, cost: 1850, downtime_minutes: 1860, passed_safety_test: null, next_due: null, metadata: { caused_cancellation: "ot-05" }, created_at: hrs(31), updated_at: hrs(4) },
  { id: "bwo-02", workspace_id: W, work_order_number: "BIOM-WO-0231", asset_id: "asset-10", asset_tag: "BIO-MON-0098", asset_name: "Patient monitor, transport", maintenance_type: "corrective", priority: "high", status: "awaiting_parts", reported_by: "Nurse Aisha Al-Dakhil", reported_at: ts(9), fault_description_en: "SpO2 channel drops out intermittently under movement. Two clinical incident reports filed.", fault_description_ar: "انقطاع متقطع في قناة تشبع الأكسجين مع الحركة مع تقريري حادثة سريرية.", assigned_to: "Eng. Tariq Al-Sulami", scheduled_at: ts(8), started_at: ts(8), completed_at: null, findings_en: "SpO2 board fault confirmed on bench test. Board on order from Mindray.", action_taken_en: "Withdrawn from clinical service and labelled.", parts_used: [], labour_hours: 2, cost: null, downtime_minutes: 12600, passed_safety_test: null, next_due: null, metadata: { part_eta_days: 6, also_blocking: "Isolation bay 3" }, created_at: ts(9), updated_at: ts(2) },
  { id: "bwo-03", workspace_id: W, work_order_number: "BIOM-WO-0218", asset_id: "asset-01", asset_tag: "BIO-VENT-0012", asset_name: "ICU ventilator", maintenance_type: "preventive", priority: "high", status: "open", reported_by: "System — PM scheduler", reported_at: ts(28), fault_description_en: null, fault_description_ar: null, assigned_to: "Eng. Mishal Al-Ruwaili", scheduled_at: ts(-2), started_at: null, completed_at: null, findings_en: null, action_taken_en: null, parts_used: [], labour_hours: null, cost: null, downtime_minutes: null, passed_safety_test: null, next_due: d(-28), metadata: { overdue_days: 28, blocker: "In continuous clinical use — pt-06 ventilated" }, created_at: ts(28), updated_at: ts(1) },
  { id: "bwo-04", workspace_id: W, work_order_number: "BIOM-WO-0225", asset_id: "asset-07", asset_tag: "BIO-DIAL-0003", asset_name: "Haemodialysis machine", maintenance_type: "corrective", priority: "high", status: "awaiting_parts", reported_by: "Nurse Aisha Al-Dakhil", reported_at: ts(4), fault_description_en: "Conductivity alarm on every treatment start. Machine will not complete self-test.", fault_description_ar: "إنذار الموصلية عند بدء كل جلسة مع فشل الاختبار الذاتي.", assigned_to: "Eng. Mishal Al-Ruwaili", scheduled_at: ts(4), started_at: ts(4), completed_at: null, findings_en: "Conductivity cell drifted beyond calibration range.", action_taken_en: "Cell ordered from Fresenius.", parts_used: [], labour_hours: 1.5, cost: null, downtime_minutes: 5760, passed_safety_test: null, next_due: null, metadata: { part_eta_days: 6 }, created_at: ts(4), updated_at: ts(1) },
  { id: "bwo-05", workspace_id: W, work_order_number: "BIOM-WO-0210", asset_id: "asset-02", asset_tag: "BIO-DEFIB-0004", asset_name: "Defibrillator, biphasic", maintenance_type: "safety_test", priority: "medium", status: "verified", reported_by: "System — PM scheduler", reported_at: ts(202), fault_description_en: null, fault_description_ar: null, assigned_to: "Eng. Tariq Al-Sulami", scheduled_at: ts(200), started_at: ts(200), completed_at: ts(200), findings_en: "Energy delivery within 5% at all tested settings. Battery capacity 96%. Pads in date.", action_taken_en: "Electrical safety test passed. Returned to service.", parts_used: [], labour_hours: 1, cost: 320, downtime_minutes: 60, passed_safety_test: true, next_due: d(20), metadata: {}, created_at: ts(202), updated_at: ts(200) },
  { id: "bwo-06", workspace_id: W, work_order_number: "BIOM-WO-0233", asset_id: "asset-05", asset_tag: "BIO-CT-0001", asset_name: "CT scanner, 128-slice", maintenance_type: "calibration", priority: "medium", status: "assigned", reported_by: "Tech. Sami Al-Ghamdi", reported_at: ts(2), fault_description_en: "Routine quarterly water-phantom calibration and dose audit due.", fault_description_ar: "معايرة ربع سنوية روتينية بالفانتوم المائي مع تدقيق الجرعة.", assigned_to: "Vendor — Siemens Service", scheduled_at: ts(-3), started_at: null, completed_at: null, findings_en: null, action_taken_en: null, parts_used: [], labour_hours: null, cost: null, downtime_minutes: null, passed_safety_test: null, next_due: d(60), metadata: { vendor_visit: true }, created_at: ts(2), updated_at: ts(1) },
];

// ─── Dietary ──────────────────────────────────────────────

export const DEMO_DIET_ORDERS: T<"diet_orders">[] = [
  { id: "diet-01", workspace_id: W, encounter_id: "enc-01", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", ward_id: "wd-01", ward_name: "Coronary Care Unit", bed_label: "CCU-01", diet_type: "cardiac", texture: "regular", fluid_consistency: null, calories_target: 1800, protein_target_g: 75, fluid_restriction_ml: 1500, allergens_to_avoid: ["Penicillin"], cultural_preference: "halal", special_instructions_en: "Low salt. No added salt at the table.", special_instructions_ar: "قليل الملح دون إضافة ملح على المائدة.", ordered_by: "Dr. Hala Al-Rasheed", dietitian_reviewed: true, start_at: hrs(9), end_at: null, status: "active", metadata: {}, created_at: hrs(9), updated_at: hrs(9) },
  { id: "diet-02", workspace_id: W, encounter_id: "enc-02", patient_id: "pt-02", patient_name: "Maryam Al-Ghamdi", ward_id: "wd-02", ward_name: "Surgical Ward A", bed_label: "SA-01", diet_type: "soft", texture: "regular", fluid_consistency: null, calories_target: 1600, protein_target_g: 65, fluid_restriction_ml: null, allergens_to_avoid: [], cultural_preference: "halal", special_instructions_en: "Light diet post-cholecystectomy, low fat. Advance as tolerated.", special_instructions_ar: "غذاء خفيف قليل الدهون بعد استئصال المرارة مع التدرج حسب التحمل.", ordered_by: "Dr. Faisal Al-Harthy", dietitian_reviewed: false, start_at: hrs(24), end_at: null, status: "active", metadata: {}, created_at: hrs(24), updated_at: hrs(24) },
  { id: "diet-03", workspace_id: W, encounter_id: "enc-06", patient_id: "pt-06", patient_name: "Abdullah Al-Shehri", ward_id: "wd-03", ward_name: "Intensive Care Unit", bed_label: "ICU-02", diet_type: "enteral", texture: null, fluid_consistency: null, calories_target: 1560, protein_target_g: 94, fluid_restriction_ml: 1200, allergens_to_avoid: [], cultural_preference: "halal", special_instructions_en: "NG feed, Nutrison Protein Plus at 65 mL/h. Four-hourly aspirates.", special_instructions_ar: "تغذية أنبوبية أنفية معدية بمعدل ٦٥ مل/ساعة مع سحب كل أربع ساعات.", ordered_by: "Dr. Omar Bin Salem", dietitian_reviewed: true, start_at: hrs(70), end_at: null, status: "active", metadata: { route: "nasogastric" }, created_at: hrs(70), updated_at: hrs(6) },
  { id: "diet-04", workspace_id: W, encounter_id: "enc-08", patient_id: "pt-08", patient_name: "Ibrahim Al-Zahrani", ward_id: "wd-02", ward_name: "Surgical Ward A", bed_label: "SA-06", diet_type: "npo", texture: null, fluid_consistency: null, calories_target: null, protein_target_g: null, fluid_restriction_ml: null, allergens_to_avoid: [], cultural_preference: "halal", special_instructions_en: "Nil by mouth for theatre. Clear fluids until two hours pre-op.", special_instructions_ar: "صائم للعملية مع سوائل صافية حتى ساعتين قبلها.", ordered_by: "Dr. Bandar Al-Otaibi", dietitian_reviewed: false, start_at: hrs(18), end_at: null, status: "active", metadata: { theatre_case: "ot-02" }, created_at: hrs(18), updated_at: hrs(18) },
  { id: "diet-05", workspace_id: W, encounter_id: "enc-05", patient_id: "pt-05", patient_name: "Yousef Al-Dosari", ward_id: "wd-05", ward_name: "Paediatric Ward", bed_label: "PD-02", diet_type: "paediatric", texture: "regular", fluid_consistency: null, calories_target: 1400, protein_target_g: 30, fluid_restriction_ml: null, allergens_to_avoid: ["Peanut", "Tree nuts"], cultural_preference: "halal", special_instructions_en: "STRICT nut-free tray. Anaphylaxis risk — separate preparation area.", special_instructions_ar: "صينية خالية من المكسرات تماماً. خطر تأق — منطقة تحضير منفصلة.", ordered_by: "Dr. Rana Al-Suwailem", dietitian_reviewed: true, start_at: hrs(5), end_at: null, status: "active", metadata: { allergy_alert: true, severity: "fatal" }, created_at: hrs(5), updated_at: hrs(5) },
  { id: "diet-06", workspace_id: W, encounter_id: "enc-04", patient_id: "pt-04", patient_name: "Noura Al-Qahtani", ward_id: "wd-04", ward_name: "Maternity Ward", bed_label: "MAT-03", diet_type: "npo", texture: null, fluid_consistency: null, calories_target: null, protein_target_g: null, fluid_restriction_ml: null, allergens_to_avoid: [], cultural_preference: "halal", special_instructions_en: "Nil by mouth from 06:00 for elective caesarean section.", special_instructions_ar: "صائمة من الساعة السادسة صباحاً للعملية القيصرية المخططة.", ordered_by: "Dr. Amal Al-Shamrani", dietitian_reviewed: false, start_at: hrs(4), end_at: null, status: "active", metadata: {}, created_at: hrs(4), updated_at: hrs(4) },
];

export const DEMO_MEAL_SERVICES: T<"meal_services">[] = [
  { id: "meal-01", workspace_id: W, diet_order_id: "diet-01", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", ward_name: "Coronary Care Unit", bed_label: "CCU-01", service_date: today(), meal: "breakfast", menu_en: "Oat porridge, low-fat laban, date, herbal tea", menu_ar: "شوفان، لبن قليل الدسم، تمرة، شاي أعشاب", status: "delivered", prepared_at: hrs(5), delivered_at: hrs(4.5), delivered_by: "Catering — Fahad Al-Otaibi", intake_percent: 80, notes: null, metadata: {}, created_at: hrs(9), updated_at: hrs(4.5) },
  { id: "meal-02", workspace_id: W, diet_order_id: "diet-01", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", ward_name: "Coronary Care Unit", bed_label: "CCU-01", service_date: today(), meal: "lunch", menu_en: "Grilled chicken, steamed rice, mixed vegetables, fruit", menu_ar: "دجاج مشوي، أرز مطهو بالبخار، خضار مشكلة، فاكهة", status: "prepared", prepared_at: mins(30), delivered_at: null, delivered_by: null, intake_percent: null, notes: null, metadata: {}, created_at: hrs(9), updated_at: mins(30) },
  { id: "meal-03", workspace_id: W, diet_order_id: "diet-02", patient_id: "pt-02", patient_name: "Maryam Al-Ghamdi", ward_name: "Surgical Ward A", bed_label: "SA-01", service_date: today(), meal: "breakfast", menu_en: "Toast, low-fat cheese, apple juice", menu_ar: "توست، جبن قليل الدسم، عصير تفاح", status: "delivered", prepared_at: hrs(5), delivered_at: hrs(4.6), delivered_by: "Catering — Fahad Al-Otaibi", intake_percent: 100, notes: "Tolerated well", metadata: {}, created_at: hrs(24), updated_at: hrs(4.6) },
  { id: "meal-04", workspace_id: W, diet_order_id: "diet-05", patient_id: "pt-05", patient_name: "Yousef Al-Dosari", ward_name: "Paediatric Ward", bed_label: "PD-02", service_date: today(), meal: "lunch", menu_en: "Nut-free: chicken pasta, cucumber sticks, yoghurt", menu_ar: "خالٍ من المكسرات: باستا بالدجاج، شرائح خيار، زبادي", status: "prepared", prepared_at: mins(35), delivered_at: null, delivered_by: null, intake_percent: null, notes: "Allergen-checked by two staff before dispatch", metadata: { allergen_double_check: true }, created_at: hrs(5), updated_at: mins(35) },
  { id: "meal-05", workspace_id: W, diet_order_id: "diet-02", patient_id: "pt-02", patient_name: "Maryam Al-Ghamdi", ward_name: "Surgical Ward A", bed_label: "SA-01", service_date: today(), meal: "lunch", menu_en: "Low-fat: baked fish, boiled potato, green beans", menu_ar: "قليل الدسم: سمك بالفرن، بطاطس مسلوقة، فاصولياء خضراء", status: "planned", prepared_at: null, delivered_at: null, delivered_by: null, intake_percent: null, notes: null, metadata: {}, created_at: hrs(24), updated_at: hrs(24) },
  { id: "meal-06", workspace_id: W, diet_order_id: "diet-01", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", ward_name: "Coronary Care Unit", bed_label: "CCU-01", service_date: d(1), meal: "dinner", menu_en: "Lentil soup, grilled vegetables, flatbread", menu_ar: "شوربة عدس، خضار مشوية، خبز", status: "delivered", prepared_at: hrs(20), delivered_at: hrs(19.5), delivered_by: "Catering — Mansour Al-Yami", intake_percent: 50, notes: "Poor appetite, chest pain at the time", metadata: {}, created_at: hrs(21), updated_at: hrs(19.5) },
  { id: "meal-07", workspace_id: W, diet_order_id: "diet-04", patient_id: "pt-08", patient_name: "Ibrahim Al-Zahrani", ward_name: "Surgical Ward A", bed_label: "SA-06", service_date: today(), meal: "breakfast", menu_en: "—", menu_ar: "—", status: "cancelled", prepared_at: null, delivered_at: null, delivered_by: null, intake_percent: null, notes: "Nil by mouth for theatre", metadata: { npo: true }, created_at: hrs(18), updated_at: hrs(18) },
  { id: "meal-08", workspace_id: W, diet_order_id: "diet-05", patient_id: "pt-05", patient_name: "Yousef Al-Dosari", ward_name: "Paediatric Ward", bed_label: "PD-02", service_date: today(), meal: "breakfast", menu_en: "Nut-free: cereal, milk, banana", menu_ar: "خالٍ من المكسرات: حبوب، حليب، موز", status: "delivered", prepared_at: hrs(5), delivered_at: hrs(4.4), delivered_by: "Catering — Fahad Al-Otaibi", intake_percent: 60, notes: null, metadata: { allergen_double_check: true }, created_at: hrs(5), updated_at: hrs(4.4) },
];

// ─── Housekeeping & linen ─────────────────────────────────

export const DEMO_HOUSEKEEPING_TASKS: T<"housekeeping_tasks">[] = [
  { id: "hk-01", workspace_id: W, task_number: "HK-2026-11201", ward_id: "wd-02", ward_name: "Surgical Ward A", bed_id: "bed-SA-04", location: "Bed SA-04", task_type: "discharge_clean", priority: "high", status: "completed", requested_at: hrs(26), requested_by: "Nurse Sara Bin Ali", assigned_to: "Housekeeper Ahmed Al-Rashidi", assigned_at: hrs(25.6), started_at: hrs(25.4), completed_at: hrs(24.7), verified_at: hrs(24.5), verified_by: "Nurse Sara Bin Ali", turnaround_minutes: 90, isolation_precaution: null, notes: "Standard discharge clean after appendicectomy patient", metadata: {}, created_at: hrs(26), updated_at: hrs(24.5) },
  { id: "hk-02", workspace_id: W, task_number: "HK-2026-11244", ward_id: "wd-01", ward_name: "Coronary Care Unit", bed_id: "bed-CCU-05", location: "Bed CCU-05", task_type: "discharge_clean", priority: "urgent", status: "in_progress", requested_at: hrs(3), requested_by: "Nurse Aisha Al-Dakhil", assigned_to: "Housekeeper Nasser Al-Qahtani", assigned_at: hrs(2.6), started_at: hrs(2.2), completed_at: null, verified_at: null, verified_by: null, turnaround_minutes: null, isolation_precaution: null, notes: "Bed needed for an ED admission — expedite", metadata: { waiting_admission: true }, created_at: hrs(3), updated_at: hrs(2.2) },
  { id: "hk-03", workspace_id: W, task_number: "HK-2026-11250", ward_id: "wd-06", ward_name: "Isolation Unit", bed_id: "bed-ISO-01", location: "Isolation bay 1", task_type: "terminal_clean", priority: "high", status: "pending", requested_at: hrs(1.5), requested_by: "Nurse Aisha Al-Dakhil", assigned_to: null, assigned_at: null, started_at: null, completed_at: null, verified_at: null, verified_by: null, turnaround_minutes: null, isolation_precaution: "Contact precautions — chlorine-based agent, 10 minute contact time", notes: "MRSA-positive patient transferred out", metadata: {}, created_at: hrs(1.5), updated_at: hrs(1.5) },
  { id: "hk-04", workspace_id: W, task_number: "HK-2026-11209", ward_id: "wd-03", ward_name: "Intensive Care Unit", bed_id: null, location: "ICU corridor", task_type: "spill", priority: "urgent", status: "completed", requested_at: hrs(9), requested_by: "Nurse Mona Al-Faraj", assigned_to: "Housekeeper Ahmed Al-Rashidi", assigned_at: hrs(8.9), started_at: hrs(8.85), completed_at: hrs(8.6), verified_at: hrs(8.6), verified_by: "Nurse Mona Al-Faraj", turnaround_minutes: 24, isolation_precaution: "Body fluid spill kit used", notes: null, metadata: {}, created_at: hrs(9), updated_at: hrs(8.6) },
  { id: "hk-05", workspace_id: W, task_number: "HK-2026-11255", ward_id: "wd-04", ward_name: "Maternity Ward", bed_id: "bed-MAT-05", location: "Bed MAT-05", task_type: "discharge_clean", priority: "normal", status: "assigned", requested_at: hrs(2), requested_by: "Midwife Reem Al-Saleh", assigned_to: "Housekeeper Mona Al-Shibli", assigned_at: hrs(1.2), started_at: null, completed_at: null, verified_at: null, verified_by: null, turnaround_minutes: null, isolation_precaution: null, notes: null, metadata: {}, created_at: hrs(2), updated_at: hrs(1.2) },
  { id: "hk-06", workspace_id: W, task_number: "HK-2026-11190", ward_id: "wd-05", ward_name: "Paediatric Ward", bed_id: null, location: "Paediatric playroom", task_type: "daily_clean", priority: "low", status: "completed", requested_at: hrs(12), requested_by: "System — daily schedule", assigned_to: "Housekeeper Mona Al-Shibli", assigned_at: hrs(11.5), started_at: hrs(11), completed_at: hrs(10.3), verified_at: hrs(10.2), verified_by: "Nurse Dana Al-Muhaisen", turnaround_minutes: 108, isolation_precaution: null, notes: "Toys sanitised", metadata: {}, created_at: hrs(12), updated_at: hrs(10.2) },
  { id: "hk-07", workspace_id: W, task_number: "HK-2026-11260", ward_id: "wd-02", ward_name: "Surgical Ward A", bed_id: "bed-SA-10", location: "Bed SA-10", task_type: "discharge_clean", priority: "normal", status: "pending", requested_at: mins(35), requested_by: "Nurse Sara Bin Ali", assigned_to: null, assigned_at: null, started_at: null, completed_at: null, verified_at: null, verified_by: null, turnaround_minutes: null, isolation_precaution: null, notes: null, metadata: {}, created_at: mins(35), updated_at: mins(35) },
];

export const DEMO_LINEN_CYCLES: T<"linen_cycles">[] = [
  { id: "lin-01", workspace_id: W, cycle_number: "LIN-2026-3301", ward_id: "wd-02", ward_name: "Surgical Ward A", cycle_date: today(), category: "bed_sheets", quantity_issued: 60, quantity_returned: 54, quantity_condemned: 2, status: "returned", issued_at: hrs(10), returned_at: hrs(2), handled_by: "Linen — Saeed Al-Ghamdi", metadata: {}, created_at: hrs(10), updated_at: hrs(2) },
  { id: "lin-02", workspace_id: W, cycle_number: "LIN-2026-3302", ward_id: "wd-03", ward_name: "Intensive Care Unit", cycle_date: today(), category: "gowns", quantity_issued: 80, quantity_returned: 61, quantity_condemned: 4, status: "shortfall", issued_at: hrs(10), returned_at: hrs(2), handled_by: "Linen — Saeed Al-Ghamdi", metadata: { shortfall: 15, note: "Isolation gown usage above forecast" }, created_at: hrs(10), updated_at: hrs(2) },
  { id: "lin-03", workspace_id: W, cycle_number: "LIN-2026-3303", ward_id: "wd-04", ward_name: "Maternity Ward", cycle_date: today(), category: "towels", quantity_issued: 45, quantity_returned: 45, quantity_condemned: 0, status: "returned", issued_at: hrs(10), returned_at: hrs(2), handled_by: "Linen — Saeed Al-Ghamdi", metadata: {}, created_at: hrs(10), updated_at: hrs(2) },
  { id: "lin-04", workspace_id: W, cycle_number: "LIN-2026-3304", ward_id: null, ward_name: "Operating Theatres", cycle_date: today(), category: "theatre_drapes", quantity_issued: 36, quantity_returned: 0, quantity_condemned: 0, status: "washing", issued_at: hrs(9), returned_at: null, handled_by: "Linen — Mohammed Al-Zahrani", metadata: { sterile_pack_cycle: true }, created_at: hrs(9), updated_at: hrs(4) },
  { id: "lin-05", workspace_id: W, cycle_number: "LIN-2026-3298", ward_id: "wd-01", ward_name: "Coronary Care Unit", cycle_date: d(1), category: "bed_sheets", quantity_issued: 32, quantity_returned: 30, quantity_condemned: 1, status: "returned", issued_at: hrs(34), returned_at: hrs(26), handled_by: "Linen — Saeed Al-Ghamdi", metadata: {}, created_at: hrs(34), updated_at: hrs(26) },
  { id: "lin-06", workspace_id: W, cycle_number: "LIN-2026-3305", ward_id: "wd-05", ward_name: "Paediatric Ward", cycle_date: today(), category: "blankets", quantity_issued: 24, quantity_returned: 0, quantity_condemned: 0, status: "issued", issued_at: hrs(3), returned_at: null, handled_by: "Linen — Mohammed Al-Zahrani", metadata: {}, created_at: hrs(3), updated_at: hrs(3) },
];

// ─── Patient portal & telehealth ──────────────────────────

export const DEMO_PORTAL_MESSAGES: T<"portal_messages">[] = [
  { id: "msg-01", workspace_id: W, patient_id: "pt-11", patient_name: "Layla Al-Anazi", direction: "inbound", category: "question", subject_en: "Cream is stinging on application", subject_ar: "الكريم يسبب حرقة عند الاستخدام", body_en: "I started the cream you prescribed two days ago. It stings for about ten minutes after I put it on. Is that expected, or should I stop?", body_ar: "بدأت استخدام الكريم الموصوف قبل يومين. يسبب حرقة لحوالي عشر دقائق بعد وضعه. هل هذا متوقع أم يجب أن أتوقف؟", provider_id: "prov-14", provider_name: "Dr. Lina Al-Yousef", status: "replied", sent_at: hrs(20), read_at: hrs(6), replied_at: hrs(5), parent_message_id: null, attachment_count: 1, metadata: {}, created_at: hrs(20), updated_at: hrs(5) },
  { id: "msg-02", workspace_id: W, patient_id: "pt-11", patient_name: "Layla Al-Anazi", direction: "outbound", category: "question", subject_en: "Re: Cream is stinging on application", subject_ar: "رد: الكريم يسبب حرقة عند الاستخدام", body_en: "Brief stinging on broken skin is common in the first few days and usually settles. Apply to dry skin rather than straight after washing, and use a plain moisturiser twenty minutes beforehand. If it burns rather than stings, or the redness spreads, stop and message me again.", body_ar: "الحرقة الخفيفة على الجلد المتشقق شائعة في الأيام الأولى وتزول عادة. ضعيه على جلد جاف لا مباشرة بعد الغسل، واستخدمي مرطباً عادياً قبله بعشرين دقيقة. إذا تحول إلى حرق شديد أو انتشر الاحمرار فتوقفي وراسليني.", provider_id: "prov-14", provider_name: "Dr. Lina Al-Yousef", status: "read", sent_at: hrs(5), read_at: hrs(4.5), replied_at: null, parent_message_id: "msg-01", attachment_count: 0, metadata: {}, created_at: hrs(5), updated_at: hrs(4.5) },
  { id: "msg-03", workspace_id: W, patient_id: "pt-14", patient_name: "Saud Al-Amri", direction: "outbound", category: "result_release", subject_en: "Your histology result is available", subject_ar: "نتيجة الفحص النسيجي متاحة", body_en: "The histology from your appendix has been reported as acute appendicitis with no unexpected findings. No further action is needed beyond your wound review appointment.", body_ar: "أظهر الفحص النسيجي للزائدة التهاباً حاداً دون أي نتائج غير متوقعة. لا يلزم إجراء إضافي سوى موعد مراجعة الجرح.", provider_id: "prov-02", provider_name: "Dr. Faisal Al-Harthy", status: "unread", sent_at: hrs(8), read_at: null, replied_at: null, parent_message_id: null, attachment_count: 1, metadata: {}, created_at: hrs(8), updated_at: hrs(8) },
  { id: "msg-04", workspace_id: W, patient_id: "pt-03", patient_name: "Fatima Al-Harbi", direction: "inbound", category: "prescription_refill", subject_en: "Refill request — new diabetes tablet", subject_ar: "طلب إعادة صرف — حبوب السكري الجديدة", body_en: "I collected the new tablet last month. Could you send the repeat to the pharmacy before I run out next week?", body_ar: "استلمت الحبوب الجديدة الشهر الماضي. هل يمكن إرسال إعادة الصرف للصيدلية قبل أن تنفد الأسبوع القادم؟", provider_id: "prov-01", provider_name: "Dr. Hala Al-Rasheed", status: "unread", sent_at: hrs(14), read_at: null, replied_at: null, parent_message_id: null, attachment_count: 0, metadata: {}, created_at: hrs(14), updated_at: hrs(14) },
  { id: "msg-05", workspace_id: W, patient_id: "pt-07", patient_name: "Sara Al-Mutairi", direction: "inbound", category: "billing", subject_en: "Why have I been billed the full amount?", subject_ar: "لماذا حُملت المبلغ كاملاً؟", body_en: "I had my cataract operation and expected insurance to cover it. I have received a bill for the whole amount. Please can someone explain?", body_ar: "أجريت عملية المياه البيضاء وتوقعت أن يغطيها التأمين، لكنني استلمت فاتورة بالمبلغ كاملاً. أرجو التوضيح.", provider_id: null, provider_name: null, status: "escalated", sent_at: hrs(16), read_at: hrs(12), replied_at: null, parent_message_id: null, attachment_count: 1, metadata: { escalated_to: "RCM — Waleed Al-Sudairi", related_claim: "clm-03" }, created_at: hrs(16), updated_at: hrs(12) },
  { id: "msg-06", workspace_id: W, patient_id: "pt-05", patient_name: "Yousef Al-Dosari", direction: "outbound", category: "reminder", subject_en: "Missed appointment — please rebook", subject_ar: "موعد فائت — يرجى إعادة الحجز", body_en: "Yousef missed his asthma review on the scheduled date. Regular reviews reduce the chance of an attack. Please rebook through the portal or call the paediatric clinic.", body_ar: "فات يوسف موعد مراجعة الربو في التاريخ المحدد. المراجعات المنتظمة تقلل احتمال النوبات. يرجى إعادة الحجز عبر البوابة أو الاتصال بعيادة الأطفال.", provider_id: "prov-08", provider_name: "Dr. Rana Al-Suwailem", status: "read", sent_at: ts(2), read_at: ts(2), replied_at: null, parent_message_id: null, attachment_count: 0, metadata: { linked_appointment: "appt-07" }, created_at: ts(2), updated_at: ts(2) },
  { id: "msg-07", workspace_id: W, patient_id: "pt-04", patient_name: "Noura Al-Qahtani", direction: "outbound", category: "appointment", subject_en: "Admission confirmed for your caesarean section", subject_ar: "تأكيد الدخول للعملية القيصرية", body_en: "Your admission is confirmed. Please do not eat from 06:00 on the day. Bring your maternity notes and hospital bag. The ward will call if the theatre time changes.", body_ar: "تم تأكيد دخولك. يرجى الامتناع عن الطعام من الساعة السادسة صباحاً وإحضار ملف الحمل وحقيبة المستشفى. سيتصل بك القسم عند تغير موعد العملية.", provider_id: "prov-07", provider_name: "Dr. Amal Al-Shamrani", status: "read", sent_at: ts(3), read_at: ts(3), replied_at: null, parent_message_id: null, attachment_count: 2, metadata: {}, created_at: ts(3), updated_at: ts(3) },
];

export const DEMO_TELEHEALTH_SESSIONS: T<"telehealth_sessions">[] = [
  { id: "tel-01", workspace_id: W, session_number: "TEL-2026-08801", appointment_id: "appt-02", encounter_id: "enc-11", patient_id: "pt-11", patient_name: "Layla Al-Anazi", provider_id: "prov-14", provider_name: "Dr. Lina Al-Yousef", scheduled_at: hrs(3), started_at: hrs(3), ended_at: hrs(2.75), duration_minutes: 15, status: "completed", room_id: "rm-8f2a91", patient_joined_at: hrs(3.05), provider_joined_at: hrs(3), connection_quality: "good", drop_count: 0, consent_recorded: true, recording_url: null, documents_shared: 2, chat_message_count: 6, metadata: { photos_reviewed: 3 }, created_at: ts(10), updated_at: hrs(2.75) },
  { id: "tel-02", workspace_id: W, session_number: "TEL-2026-08812", appointment_id: "appt-08", encounter_id: null, patient_id: "pt-11", patient_name: "Layla Al-Anazi", provider_id: "prov-14", provider_name: "Dr. Lina Al-Yousef", scheduled_at: inHrs(720), started_at: null, ended_at: null, duration_minutes: null, status: "scheduled", room_id: null, patient_joined_at: null, provider_joined_at: null, connection_quality: null, drop_count: 0, consent_recorded: false, recording_url: null, documents_shared: 0, chat_message_count: 0, metadata: {}, created_at: hrs(2.7), updated_at: hrs(2.7) },
  { id: "tel-03", workspace_id: W, session_number: "TEL-2026-08790", appointment_id: null, encounter_id: null, patient_id: "pt-13", patient_name: "Reem Al-Faisal", provider_id: "prov-01", provider_name: "Dr. Hala Al-Rasheed", scheduled_at: ts(8), started_at: ts(8), ended_at: ts(8), duration_minutes: 4, status: "failed", room_id: "rm-3c71bd", patient_joined_at: ts(8), provider_joined_at: ts(8), connection_quality: "poor", drop_count: 3, consent_recorded: true, recording_url: null, documents_shared: 0, chat_message_count: 2, metadata: { outcome: "Converted to a telephone consultation after three drops", incident_logged: true }, created_at: ts(12), updated_at: ts(8) },
  { id: "tel-04", workspace_id: W, session_number: "TEL-2026-08820", appointment_id: null, encounter_id: null, patient_id: "pt-03", patient_name: "Fatima Al-Harbi", provider_id: "prov-01", provider_name: "Dr. Hala Al-Rasheed", scheduled_at: inHrs(26), started_at: null, ended_at: null, duration_minutes: null, status: "scheduled", room_id: null, patient_joined_at: null, provider_joined_at: null, connection_quality: null, drop_count: 0, consent_recorded: false, recording_url: null, documents_shared: 0, chat_message_count: 0, metadata: { note: "Renal results discussion — daughter to interpret" }, created_at: hrs(28), updated_at: hrs(28) },
  { id: "tel-05", workspace_id: W, session_number: "TEL-2026-08775", appointment_id: null, encounter_id: null, patient_id: "pt-14", patient_name: "Saud Al-Amri", provider_id: "prov-02", provider_name: "Dr. Faisal Al-Harthy", scheduled_at: ts(20), started_at: null, ended_at: null, duration_minutes: null, status: "no_show", room_id: "rm-a01f42", patient_joined_at: null, provider_joined_at: ts(20), connection_quality: null, drop_count: 0, consent_recorded: false, recording_url: null, documents_shared: 0, chat_message_count: 0, metadata: { provider_waited_minutes: 12 }, created_at: ts(26), updated_at: ts(20) },
];

// ─── Interoperability ─────────────────────────────────────

export const DEMO_INTERFACE_ENDPOINTS: T<"interface_endpoints">[] = [
  { id: "ep-01", workspace_id: W, name_en: "Laboratory analyser interface", name_ar: "واجهة أجهزة المختبر", system_name: "Roche Cobas Middleware", protocol: "hl7v2", direction: "bidirectional", transport: "mllp", host: "10.20.4.11", port: 6661, sending_application: "AOG_LIS", sending_facility: "AOG_MAIN", message_types: ["ORM^O01", "ORU^R01", "ACK"], status: "up", last_heartbeat_at: mins(1), last_message_at: mins(4), messages_today: 1284, errors_today: 3, failure_threshold: 5, retry_policy: "Exponential backoff, 5 attempts over 15 minutes", owner_team: "Laboratory IT", metadata: {}, created_at: ts(400), updated_at: mins(1) },
  { id: "ep-02", workspace_id: W, name_en: "PACS / DICOM gateway", name_ar: "بوابة أرشيف الصور الطبية", system_name: "Sectra PACS", protocol: "dicom", direction: "bidirectional", transport: "tcp", host: "10.20.6.20", port: 104, sending_application: "AOG_RIS", sending_facility: "AOG_MAIN", message_types: ["C-STORE", "C-FIND", "MWL"], status: "up", last_heartbeat_at: mins(1), last_message_at: mins(12), messages_today: 342, errors_today: 0, failure_threshold: 3, retry_policy: "3 attempts, 30 second interval", owner_team: "Radiology IT", metadata: { modality_worklist: true }, created_at: ts(400), updated_at: mins(1) },
  { id: "ep-03", workspace_id: W, name_en: "National health exchange", name_ar: "منصة التبادل الصحي الوطنية", system_name: "NPHIES", protocol: "fhir_r4", direction: "bidirectional", transport: "https", host: "api.nphies.sa", port: 443, sending_application: "AOG_RCM", sending_facility: "AOG_MAIN", message_types: ["Claim", "ClaimResponse", "CoverageEligibilityRequest", "Patient"], status: "degraded", last_heartbeat_at: mins(3), last_message_at: mins(18), messages_today: 96, errors_today: 14, failure_threshold: 10, retry_policy: "Exponential backoff, 8 attempts over 2 hours", owner_team: "Revenue Cycle IT", metadata: { note: "Elevated 503 rate from the payer gateway since 06:00" }, created_at: ts(300), updated_at: mins(3) },
  { id: "ep-04", workspace_id: W, name_en: "Regional referral network", name_ar: "شبكة التحويلات الإقليمية", system_name: "Riyadh Health Cluster HIE", protocol: "fhir_r4", direction: "bidirectional", transport: "https", host: "hie.rhc.sa", port: 443, sending_application: "AOG_EHR", sending_facility: "AOG_MAIN", message_types: ["ServiceRequest", "DocumentReference", "Encounter"], status: "up", last_heartbeat_at: mins(2), last_message_at: mins(35), messages_today: 48, errors_today: 1, failure_threshold: 5, retry_policy: "5 attempts over 30 minutes", owner_team: "Integration", metadata: {}, created_at: ts(250), updated_at: mins(2) },
  { id: "ep-05", workspace_id: W, name_en: "Pharmacy dispensing robot", name_ar: "روبوت الصرف الصيدلاني", system_name: "BD Rowa Vmax", protocol: "hl7v2", direction: "outbound", transport: "mllp", host: "10.20.8.31", port: 6669, sending_application: "AOG_PHARM", sending_facility: "AOG_MAIN", message_types: ["RDE^O11", "RDS^O13"], status: "down", last_heartbeat_at: mins(52), last_message_at: mins(54), messages_today: 210, errors_today: 41, failure_threshold: 5, retry_policy: "5 attempts, 60 second interval, then dead letter", owner_team: "Pharmacy IT", metadata: { incident: "INC-2026-0912", note: "Robot controller unreachable — dispensing reverted to manual" }, created_at: ts(180), updated_at: mins(52) },
  { id: "ep-06", workspace_id: W, name_en: "ADT broadcast", name_ar: "بث حركة المرضى", system_name: "Internal subscribers", protocol: "hl7v2", direction: "outbound", transport: "mllp", host: "10.20.2.5", port: 6660, sending_application: "AOG_ADT", sending_facility: "AOG_MAIN", message_types: ["ADT^A01", "ADT^A03", "ADT^A08", "ADT^A11"], status: "up", last_heartbeat_at: mins(1), last_message_at: mins(2), messages_today: 412, errors_today: 0, failure_threshold: 5, retry_policy: "3 attempts, 15 second interval", owner_team: "Integration", metadata: { subscribers: ["Dietary", "Housekeeping", "Billing", "PACS"] }, created_at: ts(400), updated_at: mins(1) },
];

export const DEMO_INTERFACE_MESSAGES: T<"interface_messages">[] = [
  { id: "im-01", workspace_id: W, message_id: "MSG-20260831-004412", endpoint_id: "ep-06", endpoint_name: "ADT broadcast", direction: "outbound", protocol: "hl7v2", message_type: "ADT^A01", patient_id: "pt-01", patient_mrn: "MRN-100241", encounter_id: "enc-01", status: "acknowledged", sent_at: hrs(9), acknowledged_at: hrs(9), ack_code: "AA", error_message: null, retry_count: 0, payload_size_bytes: 1284, payload_preview: "MSH|^~\\&|AOG_ADT|AOG_MAIN|DIETARY|AOG_MAIN|20260831||ADT^A01|004412|P|2.5", processing_ms: 42, metadata: {}, created_at: hrs(9), updated_at: hrs(9) },
  { id: "im-02", workspace_id: W, message_id: "MSG-20260831-004498", endpoint_id: "ep-01", endpoint_name: "Laboratory analyser interface", direction: "inbound", protocol: "hl7v2", message_type: "ORU^R01", patient_id: "pt-06", patient_mrn: "MRN-100677", encounter_id: "enc-06", status: "acknowledged", sent_at: hrs(5.2), acknowledged_at: hrs(5.2), ack_code: "AA", error_message: null, retry_count: 0, payload_size_bytes: 2140, payload_preview: "MSH|^~\\&|COBAS|LAB|AOG_LIS|AOG_MAIN|20260831||ORU^R01|004498|P|2.5 … OBX|1|NM|2823-3^Potassium||6.4|mmol/L|3.5-5.1|HH", processing_ms: 88, metadata: { critical_result: true }, created_at: hrs(5.2), updated_at: hrs(5.2) },
  { id: "im-03", workspace_id: W, message_id: "MSG-20260831-004521", endpoint_id: "ep-02", endpoint_name: "PACS / DICOM gateway", direction: "outbound", protocol: "dicom", message_type: "MWL", patient_id: "pt-12", patient_mrn: "MRN-101208", encounter_id: "enc-12", status: "acknowledged", sent_at: mins(64), acknowledged_at: mins(64), ack_code: "AA", error_message: null, retry_count: 0, payload_size_bytes: 640, payload_preview: "Modality Worklist entry — accession RAD-2026-88245, modality CR, XR-2", processing_ms: 31, metadata: {}, created_at: mins(64), updated_at: mins(64) },
  { id: "im-04", workspace_id: W, message_id: "MSG-20260831-004540", endpoint_id: "ep-03", endpoint_name: "National health exchange", direction: "outbound", protocol: "fhir_r4", message_type: "Claim", patient_id: "pt-14", patient_mrn: "MRN-101402", encounter_id: "enc-14", status: "acknowledged", sent_at: hrs(24), acknowledged_at: hrs(23.9), ack_code: "AA", error_message: null, retry_count: 0, payload_size_bytes: 8420, payload_preview: '{"resourceType":"Claim","id":"CLM-2026-71120","status":"active","use":"claim"…', processing_ms: 640, metadata: { claim_id: "clm-01" }, created_at: hrs(24), updated_at: hrs(23.9) },
  { id: "im-05", workspace_id: W, message_id: "MSG-20260831-004602", endpoint_id: "ep-03", endpoint_name: "National health exchange", direction: "outbound", protocol: "fhir_r4", message_type: "CoverageEligibilityRequest", patient_id: "pt-12", patient_mrn: "MRN-101208", encounter_id: "enc-12", status: "retrying", sent_at: mins(88), acknowledged_at: null, ack_code: null, error_message: "HTTP 503 Service Unavailable from the payer gateway", retry_count: 4, payload_size_bytes: 1820, payload_preview: '{"resourceType":"CoverageEligibilityRequest","patient":{"reference":"Patient/MRN-101208"}…', processing_ms: null, metadata: { next_retry_in_minutes: 16 }, created_at: mins(88), updated_at: mins(12) },
  { id: "im-06", workspace_id: W, message_id: "MSG-20260831-004388", endpoint_id: "ep-05", endpoint_name: "Pharmacy dispensing robot", direction: "outbound", protocol: "hl7v2", message_type: "RDE^O11", patient_id: "pt-03", patient_mrn: "MRN-100455", encounter_id: "enc-03", status: "dead_letter", sent_at: mins(54), acknowledged_at: null, ack_code: null, error_message: "Connection refused after 5 attempts — robot controller unreachable", retry_count: 5, payload_size_bytes: 980, payload_preview: "MSH|^~\\&|AOG_PHARM|AOG_MAIN|ROWA|AOG_MAIN|20260831||RDE^O11|004388|P|2.5", processing_ms: null, metadata: { incident: "INC-2026-0912", manual_fallback: true, dispense_id: "disp-05" }, created_at: mins(54), updated_at: mins(20) },
  { id: "im-07", workspace_id: W, message_id: "MSG-20260831-004610", endpoint_id: "ep-04", endpoint_name: "Regional referral network", direction: "inbound", protocol: "fhir_r4", message_type: "ServiceRequest", patient_id: "pt-03", patient_mrn: "MRN-100455", encounter_id: null, status: "acknowledged", sent_at: mins(35), acknowledged_at: mins(35), ack_code: "AA", error_message: null, retry_count: 0, payload_size_bytes: 3240, payload_preview: '{"resourceType":"ServiceRequest","intent":"order","category":"Nephrology referral"…', processing_ms: 210, metadata: { referral_to: "Nephrology" }, created_at: mins(35), updated_at: mins(35) },
  { id: "im-08", workspace_id: W, message_id: "MSG-20260831-004455", endpoint_id: "ep-01", endpoint_name: "Laboratory analyser interface", direction: "inbound", protocol: "hl7v2", message_type: "ORU^R01", patient_id: "pt-02", patient_mrn: "MRN-100388", encounter_id: "enc-02", status: "rejected", sent_at: hrs(9), acknowledged_at: hrs(9), ack_code: "AE", error_message: "Specimen rejected at the analyser — haemolysis index above the reportable limit", retry_count: 0, payload_size_bytes: 1120, payload_preview: "MSH|^~\\&|COBAS|LAB|AOG_LIS|AOG_MAIN|20260831||ORU^R01|004455|P|2.5 … OBX|1|ST|LFT||REJECTED", processing_ms: 54, metadata: { lab_order: "lab-10", recollection_requested: true }, created_at: hrs(9), updated_at: hrs(9) },
  { id: "im-09", workspace_id: W, message_id: "MSG-20260831-004625", endpoint_id: "ep-06", endpoint_name: "ADT broadcast", direction: "outbound", protocol: "hl7v2", message_type: "ADT^A03", patient_id: "pt-14", patient_mrn: "MRN-101402", encounter_id: "enc-14", status: "acknowledged", sent_at: hrs(26), acknowledged_at: hrs(26), ack_code: "AA", error_message: null, retry_count: 0, payload_size_bytes: 1180, payload_preview: "MSH|^~\\&|AOG_ADT|AOG_MAIN|BILLING|AOG_MAIN|20260831||ADT^A03|004625|P|2.5", processing_ms: 38, metadata: { triggered: ["Housekeeping task HK-2026-11201", "Claim CLM-2026-71120"] }, created_at: hrs(26), updated_at: hrs(26) },
  { id: "im-10", workspace_id: W, message_id: "MSG-20260831-004640", endpoint_id: "ep-02", endpoint_name: "PACS / DICOM gateway", direction: "inbound", protocol: "dicom", message_type: "C-STORE", patient_id: "pt-12", patient_mrn: "MRN-101208", encounter_id: "enc-12", status: "acknowledged", sent_at: mins(29), acknowledged_at: mins(29), ack_code: "AA", error_message: null, retry_count: 0, payload_size_bytes: 14_800_000, payload_preview: "Study 1.2.840.113619.2.55.3.2831164356.902.4 — 1 series, 2 images", processing_ms: 1840, metadata: { study_uid: "1.2.840.113619.2.55.3.2831164356.902.4" }, created_at: mins(29), updated_at: mins(29) },
  { id: "im-11", workspace_id: W, message_id: "MSG-20260831-004651", endpoint_id: "ep-05", endpoint_name: "Pharmacy dispensing robot", direction: "outbound", protocol: "hl7v2", message_type: "RDE^O11", patient_id: "pt-13", patient_mrn: "MRN-101315", encounter_id: "enc-13", status: "queued", sent_at: null, acknowledged_at: null, ack_code: null, error_message: null, retry_count: 0, payload_size_bytes: 940, payload_preview: "MSH|^~\\&|AOG_PHARM|AOG_MAIN|ROWA|AOG_MAIN|20260831||RDE^O11|004651|P|2.5", processing_ms: null, metadata: { held: "Endpoint down — queued for replay" }, created_at: mins(18), updated_at: mins(18) },
  { id: "im-12", workspace_id: W, message_id: "MSG-20260831-004301", endpoint_id: "ep-03", endpoint_name: "National health exchange", direction: "inbound", protocol: "fhir_r4", message_type: "ClaimResponse", patient_id: "pt-07", patient_mrn: "MRN-100714", encounter_id: "enc-07", status: "acknowledged", sent_at: hrs(20), acknowledged_at: hrs(20), ack_code: "AA", error_message: null, retry_count: 0, payload_size_bytes: 2960, payload_preview: '{"resourceType":"ClaimResponse","outcome":"error","disposition":"Coverage terminated"…', processing_ms: 320, metadata: { claim_id: "clm-03", denial_code: "CO-27" }, created_at: hrs(20), updated_at: hrs(20) },
];
