/**
 * Clinical Demo Seed — orders, medicines and diagnostics.
 *
 * Continues the cohort defined in `clinical-seed.ts`. The orders here are
 * written to exercise the CDSS rules deliberately: pt-01 has a penicillin
 * allergy and an active co-amoxiclav order sitting behind an override,
 * pt-03 is on a renally contraindicated metformin dose, and pt-12 has an
 * aspirin allergy against an aspirin order. Those are the cases worth seeing
 * on a demo, not a list of uneventful paracetamol.
 */

import type { Database } from "@/domain/types";

type T<K extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][K]["Row"];

const W = "demo";
const d = (daysAgo: number) => new Date(Date.now() - daysAgo * 86_400_000).toISOString().slice(0, 10);
const ts = (daysAgo: number) => new Date(Date.now() - daysAgo * 86_400_000).toISOString();
const hrs = (hoursAgo: number) => new Date(Date.now() - hoursAgo * 3_600_000).toISOString();
const mins = (minutesAgo: number) => new Date(Date.now() - minutesAgo * 60_000).toISOString();
const inHrs = (hoursAhead: number) => new Date(Date.now() + hoursAhead * 3_600_000).toISOString();
const inDays = (daysAhead: number) => new Date(Date.now() + daysAhead * 86_400_000).toISOString().slice(0, 10);

// ─── CPOE orders ──────────────────────────────────────────

export const DEMO_CLINICAL_ORDERS: T<"clinical_orders">[] = [
  // pt-01 — NSTEMI protocol
  { id: "ord-01", workspace_id: W, order_number: "ORD-2026-118401", encounter_id: "enc-01", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", category: "medication", item_en: "Aspirin", item_ar: "أسبرين", item_code: "B01AC06", priority: "stat", status: "active", ordered_by_id: "prov-03", ordered_by_name: "Dr. Nasser Al-Juhani", ordered_at: hrs(11), start_at: hrs(11), end_at: null, dose: "75", dose_unit: "mg", route: "oral", frequency: "OD", duration_days: null, prn: false, prn_reason: null, instructions_en: "Continue indefinitely post-ACS", instructions_ar: "الاستمرار بعد المتلازمة التاجية", override_reason: null, department_id: "dept-02", metadata: {}, created_at: hrs(11), updated_at: hrs(11) },
  { id: "ord-02", workspace_id: W, order_number: "ORD-2026-118402", encounter_id: "enc-01", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", category: "medication", item_en: "Clopidogrel", item_ar: "كلوبيدوجريل", item_code: "B01AC04", priority: "stat", status: "active", ordered_by_id: "prov-03", ordered_by_name: "Dr. Nasser Al-Juhani", ordered_at: hrs(11), start_at: hrs(11), end_at: null, dose: "75", dose_unit: "mg", route: "oral", frequency: "OD", duration_days: 365, prn: false, prn_reason: null, instructions_en: "600 mg loading dose given in ED", instructions_ar: "أُعطيت جرعة تحميل ٦٠٠ ملغ في الطوارئ", override_reason: null, department_id: "dept-02", metadata: {}, created_at: hrs(11), updated_at: hrs(11) },
  { id: "ord-03", workspace_id: W, order_number: "ORD-2026-118403", encounter_id: "enc-01", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", category: "medication", item_en: "Enoxaparin", item_ar: "إينوكسابارين", item_code: "B01AB05", priority: "urgent", status: "active", ordered_by_id: "prov-01", ordered_by_name: "Dr. Hala Al-Rasheed", ordered_at: hrs(9), start_at: hrs(9), end_at: null, dose: "90", dose_unit: "mg", route: "sc", frequency: "BD", duration_days: 5, prn: false, prn_reason: null, instructions_en: "Treatment dose, 1 mg/kg BD. Weight 91 kg.", instructions_ar: "جرعة علاجية ١ ملغ/كغ مرتين يومياً. الوزن ٩١ كغ.", override_reason: null, department_id: "dept-02", metadata: {}, created_at: hrs(9), updated_at: hrs(9) },
  { id: "ord-04", workspace_id: W, order_number: "ORD-2026-118404", encounter_id: "enc-01", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", category: "medication", item_en: "Atorvastatin", item_ar: "أتورفاستاتين", item_code: "C10AA05", priority: "routine", status: "active", ordered_by_id: "prov-01", ordered_by_name: "Dr. Hala Al-Rasheed", ordered_at: hrs(9), start_at: hrs(9), end_at: null, dose: "80", dose_unit: "mg", route: "oral", frequency: "OD", duration_days: null, prn: false, prn_reason: null, instructions_en: "High-intensity statin post-ACS", instructions_ar: "ستاتين عالي الشدة بعد المتلازمة التاجية", override_reason: null, department_id: "dept-02", metadata: {}, created_at: hrs(9), updated_at: hrs(9) },
  { id: "ord-05", workspace_id: W, order_number: "ORD-2026-118405", encounter_id: "enc-01", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", category: "lab", item_en: "Troponin T, serial", item_ar: "تروبونين T متسلسل", item_code: "6598-7", priority: "stat", status: "in_progress", ordered_by_id: "prov-01", ordered_by_name: "Dr. Hala Al-Rasheed", ordered_at: hrs(9), start_at: hrs(9), end_at: null, dose: null, dose_unit: null, route: null, frequency: "q6h", duration_days: 1, prn: false, prn_reason: null, instructions_en: "0, 6 and 12 hours", instructions_ar: "عند صفر و٦ و١٢ ساعة", override_reason: null, department_id: "dept-08", metadata: {}, created_at: hrs(9), updated_at: hrs(3) },
  { id: "ord-06", workspace_id: W, order_number: "ORD-2026-118406", encounter_id: "enc-01", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", category: "procedure", item_en: "Coronary angiography", item_ar: "قسطرة الشرايين التاجية", item_code: "93458", priority: "urgent", status: "active", ordered_by_id: "prov-01", ordered_by_name: "Dr. Hala Al-Rasheed", ordered_at: hrs(2), start_at: inHrs(14), end_at: null, dose: null, dose_unit: null, route: null, frequency: null, duration_days: null, prn: false, prn_reason: null, instructions_en: "Consented. Fast from midnight. Hold enoxaparin morning dose.", instructions_ar: "تمت الموافقة. صيام من منتصف الليل. إيقاف جرعة الإينوكسابارين الصباحية.", override_reason: null, department_id: "dept-02", metadata: {}, created_at: hrs(2), updated_at: hrs(2) },
  // The interesting one: an allergy override, recorded rather than hidden.
  { id: "ord-07", workspace_id: W, order_number: "ORD-2026-118412", encounter_id: "enc-01", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", category: "medication", item_en: "Co-amoxiclav", item_ar: "كو-أموكسيكلاف", item_code: "J01CR02", priority: "urgent", status: "active", ordered_by_id: "prov-01", ordered_by_name: "Dr. Hala Al-Rasheed", ordered_at: hrs(6), start_at: hrs(6), end_at: null, dose: "1.2", dose_unit: "g", route: "iv", frequency: "TDS", duration_days: 5, prn: false, prn_reason: null, instructions_en: "For aspiration pneumonia on the CXR.", instructions_ar: "لعلاج الالتهاب الرئوي الاستنشاقي الظاهر بأشعة الصدر.", override_reason: "Documented penicillin reaction was a delayed rash without airway involvement. Discussed with the patient and with microbiology; benefit judged to outweigh risk. First dose given under observation with hydrocortisone and chlorphenamine available.", department_id: "dept-02", metadata: { cdss_override: true }, created_at: hrs(6), updated_at: hrs(6) },

  // pt-06 — ICU sepsis
  { id: "ord-08", workspace_id: W, order_number: "ORD-2026-118201", encounter_id: "enc-06", patient_id: "pt-06", patient_name: "Abdullah Al-Shehri", category: "medication", item_en: "Meropenem", item_ar: "ميروبينيم", item_code: "J01DH02", priority: "stat", status: "active", ordered_by_id: "prov-06", ordered_by_name: "Dr. Omar Bin Salem", ordered_at: hrs(76), start_at: hrs(76), end_at: null, dose: "1", dose_unit: "g", route: "iv", frequency: "TDS", duration_days: 7, prn: false, prn_reason: null, instructions_en: "Renally adjusted for eGFR 34. Day 3 of 7.", instructions_ar: "معدّل كلوياً لمعدل ترشيح ٣٤. اليوم الثالث من سبعة.", override_reason: null, department_id: "dept-04", metadata: {}, created_at: hrs(76), updated_at: hrs(4) },
  { id: "ord-09", workspace_id: W, order_number: "ORD-2026-118202", encounter_id: "enc-06", patient_id: "pt-06", patient_name: "Abdullah Al-Shehri", category: "medication", item_en: "Noradrenaline infusion", item_ar: "تسريب نورأدرينالين", item_code: "C01CA03", priority: "stat", status: "active", ordered_by_id: "prov-06", ordered_by_name: "Dr. Omar Bin Salem", ordered_at: hrs(76), start_at: hrs(76), end_at: null, dose: "0.06", dose_unit: "mcg/kg/min", route: "iv", frequency: "continuous", duration_days: null, prn: false, prn_reason: null, instructions_en: "Titrate to MAP above 65 mmHg. Central line, right IJ.", instructions_ar: "المعايرة للحفاظ على ضغط شرياني وسطي فوق ٦٥. قسطرة مركزية وريد وداجي أيمن.", override_reason: null, department_id: "dept-04", metadata: {}, created_at: hrs(76), updated_at: hrs(1) },
  { id: "ord-10", workspace_id: W, order_number: "ORD-2026-118203", encounter_id: "enc-06", patient_id: "pt-06", patient_name: "Abdullah Al-Shehri", category: "nursing", item_en: "Hourly urine output and MAP", item_ar: "قياس إدرار البول والضغط الوسطي كل ساعة", item_code: null, priority: "routine", status: "active", ordered_by_id: "prov-06", ordered_by_name: "Dr. Omar Bin Salem", ordered_at: hrs(76), start_at: hrs(76), end_at: null, dose: null, dose_unit: null, route: null, frequency: "hourly", duration_days: null, prn: false, prn_reason: null, instructions_en: "Escalate if urine output below 0.5 mL/kg/h for two consecutive hours.", instructions_ar: "التصعيد إذا قل إدرار البول عن ٠٫٥ مل/كغ/ساعة لساعتين متتاليتين.", override_reason: null, department_id: "dept-04", metadata: {}, created_at: hrs(76), updated_at: hrs(76) },
  { id: "ord-11", workspace_id: W, order_number: "ORD-2026-118204", encounter_id: "enc-06", patient_id: "pt-06", patient_name: "Abdullah Al-Shehri", category: "lab", item_en: "Arterial blood gas", item_ar: "غازات الدم الشرياني", item_code: "24336-0", priority: "urgent", status: "active", ordered_by_id: "prov-06", ordered_by_name: "Dr. Omar Bin Salem", ordered_at: hrs(24), start_at: hrs(24), end_at: null, dose: null, dose_unit: null, route: null, frequency: "q6h", duration_days: null, prn: false, prn_reason: null, instructions_en: null, instructions_ar: null, override_reason: null, department_id: "dept-08", metadata: {}, created_at: hrs(24), updated_at: hrs(4) },

  // pt-03 — the renal dose case
  { id: "ord-12", workspace_id: W, order_number: "ORD-2026-118501", encounter_id: "enc-03", patient_id: "pt-03", patient_name: "Fatima Al-Harbi", category: "medication", item_en: "Metformin", item_ar: "ميتفورمين", item_code: "A10BA02", priority: "routine", status: "cancelled", ordered_by_id: "prov-01", ordered_by_name: "Dr. Hala Al-Rasheed", ordered_at: ts(180), start_at: ts(180), end_at: hrs(30), dose: "1000", dose_unit: "mg", route: "oral", frequency: "BD", duration_days: null, prn: false, prn_reason: null, instructions_en: "Stopped — eGFR fell to 26, below the contraindication threshold.", instructions_ar: "أُوقف — انخفض معدل الترشيح إلى ٢٦ تحت حد المنع.", override_reason: null, department_id: "dept-02", metadata: { stopped_by_cdss: true }, created_at: ts(180), updated_at: hrs(30) },
  { id: "ord-13", workspace_id: W, order_number: "ORD-2026-118502", encounter_id: "enc-03", patient_id: "pt-03", patient_name: "Fatima Al-Harbi", category: "medication", item_en: "Linagliptin", item_ar: "ليناغليبتين", item_code: "A10BH05", priority: "routine", status: "active", ordered_by_id: "prov-01", ordered_by_name: "Dr. Hala Al-Rasheed", ordered_at: hrs(30), start_at: hrs(30), end_at: null, dose: "5", dose_unit: "mg", route: "oral", frequency: "OD", duration_days: null, prn: false, prn_reason: null, instructions_en: "No renal dose adjustment required.", instructions_ar: "لا يحتاج تعديلاً كلوياً.", override_reason: null, department_id: "dept-02", metadata: {}, created_at: hrs(30), updated_at: hrs(30) },
  { id: "ord-14", workspace_id: W, order_number: "ORD-2026-118503", encounter_id: "enc-03", patient_id: "pt-03", patient_name: "Fatima Al-Harbi", category: "lab", item_en: "Renal profile and eGFR", item_ar: "وظائف الكلى ومعدل الترشيح", item_code: "24362-6", priority: "routine", status: "completed", ordered_by_id: "prov-01", ordered_by_name: "Dr. Hala Al-Rasheed", ordered_at: hrs(31), start_at: hrs(31), end_at: hrs(29), dose: null, dose_unit: null, route: null, frequency: null, duration_days: null, prn: false, prn_reason: null, instructions_en: "Repeat in four weeks.", instructions_ar: "الإعادة بعد أربعة أسابيع.", override_reason: null, department_id: "dept-08", metadata: {}, created_at: hrs(31), updated_at: hrs(29) },

  // pt-02 — post-op
  { id: "ord-15", workspace_id: W, order_number: "ORD-2026-118301", encounter_id: "enc-02", patient_id: "pt-02", patient_name: "Maryam Al-Ghamdi", category: "medication", item_en: "Paracetamol", item_ar: "باراسيتامول", item_code: "N02BE01", priority: "routine", status: "active", ordered_by_id: "prov-02", ordered_by_name: "Dr. Faisal Al-Harthy", ordered_at: hrs(26), start_at: hrs(26), end_at: null, dose: "1000", dose_unit: "mg", route: "oral", frequency: "QDS", duration_days: 5, prn: false, prn_reason: null, instructions_en: "Maximum 4 g in 24 hours.", instructions_ar: "بحد أقصى ٤ غرام في اليوم.", override_reason: null, department_id: "dept-03", metadata: {}, created_at: hrs(26), updated_at: hrs(26) },
  { id: "ord-16", workspace_id: W, order_number: "ORD-2026-118302", encounter_id: "enc-02", patient_id: "pt-02", patient_name: "Maryam Al-Ghamdi", category: "medication", item_en: "Ondansetron", item_ar: "أوندانسيترون", item_code: "A04AA01", priority: "routine", status: "active", ordered_by_id: "prov-02", ordered_by_name: "Dr. Faisal Al-Harthy", ordered_at: hrs(26), start_at: hrs(26), end_at: null, dose: "4", dose_unit: "mg", route: "iv", frequency: "TDS", duration_days: 2, prn: true, prn_reason: "Nausea or vomiting", instructions_en: "Metoclopramide avoided — documented intolerance.", instructions_ar: "تجنب الميتوكلوبراميد لعدم التحمل الموثق.", override_reason: null, department_id: "dept-03", metadata: {}, created_at: hrs(26), updated_at: hrs(26) },
  { id: "ord-17", workspace_id: W, order_number: "ORD-2026-118303", encounter_id: "enc-02", patient_id: "pt-02", patient_name: "Maryam Al-Ghamdi", category: "diet", item_en: "Light diet as tolerated", item_ar: "غذاء خفيف حسب التحمل", item_code: null, priority: "routine", status: "active", ordered_by_id: "prov-02", ordered_by_name: "Dr. Faisal Al-Harthy", ordered_at: hrs(24), start_at: hrs(24), end_at: null, dose: null, dose_unit: null, route: null, frequency: null, duration_days: null, prn: false, prn_reason: null, instructions_en: "Progress to normal diet if tolerated.", instructions_ar: "التدرج إلى الغذاء الطبيعي حسب التحمل.", override_reason: null, department_id: "dept-03", metadata: {}, created_at: hrs(24), updated_at: hrs(24) },

  // pt-05 — paediatric asthma
  { id: "ord-18", workspace_id: W, order_number: "ORD-2026-118601", encounter_id: "enc-05", patient_id: "pt-05", patient_name: "Yousef Al-Dosari", category: "medication", item_en: "Salbutamol nebuliser", item_ar: "سالبوتامول بخاخ", item_code: "R03AC02", priority: "urgent", status: "active", ordered_by_id: "prov-08", ordered_by_name: "Dr. Rana Al-Suwailem", ordered_at: hrs(5), start_at: hrs(5), end_at: null, dose: "2.5", dose_unit: "mg", route: "inhaled", frequency: "q4h", duration_days: 2, prn: false, prn_reason: null, instructions_en: "Step down to PRN once stable for eight hours.", instructions_ar: "التخفيف إلى عند اللزوم بعد استقرار ثماني ساعات.", override_reason: null, department_id: "dept-06", metadata: { weight_based: true, weight_kg: 24 }, created_at: hrs(5), updated_at: hrs(1) },
  { id: "ord-19", workspace_id: W, order_number: "ORD-2026-118602", encounter_id: "enc-05", patient_id: "pt-05", patient_name: "Yousef Al-Dosari", category: "medication", item_en: "Prednisolone", item_ar: "بريدنيزولون", item_code: "H02AB06", priority: "urgent", status: "active", ordered_by_id: "prov-08", ordered_by_name: "Dr. Rana Al-Suwailem", ordered_at: hrs(5), start_at: hrs(5), end_at: null, dose: "24", dose_unit: "mg", route: "oral", frequency: "OD", duration_days: 3, prn: false, prn_reason: null, instructions_en: "1 mg/kg, weight 24 kg. Three-day course, no taper needed.", instructions_ar: "١ ملغ/كغ بوزن ٢٤ كغ. مدة ثلاثة أيام دون تدرج في الإيقاف.", override_reason: null, department_id: "dept-06", metadata: { weight_based: true }, created_at: hrs(5), updated_at: hrs(5) },

  // pt-12 — ED, the aspirin allergy case
  { id: "ord-20", workspace_id: W, order_number: "ORD-2026-118701", encounter_id: "enc-12", patient_id: "pt-12", patient_name: "Turki Al-Malki", category: "medication", item_en: "Salbutamol nebuliser", item_ar: "سالبوتامول بخاخ", item_code: "R03AC02", priority: "stat", status: "active", ordered_by_id: "prov-03", ordered_by_name: "Dr. Nasser Al-Juhani", ordered_at: mins(75), start_at: mins(75), end_at: null, dose: "5", dose_unit: "mg", route: "inhaled", frequency: "q4h", duration_days: 1, prn: false, prn_reason: null, instructions_en: "Driven by air, not oxygen, given CO2 retention risk.", instructions_ar: "يُعطى بالهواء لا بالأكسجين بسبب خطر احتباس ثاني أكسيد الكربون.", override_reason: null, department_id: "dept-01", metadata: {}, created_at: mins(75), updated_at: mins(75) },
  { id: "ord-21", workspace_id: W, order_number: "ORD-2026-118702", encounter_id: "enc-12", patient_id: "pt-12", patient_name: "Turki Al-Malki", category: "medication", item_en: "Prednisolone", item_ar: "بريدنيزولون", item_code: "H02AB06", priority: "urgent", status: "active", ordered_by_id: "prov-03", ordered_by_name: "Dr. Nasser Al-Juhani", ordered_at: mins(70), start_at: mins(70), end_at: null, dose: "30", dose_unit: "mg", route: "oral", frequency: "OD", duration_days: 5, prn: false, prn_reason: null, instructions_en: null, instructions_ar: null, override_reason: null, department_id: "dept-01", metadata: {}, created_at: mins(70), updated_at: mins(70) },
  { id: "ord-22", workspace_id: W, order_number: "ORD-2026-118703", encounter_id: "enc-12", patient_id: "pt-12", patient_name: "Turki Al-Malki", category: "imaging", item_en: "Chest X-ray, PA erect", item_ar: "أشعة صدر أمامية خلفية", item_code: "71046", priority: "urgent", status: "in_progress", ordered_by_id: "prov-03", ordered_by_name: "Dr. Nasser Al-Juhani", ordered_at: mins(65), start_at: mins(65), end_at: null, dose: null, dose_unit: null, route: null, frequency: null, duration_days: null, prn: false, prn_reason: null, instructions_en: "Exclude pneumothorax and consolidation.", instructions_ar: "لاستبعاد الاسترواح الصدري والتصلد.", override_reason: null, department_id: "dept-09", metadata: {}, created_at: mins(65), updated_at: mins(30) },
  // Drafted and blocked — the demo's hard-stop case.
  { id: "ord-23", workspace_id: W, order_number: "ORD-2026-118704", encounter_id: "enc-12", patient_id: "pt-12", patient_name: "Turki Al-Malki", category: "medication", item_en: "Aspirin", item_ar: "أسبرين", item_code: "B01AC06", priority: "routine", status: "draft", ordered_by_id: "prov-03", ordered_by_name: "Dr. Nasser Al-Juhani", ordered_at: mins(28), start_at: null, end_at: null, dose: "75", dose_unit: "mg", route: "oral", frequency: "OD", duration_days: null, prn: false, prn_reason: null, instructions_en: null, instructions_ar: null, override_reason: null, department_id: "dept-01", metadata: { blocked_by_cdss: true }, created_at: mins(28), updated_at: mins(28) },

  // pt-08 — pre-op
  { id: "ord-24", workspace_id: W, order_number: "ORD-2026-118801", encounter_id: "enc-08", patient_id: "pt-08", patient_name: "Ibrahim Al-Zahrani", category: "medication", item_en: "Morphine sulfate", item_ar: "كبريتات المورفين", item_code: "N02AA01", priority: "urgent", status: "active", ordered_by_id: "prov-09", ordered_by_name: "Dr. Bandar Al-Otaibi", ordered_at: hrs(20), start_at: hrs(20), end_at: null, dose: "5", dose_unit: "mg", route: "iv", frequency: "q4h", duration_days: 2, prn: true, prn_reason: "Pain score above 4", instructions_en: "Controlled drug — two-nurse check and register entry required.", instructions_ar: "دواء خاضع للرقابة — يلزم تحقق ممرضين وتسجيل في السجل.", override_reason: null, department_id: "dept-07", metadata: { controlled: true }, created_at: hrs(20), updated_at: hrs(20) },
  { id: "ord-25", workspace_id: W, order_number: "ORD-2026-118802", encounter_id: "enc-08", patient_id: "pt-08", patient_name: "Ibrahim Al-Zahrani", category: "blood", item_en: "Group and save, hold 2 units", item_ar: "فصيلة الدم مع حجز وحدتين", item_code: null, priority: "urgent", status: "completed", ordered_by_id: "prov-09", ordered_by_name: "Dr. Bandar Al-Otaibi", ordered_at: hrs(19), start_at: hrs(19), end_at: hrs(16), dose: null, dose_unit: null, route: null, frequency: null, duration_days: null, prn: false, prn_reason: null, instructions_en: "For intramedullary nailing.", instructions_ar: "لعملية التثبيت داخل النخاع.", override_reason: null, department_id: "dept-08", metadata: {}, created_at: hrs(19), updated_at: hrs(16) },
  { id: "ord-26", workspace_id: W, order_number: "ORD-2026-118803", encounter_id: "enc-08", patient_id: "pt-08", patient_name: "Ibrahim Al-Zahrani", category: "nursing", item_en: "Nil by mouth from midnight", item_ar: "الصيام من منتصف الليل", item_code: null, priority: "routine", status: "active", ordered_by_id: "prov-09", ordered_by_name: "Dr. Bandar Al-Otaibi", ordered_at: hrs(18), start_at: hrs(18), end_at: null, dose: null, dose_unit: null, route: null, frequency: null, duration_days: null, prn: false, prn_reason: null, instructions_en: "Clear fluids permitted until two hours pre-op.", instructions_ar: "يُسمح بالسوائل الصافية حتى ساعتين قبل العملية.", override_reason: null, department_id: "dept-07", metadata: {}, created_at: hrs(18), updated_at: hrs(18) },

  // pt-09 — oncology
  { id: "ord-27", workspace_id: W, order_number: "ORD-2026-118901", encounter_id: "enc-09", patient_id: "pt-09", patient_name: "Hessa Al-Subaie", category: "medication", item_en: "Oxaliplatin", item_ar: "أوكزاليبلاتين", item_code: "L01XA03", priority: "routine", status: "in_progress", ordered_by_id: "prov-13", ordered_by_name: "Dr. Ziad Al-Mansour", ordered_at: hrs(7), start_at: hrs(6), end_at: null, dose: "150", dose_unit: "mg", route: "iv", frequency: "q14d", duration_days: 1, prn: false, prn_reason: null, instructions_en: "85 mg/m² over 2 hours. BSA 1.76. Cycle 4 of 12.", instructions_ar: "٨٥ ملغ/م² على مدى ساعتين. مساحة السطح ١٫٧٦. الدورة الرابعة من ١٢.", override_reason: null, department_id: "dept-12", metadata: { high_alert: true, bsa: 1.76 }, created_at: hrs(7), updated_at: hrs(6) },
  { id: "ord-28", workspace_id: W, order_number: "ORD-2026-118902", encounter_id: "enc-09", patient_id: "pt-09", patient_name: "Hessa Al-Subaie", category: "medication", item_en: "Ondansetron", item_ar: "أوندانسيترون", item_code: "A04AA01", priority: "routine", status: "completed", ordered_by_id: "prov-13", ordered_by_name: "Dr. Ziad Al-Mansour", ordered_at: hrs(7), start_at: hrs(7), end_at: hrs(6), dose: "8", dose_unit: "mg", route: "iv", frequency: "OD", duration_days: 1, prn: false, prn_reason: null, instructions_en: "Pre-chemotherapy antiemetic.", instructions_ar: "مضاد قيء قبل العلاج الكيميائي.", override_reason: null, department_id: "dept-12", metadata: {}, created_at: hrs(7), updated_at: hrs(6) },

  // pt-04 — maternity
  { id: "ord-29", workspace_id: W, order_number: "ORD-2026-118951", encounter_id: "enc-04", patient_id: "pt-04", patient_name: "Noura Al-Qahtani", category: "nursing", item_en: "CTG monitoring, 30 minutes q4h", item_ar: "مراقبة نبض الجنين ٣٠ دقيقة كل ٤ ساعات", item_code: null, priority: "routine", status: "active", ordered_by_id: "prov-07", ordered_by_name: "Dr. Amal Al-Shamrani", ordered_at: hrs(14), start_at: hrs(14), end_at: null, dose: null, dose_unit: null, route: null, frequency: "q4h", duration_days: null, prn: false, prn_reason: null, instructions_en: "Escalate for any decelerations.", instructions_ar: "التصعيد عند أي تباطؤ.", override_reason: null, department_id: "dept-05", metadata: {}, created_at: hrs(14), updated_at: hrs(2) },
  { id: "ord-30", workspace_id: W, order_number: "ORD-2026-118952", encounter_id: "enc-04", patient_id: "pt-04", patient_name: "Noura Al-Qahtani", category: "procedure", item_en: "Elective lower segment caesarean section", item_ar: "عملية قيصرية مخططة", item_code: "59510", priority: "routine", status: "active", ordered_by_id: "prov-07", ordered_by_name: "Dr. Amal Al-Shamrani", ordered_at: hrs(13), start_at: inHrs(3), end_at: null, dose: null, dose_unit: null, route: null, frequency: null, duration_days: null, prn: false, prn_reason: null, instructions_en: "Consented. Spinal anaesthesia planned.", instructions_ar: "تمت الموافقة. التخدير النصفي مخطط.", override_reason: null, department_id: "dept-05", metadata: {}, created_at: hrs(13), updated_at: hrs(13) },
];

// ─── Medication administration record ─────────────────────

export const DEMO_MED_ADMINISTRATIONS: T<"med_administrations">[] = [
  { id: "mar-01", workspace_id: W, order_id: "ord-01", encounter_id: "enc-01", patient_id: "pt-01", drug_name: "Aspirin 75 mg", dose: "75 mg", route: "oral", scheduled_at: hrs(10), administered_at: hrs(10), administered_by: "Nurse Aisha Al-Dakhil", status: "given", hold_reason: null, site: null, witnessed_by: null, metadata: {}, created_at: hrs(11), updated_at: hrs(10) },
  { id: "mar-02", workspace_id: W, order_id: "ord-03", encounter_id: "enc-01", patient_id: "pt-01", drug_name: "Enoxaparin 90 mg", dose: "90 mg", route: "sc", scheduled_at: hrs(9), administered_at: hrs(9), administered_by: "Nurse Aisha Al-Dakhil", status: "given", hold_reason: null, site: "Left abdomen", witnessed_by: null, metadata: {}, created_at: hrs(9), updated_at: hrs(9) },
  { id: "mar-03", workspace_id: W, order_id: "ord-03", encounter_id: "enc-01", patient_id: "pt-01", drug_name: "Enoxaparin 90 mg", dose: "90 mg", route: "sc", scheduled_at: inHrs(3), administered_at: null, administered_by: null, status: "due", hold_reason: null, site: null, witnessed_by: null, metadata: { note: "Hold if angiography confirmed for the morning" }, created_at: hrs(9), updated_at: hrs(9) },
  { id: "mar-04", workspace_id: W, order_id: "ord-07", encounter_id: "enc-01", patient_id: "pt-01", drug_name: "Co-amoxiclav 1.2 g", dose: "1.2 g", route: "iv", scheduled_at: hrs(6), administered_at: hrs(6), administered_by: "Nurse Aisha Al-Dakhil", status: "given", hold_reason: null, site: "Right cannula", witnessed_by: "Dr. Hala Al-Rasheed", metadata: { observed_30_min: true, note: "Given under observation — documented penicillin allergy overridden" }, created_at: hrs(6), updated_at: hrs(6) },
  { id: "mar-05", workspace_id: W, order_id: "ord-08", encounter_id: "enc-06", patient_id: "pt-06", drug_name: "Meropenem 1 g", dose: "1 g", route: "iv", scheduled_at: hrs(8), administered_at: hrs(8), administered_by: "Nurse Aisha Al-Dakhil", status: "given", hold_reason: null, site: "Central line", witnessed_by: null, metadata: {}, created_at: hrs(8), updated_at: hrs(8) },
  { id: "mar-06", workspace_id: W, order_id: "ord-08", encounter_id: "enc-06", patient_id: "pt-06", drug_name: "Meropenem 1 g", dose: "1 g", route: "iv", scheduled_at: hrs(0.5), administered_at: null, administered_by: null, status: "due", hold_reason: null, site: null, witnessed_by: null, metadata: {}, created_at: hrs(8), updated_at: hrs(8) },
  { id: "mar-07", workspace_id: W, order_id: "ord-15", encounter_id: "enc-02", patient_id: "pt-02", drug_name: "Paracetamol 1 g", dose: "1000 mg", route: "oral", scheduled_at: hrs(6), administered_at: hrs(6), administered_by: "Nurse Sara Bin Ali", status: "given", hold_reason: null, site: null, witnessed_by: null, metadata: {}, created_at: hrs(26), updated_at: hrs(6) },
  { id: "mar-08", workspace_id: W, order_id: "ord-15", encounter_id: "enc-02", patient_id: "pt-02", drug_name: "Paracetamol 1 g", dose: "1000 mg", route: "oral", scheduled_at: hrs(12), administered_at: null, administered_by: null, status: "refused", hold_reason: "Patient declined — pain 2/10, preferred to wait", site: null, witnessed_by: null, metadata: {}, created_at: hrs(26), updated_at: hrs(12) },
  { id: "mar-09", workspace_id: W, order_id: "ord-18", encounter_id: "enc-05", patient_id: "pt-05", drug_name: "Salbutamol 2.5 mg neb", dose: "2.5 mg", route: "inhaled", scheduled_at: hrs(1), administered_at: hrs(1), administered_by: "Nurse Dana Al-Muhaisen", status: "given", hold_reason: null, site: null, witnessed_by: null, metadata: {}, created_at: hrs(5), updated_at: hrs(1) },
  { id: "mar-10", workspace_id: W, order_id: "ord-24", encounter_id: "enc-08", patient_id: "pt-08", drug_name: "Morphine 5 mg", dose: "5 mg", route: "iv", scheduled_at: hrs(8), administered_at: hrs(8), administered_by: "Nurse Sara Bin Ali", status: "given", hold_reason: null, site: "Left cannula", witnessed_by: "Nurse Hind Al-Otaibi", metadata: { controlled_register_entry: "CD-2026-0881" }, created_at: hrs(20), updated_at: hrs(8) },
  { id: "mar-11", workspace_id: W, order_id: "ord-09", encounter_id: "enc-06", patient_id: "pt-06", drug_name: "Noradrenaline infusion", dose: "0.06 mcg/kg/min", route: "iv", scheduled_at: hrs(1), administered_at: hrs(1), administered_by: "Nurse Aisha Al-Dakhil", status: "given", hold_reason: null, site: "Central line", witnessed_by: "Nurse Mona Al-Faraj", metadata: { high_alert: true, rate_change: "0.09 → 0.06" }, created_at: hrs(76), updated_at: hrs(1) },
  { id: "mar-12", workspace_id: W, order_id: "ord-19", encounter_id: "enc-05", patient_id: "pt-05", drug_name: "Prednisolone 24 mg", dose: "24 mg", route: "oral", scheduled_at: hrs(4), administered_at: null, administered_by: null, status: "missed", hold_reason: null, site: null, witnessed_by: null, metadata: { note: "Not signed within the 2-hour window — flagged to charge nurse" }, created_at: hrs(5), updated_at: hrs(2) },
];

// ─── Prescriptions (eRx) ──────────────────────────────────

export const DEMO_PRESCRIPTIONS: T<"prescriptions">[] = [
  { id: "rx-01", workspace_id: W, rx_number: "RX-2026-77120", patient_id: "pt-14", patient_name: "Saud Al-Amri", encounter_id: "enc-14", prescriber_id: "prov-02", prescriber_name: "Dr. Faisal Al-Harthy", drug_name_en: "Paracetamol", drug_name_ar: "باراسيتامول", atc_code: "N02BE01", strength: "500 mg", form: "tablet", dose: "1000 mg", route: "oral", frequency: "QDS PRN", duration_days: 7, quantity: 28, refills_allowed: 0, refills_used: 0, controlled_schedule: null, substitution_allowed: true, pharmacy_name: "Al-Madinah Outpatient Pharmacy", status: "dispensed", transmitted_at: hrs(26), dispensed_at: hrs(25), notes_en: "Take with food. Do not exceed 4 g in 24 hours.", notes_ar: "يؤخذ مع الطعام. لا يتجاوز ٤ غرام يومياً.", metadata: {}, created_at: hrs(27), updated_at: hrs(25) },
  { id: "rx-02", workspace_id: W, rx_number: "RX-2026-77121", patient_id: "pt-14", patient_name: "Saud Al-Amri", encounter_id: "enc-14", prescriber_id: "prov-02", prescriber_name: "Dr. Faisal Al-Harthy", drug_name_en: "Ibuprofen", drug_name_ar: "إيبوبروفين", atc_code: "M01AE01", strength: "400 mg", form: "tablet", dose: "400 mg", route: "oral", frequency: "TDS PRN", duration_days: 5, quantity: 15, refills_allowed: 0, refills_used: 0, controlled_schedule: null, substitution_allowed: true, pharmacy_name: "Al-Madinah Outpatient Pharmacy", status: "dispensed", transmitted_at: hrs(26), dispensed_at: hrs(25), notes_en: "Take after food.", notes_ar: "يؤخذ بعد الطعام.", metadata: {}, created_at: hrs(27), updated_at: hrs(25) },
  { id: "rx-03", workspace_id: W, rx_number: "RX-2026-77203", patient_id: "pt-03", patient_name: "Fatima Al-Harbi", encounter_id: "enc-03", prescriber_id: "prov-01", prescriber_name: "Dr. Hala Al-Rasheed", drug_name_en: "Linagliptin", drug_name_ar: "ليناغليبتين", atc_code: "A10BH05", strength: "5 mg", form: "tablet", dose: "5 mg", route: "oral", frequency: "OD", duration_days: 90, quantity: 90, refills_allowed: 2, refills_used: 0, controlled_schedule: null, substitution_allowed: false, pharmacy_name: "Al-Madinah Outpatient Pharmacy", status: "transmitted", transmitted_at: hrs(29), dispensed_at: null, notes_en: "Replaces metformin. No renal adjustment needed.", notes_ar: "بديل للميتفورمين ولا يحتاج تعديلاً كلوياً.", metadata: {}, created_at: hrs(30), updated_at: hrs(29) },
  { id: "rx-04", workspace_id: W, rx_number: "RX-2026-77244", patient_id: "pt-11", patient_name: "Layla Al-Anazi", encounter_id: "enc-11", prescriber_id: "prov-14", prescriber_name: "Dr. Lina Al-Yousef", drug_name_en: "Mometasone furoate", drug_name_ar: "موميتازون فيوروات", atc_code: "D07AC13", strength: "0.1%", form: "cream", dose: "Apply thinly", route: "topical", frequency: "OD", duration_days: 14, quantity: 1, refills_allowed: 1, refills_used: 0, controlled_schedule: null, substitution_allowed: true, pharmacy_name: "Community Pharmacy — Al Rabwah", status: "signed", transmitted_at: null, dispensed_at: null, notes_en: "Apply to affected areas only, avoid the face.", notes_ar: "يوضع على المناطق المصابة فقط مع تجنب الوجه.", metadata: {}, created_at: hrs(3), updated_at: hrs(3) },
  { id: "rx-05", workspace_id: W, rx_number: "RX-2026-77188", patient_id: "pt-07", patient_name: "Sara Al-Mutairi", encounter_id: "enc-07", prescriber_id: "prov-02", prescriber_name: "Dr. Faisal Al-Harthy", drug_name_en: "Chloramphenicol eye drops", drug_name_ar: "قطرة كلورامفينيكول للعين", atc_code: "S01AA01", strength: "0.5%", form: "drops", dose: "1 drop", route: "ophthalmic", frequency: "QDS", duration_days: 7, quantity: 1, refills_allowed: 0, refills_used: 0, controlled_schedule: null, substitution_allowed: true, pharmacy_name: "Al-Madinah Outpatient Pharmacy", status: "dispensed", transmitted_at: hrs(27), dispensed_at: hrs(26), notes_en: "Right eye. Discard 28 days after opening.", notes_ar: "العين اليمنى. يُتخلص منها بعد ٢٨ يوماً من الفتح.", metadata: {}, created_at: hrs(27), updated_at: hrs(26) },
  { id: "rx-06", workspace_id: W, rx_number: "RX-2026-77260", patient_id: "pt-13", patient_name: "Reem Al-Faisal", encounter_id: "enc-13", prescriber_id: "prov-04", prescriber_name: "Dr. Maha Al-Sanea", drug_name_en: "Levothyroxine", drug_name_ar: "ليفوثيروكسين", atc_code: "H03AA01", strength: "75 mcg", form: "tablet", dose: "75 mcg", route: "oral", frequency: "OD", duration_days: 90, quantity: 90, refills_allowed: 3, refills_used: 1, controlled_schedule: null, substitution_allowed: false, pharmacy_name: "Al-Madinah Outpatient Pharmacy", status: "cancelled", transmitted_at: null, dispensed_at: null, notes_en: "Cancelled — prescriber's licence lapsed at the point of signing. Reissued by Dr. Hala Al-Rasheed.", notes_ar: "أُلغيت لانتهاء رخصة الطبيب وقت التوقيع. أُعيد إصدارها من د. هالة الرشيد.", metadata: { blocked_by: "credential_check" }, created_at: hrs(47), updated_at: hrs(46) },
  { id: "rx-07", workspace_id: W, rx_number: "RX-2026-77261", patient_id: "pt-13", patient_name: "Reem Al-Faisal", encounter_id: "enc-13", prescriber_id: "prov-01", prescriber_name: "Dr. Hala Al-Rasheed", drug_name_en: "Levothyroxine", drug_name_ar: "ليفوثيروكسين", atc_code: "H03AA01", strength: "75 mcg", form: "tablet", dose: "75 mcg", route: "oral", frequency: "OD", duration_days: 90, quantity: 90, refills_allowed: 3, refills_used: 0, controlled_schedule: null, substitution_allowed: false, pharmacy_name: "Al-Madinah Outpatient Pharmacy", status: "dispensed", transmitted_at: hrs(46), dispensed_at: hrs(45), notes_en: "Take on an empty stomach, 30 minutes before breakfast.", notes_ar: "يؤخذ على معدة فارغة قبل الإفطار بثلاثين دقيقة.", metadata: {}, created_at: hrs(46), updated_at: hrs(45) },
  { id: "rx-08", workspace_id: W, rx_number: "RX-2026-77275", patient_id: "pt-05", patient_name: "Yousef Al-Dosari", encounter_id: "enc-05", prescriber_id: "prov-08", prescriber_name: "Dr. Rana Al-Suwailem", drug_name_en: "Salbutamol inhaler", drug_name_ar: "بخاخ سالبوتامول", atc_code: "R03AC02", strength: "100 mcg/dose", form: "inhaler", dose: "2 puffs", route: "inhaled", frequency: "QDS PRN", duration_days: 30, quantity: 1, refills_allowed: 2, refills_used: 0, controlled_schedule: null, substitution_allowed: true, pharmacy_name: "Al-Madinah Outpatient Pharmacy", status: "draft", transmitted_at: null, dispensed_at: null, notes_en: "With spacer. Technique to be checked before discharge.", notes_ar: "مع الفاصل. يجب مراجعة تقنية الاستخدام قبل الخروج.", metadata: {}, created_at: hrs(1), updated_at: hrs(1) },
];

// ─── CDSS alerts ──────────────────────────────────────────

export const DEMO_CDSS_ALERTS: T<"cdss_alerts">[] = [
  { id: "alert-01", workspace_id: W, patient_id: "pt-01", encounter_id: "enc-01", order_id: "ord-07", alert_type: "allergy", severity: "high", title_en: "Documented penicillin allergy", title_ar: "حساسية موثقة من البنسلين", message_en: "Co-amoxiclav contains amoxicillin, the same class as the recorded penicillin allergy. Reaction on record: widespread maculopapular rash (moderate).", message_ar: "كو-أموكسيكلاف يحتوي على أموكسيسيلين من نفس فئة البنسلين المسجل. رد الفعل المسجل: طفح جلدي منتشر (متوسط).", evidence: { allergy_id: "alg-01", substance: "Penicillin", match: "class" }, recommendation_en: "Confirm the reaction history. If the reaction was a delayed rash without airway involvement, a penicillin may still be appropriate with observation.", recommendation_ar: "أكد تاريخ رد الفعل. إذا كان طفحاً متأخراً دون تأثير على المجرى التنفسي فقد يكون البنسلين مناسباً مع المراقبة.", status: "overridden", fired_at: hrs(6), responded_at: hrs(6), responded_by: "Dr. Hala Al-Rasheed", override_reason: "Delayed rash only, no airway involvement. Discussed with microbiology. First dose under observation with rescue drugs at the bedside.", rule_id: "allergy:alg-01", metadata: {}, created_at: hrs(6), updated_at: hrs(6) },
  { id: "alert-02", workspace_id: W, patient_id: "pt-12", encounter_id: "enc-12", order_id: "ord-23", alert_type: "allergy", severity: "contraindicated", title_en: "Severe aspirin allergy — bronchospasm", title_ar: "حساسية شديدة من الأسبرين — تشنج قصبي", message_en: "Aspirin is the exact substance on the allergy record. Documented reaction: bronchospasm (severe). The patient is currently being treated for an acute COPD exacerbation.", message_ar: "الأسبرين هو نفس المادة المسجلة في سجل الحساسية. رد الفعل الموثق: تشنج قصبي (شديد). المريض يُعالج حالياً من نوبة انسداد رئوي حادة.", evidence: { allergy_id: "alg-05", substance: "Aspirin", match: "exact", current_spo2: 91 }, recommendation_en: "Do not proceed. Use clopidogrel if antiplatelet therapy is indicated.", recommendation_ar: "لا تكمل. استخدم كلوبيدوجريل إذا كان العلاج المضاد للصفيحات ضرورياً.", status: "active", fired_at: mins(28), responded_at: null, responded_by: null, override_reason: null, rule_id: "allergy:alg-05", metadata: {}, created_at: mins(28), updated_at: mins(28) },
  { id: "alert-03", workspace_id: W, patient_id: "pt-03", encounter_id: "enc-03", order_id: "ord-12", alert_type: "renal_dosing", severity: "high", title_en: "Metformin contraindicated at this eGFR", title_ar: "الميتفورمين ممنوع عند هذا المعدل", message_en: "eGFR is 26 mL/min/1.73m², below the threshold of 30 for metformin. Continued use raises the risk of lactic acidosis.", message_ar: "معدل الترشيح ٢٦ وهو أقل من حد ٣٠ للميتفورمين. الاستمرار يرفع خطر الحماض اللبني.", evidence: { drug: "metformin", egfr: 26, threshold: 30, previous_egfr: 34 }, recommendation_en: "Stop metformin. A DPP-4 inhibitor such as linagliptin needs no renal adjustment.", recommendation_ar: "أوقف الميتفورمين. مثبط DPP-4 مثل ليناغليبتين لا يحتاج تعديلاً كلوياً.", status: "resolved", fired_at: hrs(30), responded_at: hrs(30), responded_by: "Dr. Hala Al-Rasheed", override_reason: null, rule_id: "renal:metformin", metadata: { action_taken: "Order cancelled, linagliptin started" }, created_at: hrs(30), updated_at: hrs(30) },
  { id: "alert-04", workspace_id: W, patient_id: "pt-06", encounter_id: "enc-06", order_id: null, alert_type: "critical_lab", severity: "high", title_en: "Critical potassium", title_ar: "بوتاسيوم حرج", message_en: "Potassium is 6.4 mmol/L — above the critical threshold of 6.2. Last value 5.1 six hours ago.", message_ar: "البوتاسيوم ٦٫٤ مليمول/لتر وهو فوق الحد الحرج ٦٫٢. القيمة السابقة ٥٫١ قبل ست ساعات.", evidence: { analyte: "Potassium", value: 6.4, critical_high: 6.2, trend: "rising", aki_stage: 2 }, recommendation_en: "Repeat urgently, 12-lead ECG, and treat before the repeat returns. Review all potassium-sparing agents.", recommendation_ar: "أعد الفحص عاجلاً مع تخطيط قلب وابدأ العلاج قبل عودة النتيجة. راجع كل الأدوية الحافظة للبوتاسيوم.", status: "acknowledged", fired_at: hrs(5), responded_at: hrs(5), responded_by: "Dr. Omar Bin Salem", override_reason: null, rule_id: "critical_lab:potassium", metadata: { notified_by: "phone", notified_at_minutes: 4 }, created_at: hrs(5), updated_at: hrs(5) },
  { id: "alert-05", workspace_id: W, patient_id: "pt-12", encounter_id: "enc-12", order_id: null, alert_type: "deterioration", severity: "high", title_en: "NEWS2 7 — high risk", title_ar: "مؤشر الإنذار المبكر ٧ — خطورة عالية", message_en: "Aggregate NEWS2 is 7 with SpO₂ 88% on oxygen and a respiratory rate of 30. This meets the threshold for emergency assessment.", message_ar: "مجموع مؤشر الإنذار المبكر ٧ مع تشبع ٨٨٪ على الأكسجين ومعدل تنفس ٣٠. هذا يستوفي حد التقييم الطارئ.", evidence: { news2: 7, spo2: 88, rr: 30, on_oxygen: true }, recommendation_en: "Emergency assessment by the critical care outreach team. Consider non-invasive ventilation.", recommendation_ar: "تقييم طارئ من فريق العناية المركزة الميداني مع دراسة التنفس غير الغازي.", status: "acknowledged", fired_at: mins(78), responded_at: mins(72), responded_by: "Dr. Nasser Al-Juhani", override_reason: null, rule_id: "deterioration:news2", metadata: { escalated_to: "Critical Care Outreach" }, created_at: mins(78), updated_at: mins(72) },
  { id: "alert-06", workspace_id: W, patient_id: "pt-09", encounter_id: "enc-09", order_id: null, alert_type: "allergy", severity: "moderate", title_en: "Contrast allergy on record", title_ar: "حساسية موثقة من الصبغة", message_en: "Iodinated contrast allergy recorded — urticaria within 20 minutes. A contrast-enhanced CT is scheduled for restaging.", message_ar: "حساسية موثقة من الصبغة اليودية مع شرى خلال ٢٠ دقيقة. توجد أشعة مقطعية بالصبغة مجدولة لإعادة التقييم.", evidence: { allergy_id: "alg-04", upcoming_study: "img-05" }, recommendation_en: "Apply the premedication protocol: prednisolone at 13, 7 and 1 hours pre-scan, plus chlorphenamine.", recommendation_ar: "طبّق بروتوكول التحضير الدوائي: بريدنيزولون قبل ١٣ و٧ وساعة واحدة من الفحص مع كلورفينامين.", status: "acknowledged", fired_at: hrs(7), responded_at: hrs(7), responded_by: "Dr. Ziad Al-Mansour", override_reason: null, rule_id: "allergy:alg-04", metadata: { premedication_ordered: true }, created_at: hrs(7), updated_at: hrs(7) },
  { id: "alert-07", workspace_id: W, patient_id: "pt-01", encounter_id: "enc-01", order_id: "ord-01", alert_type: "duplicate_therapy", severity: "moderate", title_en: "Two antiplatelet agents active", title_ar: "دواءان مضادان للصفيحات نشطان", message_en: "Aspirin and clopidogrel are both active. This is expected as dual antiplatelet therapy after an acute coronary syndrome.", message_ar: "الأسبرين والكلوبيدوجريل نشطان معاً، وهو المتوقع كعلاج مزدوج مضاد للصفيحات بعد المتلازمة التاجية.", evidence: { drugs: ["Aspirin", "Clopidogrel"], indication: "NSTEMI" }, recommendation_en: "No action needed if DAPT is intended. Confirm the planned duration and add gastroprotection.", recommendation_ar: "لا يلزم إجراء إذا كان العلاج المزدوج مقصوداً. أكد المدة المخططة وأضف واقياً للمعدة.", status: "acknowledged", fired_at: hrs(11), responded_at: hrs(11), responded_by: "Dr. Nasser Al-Juhani", override_reason: null, rule_id: "duplicate:ord-02", metadata: { expected: true }, created_at: hrs(11), updated_at: hrs(11) },
  { id: "alert-08", workspace_id: W, patient_id: "pt-06", encounter_id: "enc-06", order_id: null, alert_type: "sepsis", severity: "high", title_en: "qSOFA positive on admission", title_ar: "مؤشر qSOFA إيجابي عند الدخول", message_en: "All three qSOFA criteria met at presentation: respiratory rate 28, altered mentation, systolic BP 84.", message_ar: "استوفى المريض معايير qSOFA الثلاثة عند الحضور: معدل تنفس ٢٨، تغير في الوعي، ضغط انقباضي ٨٤.", evidence: { qsofa: 3, rr: 28, sbp: 84, mentation: "voice" }, recommendation_en: "Sepsis Six within one hour: cultures, lactate, antibiotics, fluids, oxygen, urine output.", recommendation_ar: "حزمة الإنتان الستة خلال ساعة: مزارع، لاكتات، مضادات حيوية، سوائل، أكسجين، مراقبة إدرار البول.", status: "resolved", fired_at: hrs(76), responded_at: hrs(76), responded_by: "Dr. Omar Bin Salem", override_reason: null, rule_id: "sepsis:qsofa", metadata: { bundle_completed_minutes: 41 }, created_at: hrs(76), updated_at: hrs(70) },
];

// ─── Laboratory ───────────────────────────────────────────

export const DEMO_LAB_ORDERS: T<"lab_orders">[] = [
  { id: "lab-01", workspace_id: W, accession_number: "LAB-2026-330891", order_id: "ord-05", encounter_id: "enc-01", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", patient_mrn: "MRN-100241", panel_en: "Troponin T (0 h)", panel_ar: "تروبونين T (صفر ساعة)", loinc_code: "6598-7", discipline: "chemistry", specimen_type: "serum", container: "Gold SST", priority: "stat", status: "verified", rejection_reason: null, ordered_by: "Dr. Nasser Al-Juhani", ordered_at: hrs(11), collected_at: hrs(10.8), collected_by: "Phlebotomist Ahmed Al-Sultan", received_at: hrs(10.6), resulted_at: hrs(10.1), verified_at: hrs(10), verified_by: "Dr. Salma Al-Hazmi", tat_minutes: 60, has_critical_result: false, metadata: {}, created_at: hrs(11), updated_at: hrs(10) },
  { id: "lab-02", workspace_id: W, accession_number: "LAB-2026-331044", order_id: "ord-05", encounter_id: "enc-01", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", patient_mrn: "MRN-100241", panel_en: "Troponin T (6 h)", panel_ar: "تروبونين T (٦ ساعات)", loinc_code: "6598-7", discipline: "chemistry", specimen_type: "serum", container: "Gold SST", priority: "stat", status: "verified", rejection_reason: null, ordered_by: "Dr. Hala Al-Rasheed", ordered_at: hrs(5), collected_at: hrs(4.8), collected_by: "Nurse Aisha Al-Dakhil", received_at: hrs(4.6), resulted_at: hrs(4.1), verified_at: hrs(4), verified_by: "Dr. Salma Al-Hazmi", tat_minutes: 60, has_critical_result: false, metadata: {}, created_at: hrs(5), updated_at: hrs(4) },
  { id: "lab-03", workspace_id: W, accession_number: "LAB-2026-331188", order_id: "ord-05", encounter_id: "enc-01", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", patient_mrn: "MRN-100241", panel_en: "Troponin T (12 h)", panel_ar: "تروبونين T (١٢ ساعة)", loinc_code: "6598-7", discipline: "chemistry", specimen_type: "serum", container: "Gold SST", priority: "stat", status: "collected", rejection_reason: null, ordered_by: "Dr. Hala Al-Rasheed", ordered_at: hrs(1), collected_at: mins(20), collected_by: "Nurse Aisha Al-Dakhil", received_at: null, resulted_at: null, verified_at: null, verified_by: null, tat_minutes: null, has_critical_result: false, metadata: {}, created_at: hrs(1), updated_at: mins(20) },
  { id: "lab-04", workspace_id: W, accession_number: "LAB-2026-330612", order_id: null, encounter_id: "enc-06", patient_id: "pt-06", patient_name: "Abdullah Al-Shehri", patient_mrn: "MRN-100677", panel_en: "Urea & Electrolytes", panel_ar: "اليوريا والأملاح", loinc_code: "24362-6", discipline: "chemistry", specimen_type: "serum", container: "Gold SST", priority: "urgent", status: "verified", rejection_reason: null, ordered_by: "Dr. Omar Bin Salem", ordered_at: hrs(6), collected_at: hrs(5.8), collected_by: "Nurse Aisha Al-Dakhil", received_at: hrs(5.6), resulted_at: hrs(5.2), verified_at: hrs(5), verified_by: "Dr. Salma Al-Hazmi", tat_minutes: 60, has_critical_result: true, metadata: {}, created_at: hrs(6), updated_at: hrs(5) },
  { id: "lab-05", workspace_id: W, accession_number: "LAB-2026-330344", order_id: null, encounter_id: "enc-06", patient_id: "pt-06", patient_name: "Abdullah Al-Shehri", patient_mrn: "MRN-100677", panel_en: "Blood culture, aerobic & anaerobic", panel_ar: "مزرعة دم هوائية ولاهوائية", loinc_code: "600-7", discipline: "microbiology", specimen_type: "blood", container: "BacT/ALERT pair", priority: "urgent", status: "verified", rejection_reason: null, ordered_by: "Dr. Omar Bin Salem", ordered_at: hrs(76), collected_at: hrs(75.5), collected_by: "Nurse Aisha Al-Dakhil", received_at: hrs(75), resulted_at: hrs(28), verified_at: hrs(26), verified_by: "Dr. Salma Al-Hazmi", tat_minutes: 3000, has_critical_result: true, metadata: { organism: "Escherichia coli" }, created_at: hrs(76), updated_at: hrs(26) },
  { id: "lab-06", workspace_id: W, accession_number: "LAB-2026-331201", order_id: "ord-14", encounter_id: "enc-03", patient_id: "pt-03", patient_name: "Fatima Al-Harbi", patient_mrn: "MRN-100455", panel_en: "Renal profile & eGFR", panel_ar: "وظائف الكلى ومعدل الترشيح", loinc_code: "24362-6", discipline: "chemistry", specimen_type: "serum", container: "Gold SST", priority: "routine", status: "verified", rejection_reason: null, ordered_by: "Dr. Hala Al-Rasheed", ordered_at: hrs(31), collected_at: hrs(30.8), collected_by: "Phlebotomist Ahmed Al-Sultan", received_at: hrs(30.5), resulted_at: hrs(29.5), verified_at: hrs(29), verified_by: "Dr. Salma Al-Hazmi", tat_minutes: 120, has_critical_result: false, metadata: {}, created_at: hrs(31), updated_at: hrs(29) },
  { id: "lab-07", workspace_id: W, accession_number: "LAB-2026-331255", order_id: null, encounter_id: "enc-12", patient_id: "pt-12", patient_name: "Turki Al-Malki", patient_mrn: "MRN-101208", panel_en: "Arterial blood gas", panel_ar: "غازات الدم الشرياني", loinc_code: "24336-0", discipline: "chemistry", specimen_type: "blood", container: "Heparinised syringe", priority: "stat", status: "resulted", rejection_reason: null, ordered_by: "Dr. Nasser Al-Juhani", ordered_at: mins(70), collected_at: mins(66), collected_by: "Dr. Nasser Al-Juhani", received_at: mins(64), resulted_at: mins(58), verified_at: null, verified_by: null, tat_minutes: null, has_critical_result: false, metadata: {}, created_at: mins(70), updated_at: mins(58) },
  { id: "lab-08", workspace_id: W, accession_number: "LAB-2026-331002", order_id: "ord-25", encounter_id: "enc-08", patient_id: "pt-08", patient_name: "Ibrahim Al-Zahrani", patient_mrn: "MRN-100822", panel_en: "Group & save", panel_ar: "فصيلة الدم والحفظ", loinc_code: "882-1", discipline: "blood_bank", specimen_type: "blood", container: "EDTA pink", priority: "urgent", status: "verified", rejection_reason: null, ordered_by: "Dr. Bandar Al-Otaibi", ordered_at: hrs(19), collected_at: hrs(18.5), collected_by: "Nurse Sara Bin Ali", received_at: hrs(18), resulted_at: hrs(16.5), verified_at: hrs(16), verified_by: "Dr. Salma Al-Hazmi", tat_minutes: 180, has_critical_result: false, metadata: { group: "O+", antibody_screen: "negative" }, created_at: hrs(19), updated_at: hrs(16) },
  { id: "lab-09", workspace_id: W, accession_number: "LAB-2026-331277", order_id: null, encounter_id: "enc-09", patient_id: "pt-09", patient_name: "Hessa Al-Subaie", patient_mrn: "MRN-100901", panel_en: "Full blood count", panel_ar: "صورة دم كاملة", loinc_code: "58410-2", discipline: "haematology", specimen_type: "blood", container: "EDTA purple", priority: "routine", status: "verified", rejection_reason: null, ordered_by: "Dr. Ziad Al-Mansour", ordered_at: hrs(8), collected_at: hrs(7.8), collected_by: "Nurse Nouf Al-Ajmi", received_at: hrs(7.5), resulted_at: hrs(7.1), verified_at: hrs(7), verified_by: "Dr. Salma Al-Hazmi", tat_minutes: 60, has_critical_result: false, metadata: { note: "Pre-chemotherapy check — counts adequate to proceed" }, created_at: hrs(8), updated_at: hrs(7) },
  { id: "lab-10", workspace_id: W, accession_number: "LAB-2026-331290", order_id: null, encounter_id: "enc-02", patient_id: "pt-02", patient_name: "Maryam Al-Ghamdi", patient_mrn: "MRN-100388", panel_en: "Liver function tests", panel_ar: "وظائف الكبد", loinc_code: "24325-3", discipline: "chemistry", specimen_type: "serum", container: "Gold SST", priority: "routine", status: "rejected", rejection_reason: "Haemolysed sample — potassium and LDH unreliable. Recollection requested.", ordered_by: "Dr. Faisal Al-Harthy", ordered_at: hrs(10), collected_at: hrs(9.5), collected_by: "Phlebotomist Ahmed Al-Sultan", received_at: hrs(9), resulted_at: null, verified_at: null, verified_by: null, tat_minutes: null, has_critical_result: false, metadata: {}, created_at: hrs(10), updated_at: hrs(9) },
  { id: "lab-11", workspace_id: W, accession_number: "LAB-2026-331301", order_id: "ord-11", encounter_id: "enc-06", patient_id: "pt-06", patient_name: "Abdullah Al-Shehri", patient_mrn: "MRN-100677", panel_en: "Arterial blood gas", panel_ar: "غازات الدم الشرياني", loinc_code: "24336-0", discipline: "chemistry", specimen_type: "blood", container: "Heparinised syringe", priority: "urgent", status: "in_progress", rejection_reason: null, ordered_by: "Dr. Omar Bin Salem", ordered_at: mins(45), collected_at: mins(40), collected_by: "Nurse Aisha Al-Dakhil", received_at: mins(36), resulted_at: null, verified_at: null, verified_by: null, tat_minutes: null, has_critical_result: false, metadata: {}, created_at: mins(45), updated_at: mins(36) },
  { id: "lab-12", workspace_id: W, accession_number: "LAB-2026-331310", order_id: null, encounter_id: "enc-05", patient_id: "pt-05", patient_name: "Yousef Al-Dosari", patient_mrn: "MRN-100603", panel_en: "Capillary blood gas", panel_ar: "غازات الدم الشعرية", loinc_code: "24337-8", discipline: "chemistry", specimen_type: "blood", container: "Capillary tube", priority: "urgent", status: "ordered", rejection_reason: null, ordered_by: "Dr. Rana Al-Suwailem", ordered_at: mins(15), collected_at: null, collected_by: null, received_at: null, resulted_at: null, verified_at: null, verified_by: null, tat_minutes: null, has_critical_result: false, metadata: {}, created_at: mins(15), updated_at: mins(15) },
];

export const DEMO_LAB_RESULTS: T<"lab_results">[] = [
  { id: "res-01", workspace_id: W, lab_order_id: "lab-01", patient_id: "pt-01", analyte_en: "Troponin T", analyte_ar: "تروبونين T", loinc_code: "6598-7", value: "412", value_numeric: 412, unit: "ng/L", reference_low: null, reference_high: 14, reference_text: "< 14 ng/L", flag: "high", critical_notified_at: null, critical_notified_to: null, method: "ECLIA", instrument: "Cobas e801", resulted_at: hrs(10.1), metadata: {}, created_at: hrs(10.1), updated_at: hrs(10) },
  { id: "res-02", workspace_id: W, lab_order_id: "lab-02", patient_id: "pt-01", analyte_en: "Troponin T", analyte_ar: "تروبونين T", loinc_code: "6598-7", value: "890", value_numeric: 890, unit: "ng/L", reference_low: null, reference_high: 14, reference_text: "< 14 ng/L", flag: "high", critical_notified_at: hrs(4), critical_notified_to: "Dr. Hala Al-Rasheed", method: "ECLIA", instrument: "Cobas e801", resulted_at: hrs(4.1), metadata: { delta: "+478 over 6 h — rising pattern consistent with myocardial infarction" }, created_at: hrs(4.1), updated_at: hrs(4) },
  { id: "res-03", workspace_id: W, lab_order_id: "lab-04", patient_id: "pt-06", analyte_en: "Potassium", analyte_ar: "البوتاسيوم", loinc_code: "2823-3", value: "6.4", value_numeric: 6.4, unit: "mmol/L", reference_low: 3.5, reference_high: 5.1, reference_text: "3.5–5.1", flag: "critical_high", critical_notified_at: hrs(4.9), critical_notified_to: "Dr. Omar Bin Salem", method: "ISE", instrument: "Cobas c702", resulted_at: hrs(5.2), metadata: { notified_within_minutes: 4 }, created_at: hrs(5.2), updated_at: hrs(4.9) },
  { id: "res-04", workspace_id: W, lab_order_id: "lab-04", patient_id: "pt-06", analyte_en: "Creatinine", analyte_ar: "الكرياتينين", loinc_code: "2160-0", value: "186", value_numeric: 186, unit: "µmol/L", reference_low: 62, reference_high: 106, reference_text: "62–106", flag: "high", critical_notified_at: null, critical_notified_to: null, method: "Enzymatic", instrument: "Cobas c702", resulted_at: hrs(5.2), metadata: { egfr: 34, baseline: 96 }, created_at: hrs(5.2), updated_at: hrs(5) },
  { id: "res-05", workspace_id: W, lab_order_id: "lab-04", patient_id: "pt-06", analyte_en: "Sodium", analyte_ar: "الصوديوم", loinc_code: "2951-2", value: "134", value_numeric: 134, unit: "mmol/L", reference_low: 136, reference_high: 145, reference_text: "136–145", flag: "low", critical_notified_at: null, critical_notified_to: null, method: "ISE", instrument: "Cobas c702", resulted_at: hrs(5.2), metadata: {}, created_at: hrs(5.2), updated_at: hrs(5) },
  { id: "res-06", workspace_id: W, lab_order_id: "lab-05", patient_id: "pt-06", analyte_en: "Blood culture organism", analyte_ar: "الكائن الدقيق في مزرعة الدم", loinc_code: "600-7", value: "Escherichia coli — sensitive to meropenem, ceftriaxone, gentamicin. Resistant to co-amoxiclav and ciprofloxacin.", value_numeric: null, unit: null, reference_low: null, reference_high: null, reference_text: "No growth", flag: "abnormal", critical_notified_at: hrs(27.5), critical_notified_to: "Dr. Omar Bin Salem", method: "MALDI-TOF", instrument: "BacT/ALERT VIRTUO", resulted_at: hrs(28), metadata: { time_to_positivity_hours: 11 }, created_at: hrs(28), updated_at: hrs(26) },
  { id: "res-07", workspace_id: W, lab_order_id: "lab-06", patient_id: "pt-03", analyte_en: "Creatinine", analyte_ar: "الكرياتينين", loinc_code: "2160-0", value: "198", value_numeric: 198, unit: "µmol/L", reference_low: 49, reference_high: 90, reference_text: "49–90", flag: "high", critical_notified_at: null, critical_notified_to: null, method: "Enzymatic", instrument: "Cobas c702", resulted_at: hrs(29.5), metadata: { egfr: 26, previous_egfr: 34 }, created_at: hrs(29.5), updated_at: hrs(29) },
  { id: "res-08", workspace_id: W, lab_order_id: "lab-06", patient_id: "pt-03", analyte_en: "eGFR", analyte_ar: "معدل الترشيح الكبيبي", loinc_code: "62238-1", value: "26", value_numeric: 26, unit: "mL/min/1.73m²", reference_low: 90, reference_high: null, reference_text: "> 90", flag: "low", critical_notified_at: null, critical_notified_to: null, method: "CKD-EPI", instrument: "Calculated", resulted_at: hrs(29.5), metadata: { stage: "CKD 4" }, created_at: hrs(29.5), updated_at: hrs(29) },
  { id: "res-09", workspace_id: W, lab_order_id: "lab-06", patient_id: "pt-03", analyte_en: "HbA1c", analyte_ar: "الهيموغلوبين السكري", loinc_code: "4548-4", value: "8.4", value_numeric: 8.4, unit: "%", reference_low: null, reference_high: 6.5, reference_text: "< 6.5", flag: "high", critical_notified_at: null, critical_notified_to: null, method: "HPLC", instrument: "Variant II", resulted_at: hrs(29.5), metadata: { previous: 7.6 }, created_at: hrs(29.5), updated_at: hrs(29) },
  { id: "res-10", workspace_id: W, lab_order_id: "lab-07", patient_id: "pt-12", analyte_en: "pH", analyte_ar: "الأس الهيدروجيني", loinc_code: "2744-1", value: "7.31", value_numeric: 7.31, unit: "", reference_low: 7.35, reference_high: 7.45, reference_text: "7.35–7.45", flag: "low", critical_notified_at: null, critical_notified_to: null, method: "Blood gas analyser", instrument: "ABL90 FLEX", resulted_at: mins(58), metadata: {}, created_at: mins(58), updated_at: mins(58) },
  { id: "res-11", workspace_id: W, lab_order_id: "lab-07", patient_id: "pt-12", analyte_en: "pCO2", analyte_ar: "ضغط ثاني أكسيد الكربون", loinc_code: "2019-8", value: "7.8", value_numeric: 7.8, unit: "kPa", reference_low: 4.7, reference_high: 6.0, reference_text: "4.7–6.0", flag: "high", critical_notified_at: mins(56), critical_notified_to: "Dr. Nasser Al-Juhani", method: "Blood gas analyser", instrument: "ABL90 FLEX", resulted_at: mins(58), metadata: { interpretation: "Acute-on-chronic type 2 respiratory failure" }, created_at: mins(58), updated_at: mins(56) },
  { id: "res-12", workspace_id: W, lab_order_id: "lab-09", patient_id: "pt-09", analyte_en: "Haemoglobin", analyte_ar: "الهيموغلوبين", loinc_code: "718-7", value: "10.8", value_numeric: 10.8, unit: "g/dL", reference_low: 12.0, reference_high: 15.5, reference_text: "12.0–15.5", flag: "low", critical_notified_at: null, critical_notified_to: null, method: "Impedance", instrument: "Sysmex XN-1000", resulted_at: hrs(7.1), metadata: {}, created_at: hrs(7.1), updated_at: hrs(7) },
  { id: "res-13", workspace_id: W, lab_order_id: "lab-09", patient_id: "pt-09", analyte_en: "Neutrophils", analyte_ar: "العدلات", loinc_code: "751-8", value: "1.8", value_numeric: 1.8, unit: "10⁹/L", reference_low: 2.0, reference_high: 7.5, reference_text: "2.0–7.5", flag: "low", critical_notified_at: null, critical_notified_to: null, method: "Flow cytometry", instrument: "Sysmex XN-1000", resulted_at: hrs(7.1), metadata: { note: "Above the 1.5 threshold — chemotherapy may proceed" }, created_at: hrs(7.1), updated_at: hrs(7) },
  { id: "res-14", workspace_id: W, lab_order_id: "lab-09", patient_id: "pt-09", analyte_en: "Platelets", analyte_ar: "الصفائح الدموية", loinc_code: "777-3", value: "168", value_numeric: 168, unit: "10⁹/L", reference_low: 150, reference_high: 400, reference_text: "150–400", flag: "normal", critical_notified_at: null, critical_notified_to: null, method: "Impedance", instrument: "Sysmex XN-1000", resulted_at: hrs(7.1), metadata: {}, created_at: hrs(7.1), updated_at: hrs(7) },
];

// ─── Blood bank ───────────────────────────────────────────

export const DEMO_BLOOD_UNITS: T<"blood_units">[] = [
  { id: "bu-01", workspace_id: W, unit_number: "BU-2026-04112", blood_group: "O+", component: "prbc", volume_ml: 280, collected_at: ts(18), expires_at: inDays(17), status: "crossmatched", reserved_for_patient_id: "pt-08", reserved_for_patient_name: "Ibrahim Al-Zahrani", crossmatch_result: "compatible", issued_at: null, transfused_at: null, discard_reason: null, storage_location: "Fridge A, Shelf 2", donor_reference: "DNR-77120", screening_passed: true, metadata: {}, created_at: ts(18), updated_at: hrs(16) },
  { id: "bu-02", workspace_id: W, unit_number: "BU-2026-04113", blood_group: "O+", component: "prbc", volume_ml: 275, collected_at: ts(18), expires_at: inDays(17), status: "crossmatched", reserved_for_patient_id: "pt-08", reserved_for_patient_name: "Ibrahim Al-Zahrani", crossmatch_result: "compatible", issued_at: null, transfused_at: null, discard_reason: null, storage_location: "Fridge A, Shelf 2", donor_reference: "DNR-77121", screening_passed: true, metadata: {}, created_at: ts(18), updated_at: hrs(16) },
  { id: "bu-03", workspace_id: W, unit_number: "BU-2026-04088", blood_group: "O-", component: "prbc", volume_ml: 290, collected_at: ts(25), expires_at: inDays(10), status: "available", reserved_for_patient_id: null, reserved_for_patient_name: null, crossmatch_result: null, issued_at: null, transfused_at: null, discard_reason: null, storage_location: "Fridge A, Shelf 1 — Emergency O neg", donor_reference: "DNR-76988", screening_passed: true, metadata: { emergency_stock: true }, created_at: ts(25), updated_at: ts(25) },
  { id: "bu-04", workspace_id: W, unit_number: "BU-2026-04089", blood_group: "O-", component: "prbc", volume_ml: 285, collected_at: ts(25), expires_at: inDays(10), status: "available", reserved_for_patient_id: null, reserved_for_patient_name: null, crossmatch_result: null, issued_at: null, transfused_at: null, discard_reason: null, storage_location: "Fridge A, Shelf 1 — Emergency O neg", donor_reference: "DNR-76989", screening_passed: true, metadata: { emergency_stock: true }, created_at: ts(25), updated_at: ts(25) },
  { id: "bu-05", workspace_id: W, unit_number: "BU-2026-04155", blood_group: "A+", component: "prbc", volume_ml: 278, collected_at: ts(12), expires_at: inDays(23), status: "available", reserved_for_patient_id: null, reserved_for_patient_name: null, crossmatch_result: null, issued_at: null, transfused_at: null, discard_reason: null, storage_location: "Fridge A, Shelf 3", donor_reference: "DNR-77201", screening_passed: true, metadata: {}, created_at: ts(12), updated_at: ts(12) },
  { id: "bu-06", workspace_id: W, unit_number: "BU-2026-04161", blood_group: "AB+", component: "ffp", volume_ml: 250, collected_at: ts(40), expires_at: inDays(320), status: "available", reserved_for_patient_id: null, reserved_for_patient_name: null, crossmatch_result: null, issued_at: null, transfused_at: null, discard_reason: null, storage_location: "Freezer B, -30°C", donor_reference: "DNR-76540", screening_passed: true, metadata: { note: "AB plasma — universal for FFP" }, created_at: ts(40), updated_at: ts(40) },
  { id: "bu-07", workspace_id: W, unit_number: "BU-2026-04170", blood_group: "B+", component: "platelets", volume_ml: 200, collected_at: ts(3), expires_at: inDays(2), status: "available", reserved_for_patient_id: null, reserved_for_patient_name: null, crossmatch_result: null, issued_at: null, transfused_at: null, discard_reason: null, storage_location: "Agitator, 22°C", donor_reference: "DNR-77310", screening_passed: true, metadata: { expiry_warning: true }, created_at: ts(3), updated_at: ts(3) },
  { id: "bu-08", workspace_id: W, unit_number: "BU-2026-03998", blood_group: "A-", component: "prbc", volume_ml: 282, collected_at: ts(40), expires_at: ts(5), status: "expired", reserved_for_patient_id: null, reserved_for_patient_name: null, crossmatch_result: null, issued_at: null, transfused_at: null, discard_reason: "Reached 35-day shelf life without issue", storage_location: "Quarantine bin", donor_reference: "DNR-76201", screening_passed: true, metadata: {}, created_at: ts(40), updated_at: ts(5) },
  { id: "bu-09", workspace_id: W, unit_number: "BU-2026-04180", blood_group: "O+", component: "prbc", volume_ml: 276, collected_at: ts(1), expires_at: inDays(34), status: "quarantine", reserved_for_patient_id: null, reserved_for_patient_name: null, crossmatch_result: null, issued_at: null, transfused_at: null, discard_reason: null, storage_location: "Quarantine fridge", donor_reference: "DNR-77402", screening_passed: false, metadata: { pending: "Awaiting NAT screening result" }, created_at: ts(1), updated_at: ts(1) },
  { id: "bu-10", workspace_id: W, unit_number: "BU-2026-04101", blood_group: "A+", component: "prbc", volume_ml: 279, collected_at: ts(22), expires_at: inDays(13), status: "transfused", reserved_for_patient_id: "pt-09", reserved_for_patient_name: "Hessa Al-Subaie", crossmatch_result: "compatible", issued_at: ts(14), transfused_at: ts(14), discard_reason: null, storage_location: "Issued", donor_reference: "DNR-77050", screening_passed: true, metadata: { indication: "Chemotherapy-related anaemia, Hb 7.8" }, created_at: ts(22), updated_at: ts(14) },
];

// ─── Radiology (RIS) ──────────────────────────────────────

export const DEMO_IMAGING_ORDERS: T<"imaging_orders">[] = [
  { id: "img-01", workspace_id: W, accession_number: "RAD-2026-88120", order_id: null, encounter_id: "enc-01", patient_id: "pt-01", patient_name: "Khalid Al-Otaibi", patient_mrn: "MRN-100241", modality: "xr", procedure_en: "Chest X-ray, PA erect", procedure_ar: "أشعة صدر أمامية خلفية", body_part: "Chest", laterality: "na", contrast_required: false, priority: "urgent", status: "verified", scheduled_at: hrs(10.5), room: "XR-1", performed_at: hrs(10.2), technologist: "Tech. Faris Al-Otaibi", reported_at: hrs(7), radiologist: "Dr. Tariq Al-Balawi", report_en: "Right lower zone patchy consolidation consistent with aspiration. Heart size within normal limits. No pleural effusion or pneumothorax. Bony thorax intact.", report_ar: "تصلد بقعي في المنطقة السفلية اليمنى يتوافق مع الاستنشاق. حجم القلب ضمن الطبيعي. لا يوجد انصباب جنبي أو استرواح صدري. القفص الصدري سليم.", impression_en: "Right lower lobe aspiration pneumonia.", critical_finding: false, critical_notified_at: null, study_uid: "1.2.840.113619.2.55.3.2831164356.781.1", series_count: 1, image_count: 2, radiation_dose: 0.1, metadata: {}, created_at: hrs(11), updated_at: hrs(7) },
  { id: "img-02", workspace_id: W, accession_number: "RAD-2026-88245", order_id: "ord-22", encounter_id: "enc-12", patient_id: "pt-12", patient_name: "Turki Al-Malki", patient_mrn: "MRN-101208", modality: "xr", procedure_en: "Chest X-ray, PA erect", procedure_ar: "أشعة صدر أمامية خلفية", body_part: "Chest", laterality: "na", contrast_required: false, priority: "urgent", status: "acquired", scheduled_at: mins(45), room: "XR-2", performed_at: mins(30), technologist: "Tech. Nada Al-Harbi", reported_at: null, radiologist: null, report_en: null, report_ar: null, impression_en: null, critical_finding: false, critical_notified_at: null, study_uid: "1.2.840.113619.2.55.3.2831164356.902.4", series_count: 1, image_count: 2, radiation_dose: 0.1, metadata: {}, created_at: mins(65), updated_at: mins(30) },
  { id: "img-03", workspace_id: W, accession_number: "RAD-2026-88011", order_id: null, encounter_id: "enc-08", patient_id: "pt-08", patient_name: "Ibrahim Al-Zahrani", patient_mrn: "MRN-100822", modality: "xr", procedure_en: "Tibia and fibula, two views", procedure_ar: "أشعة الساق والشظية بمنظورين", body_part: "Lower leg", laterality: "left", contrast_required: false, priority: "urgent", status: "verified", scheduled_at: hrs(20.5), room: "XR-1", performed_at: hrs(20.2), technologist: "Tech. Faris Al-Otaibi", reported_at: hrs(19), radiologist: "Dr. Tariq Al-Balawi", report_en: "Transverse fracture of the mid-shaft of the left tibia with approximately 8 mm of lateral displacement. Intact fibula. No intra-articular extension. Soft tissue swelling without radiopaque foreign body.", report_ar: "كسر عرضي في منتصف جسم عظم الساق الأيسر مع إزاحة جانبية بحوالي ٨ ملم. الشظية سليمة. لا امتداد داخل المفصل. تورم في الأنسجة الرخوة دون جسم غريب ظليل.", impression_en: "Displaced transverse mid-shaft tibial fracture, left.", critical_finding: false, critical_notified_at: null, study_uid: "1.2.840.113619.2.55.3.2831164356.655.2", series_count: 2, image_count: 4, radiation_dose: 0.05, metadata: {}, created_at: hrs(21), updated_at: hrs(19) },
  { id: "img-04", workspace_id: W, accession_number: "RAD-2026-87904", order_id: null, encounter_id: "enc-06", patient_id: "pt-06", patient_name: "Abdullah Al-Shehri", patient_mrn: "MRN-100677", modality: "ct", procedure_en: "CT abdomen and pelvis with contrast", procedure_ar: "أشعة مقطعية للبطن والحوض بالصبغة", body_part: "Abdomen/Pelvis", laterality: "na", contrast_required: true, priority: "stat", status: "verified", scheduled_at: hrs(74), room: "CT-1", performed_at: hrs(73.5), technologist: "Tech. Sami Al-Ghamdi", reported_at: hrs(72), radiologist: "Dr. Tariq Al-Balawi", report_en: "Left-sided hydronephrosis with an obstructing 9 mm calculus at the vesicoureteric junction. Perinephric stranding and a thickened renal pelvis consistent with infection. No collection or gas. Right kidney unremarkable.", report_ar: "استسقاء كلوي أيسر مع حصوة انسدادية ٩ ملم عند ملتقى الحالب بالمثانة. تخطط حول الكلية وسماكة في حوض الكلية تتوافق مع الالتهاب. لا يوجد تجمع أو غازات. الكلية اليمنى طبيعية.", impression_en: "Obstructed infected left kidney — urological emergency.", critical_finding: true, critical_notified_at: hrs(72.2), study_uid: "1.2.840.113619.2.55.3.2831164356.401.9", series_count: 4, image_count: 612, radiation_dose: 480, metadata: { notified_to: "Dr. Omar Bin Salem", notified_within_minutes: 12 }, created_at: hrs(74), updated_at: hrs(72) },
  { id: "img-05", workspace_id: W, accession_number: "RAD-2026-88301", order_id: null, encounter_id: "enc-09", patient_id: "pt-09", patient_name: "Hessa Al-Subaie", patient_mrn: "MRN-100901", modality: "ct", procedure_en: "CT chest, abdomen and pelvis with contrast — restaging", procedure_ar: "أشعة مقطعية للصدر والبطن والحوض بالصبغة — إعادة تقييم", body_part: "Chest/Abdomen/Pelvis", laterality: "na", contrast_required: true, priority: "routine", status: "scheduled", scheduled_at: inHrs(52), room: "CT-2", performed_at: null, technologist: null, reported_at: null, radiologist: null, report_en: null, report_ar: null, impression_en: null, critical_finding: false, critical_notified_at: null, study_uid: null, series_count: null, image_count: null, radiation_dose: null, metadata: { contrast_allergy: true, premedication_required: true }, created_at: hrs(7), updated_at: hrs(7) },
  { id: "img-06", workspace_id: W, accession_number: "RAD-2026-88288", order_id: null, encounter_id: "enc-05", patient_id: "pt-05", patient_name: "Yousef Al-Dosari", patient_mrn: "MRN-100603", modality: "xr", procedure_en: "Chest X-ray, AP", procedure_ar: "أشعة صدر أمامية", body_part: "Chest", laterality: "na", contrast_required: false, priority: "routine", status: "reported", scheduled_at: hrs(4.5), room: "XR-2", performed_at: hrs(4.2), technologist: "Tech. Nada Al-Harbi", reported_at: hrs(3), radiologist: "Dr. Tariq Al-Balawi", report_en: "Hyperinflated lung fields consistent with air trapping. No focal consolidation, effusion or pneumothorax. Normal cardiothymic silhouette for age.", report_ar: "حقول رئوية مفرطة التمدد تتوافق مع احتباس الهواء. لا يوجد تصلد بؤري أو انصباب أو استرواح. ظل القلب والغدة الصعترية طبيعي للعمر.", impression_en: "Air trapping, no acute consolidation.", critical_finding: false, critical_notified_at: null, study_uid: "1.2.840.113619.2.55.3.2831164356.877.3", series_count: 1, image_count: 1, radiation_dose: 0.02, metadata: { paediatric_dose_protocol: true }, created_at: hrs(5), updated_at: hrs(3) },
  { id: "img-07", workspace_id: W, accession_number: "RAD-2026-88310", order_id: null, encounter_id: "enc-04", patient_id: "pt-04", patient_name: "Noura Al-Qahtani", patient_mrn: "MRN-100512", modality: "us", procedure_en: "Obstetric ultrasound, growth and presentation", procedure_ar: "سونار حمل لتقييم النمو والوضعية", body_part: "Gravid uterus", laterality: "na", contrast_required: false, priority: "routine", status: "verified", scheduled_at: hrs(13), room: "US-1", performed_at: hrs(12.8), technologist: "Sonographer Huda Al-Nasser", reported_at: hrs(12), radiologist: "Dr. Tariq Al-Balawi", report_en: "Single live intrauterine fetus in cephalic presentation. Estimated fetal weight 3,340 g, on the 58th centile. Amniotic fluid index 14 cm, within normal limits. Anterior placenta, well clear of the internal os. Umbilical artery Doppler normal.", report_ar: "جنين حي واحد داخل الرحم بوضعية رأسية. الوزن المقدر ٣٣٤٠ غرام عند المئين ٥٨. مؤشر السائل الأمنيوسي ١٤ سم ضمن الطبيعي. مشيمة أمامية بعيدة عن فوهة عنق الرحم. دوبلر الشريان السري طبيعي.", impression_en: "Appropriately grown cephalic fetus, normal liquor and Dopplers.", critical_finding: false, critical_notified_at: null, study_uid: "1.2.840.113619.2.55.3.2831164356.910.1", series_count: 1, image_count: 18, radiation_dose: null, metadata: {}, created_at: hrs(13), updated_at: hrs(12) },
  { id: "img-08", workspace_id: W, accession_number: "RAD-2026-88322", order_id: null, encounter_id: "enc-10", patient_id: "pt-10", patient_name: "Majed Al-Rashid", patient_mrn: "MRN-101034", modality: "xr", procedure_en: "Ankle, three views", procedure_ar: "أشعة الكاحل بثلاثة منظورات", body_part: "Ankle", laterality: "right", contrast_required: false, priority: "routine", status: "ordered", scheduled_at: null, room: null, performed_at: null, technologist: null, reported_at: null, radiologist: null, report_en: null, report_ar: null, impression_en: null, critical_finding: false, critical_notified_at: null, study_uid: null, series_count: null, image_count: null, radiation_dose: null, metadata: { ottawa_rules_positive: true }, created_at: mins(40), updated_at: mins(40) },
];

// ─── Pharmacy ─────────────────────────────────────────────

export const DEMO_PHARMACY_STOCK: T<"pharmacy_stock">[] = [
  { id: "ph-01", workspace_id: W, drug_code: "DRG-00101", name_en: "Paracetamol", name_ar: "باراسيتامول", generic_name: "Paracetamol", atc_code: "N02BE01", form: "Tablet", strength: "500 mg", batch_number: "PC-24118", expiry_date: inDays(420), quantity_on_hand: 8400, quantity_reserved: 320, reorder_level: 2000, unit: "tablet", unit_cost: 0.12, location: "Main store, A-12", controlled_schedule: null, high_alert: false, requires_refrigeration: false, supplier_name: "Tabuk Pharmaceuticals", status: "active", metadata: {}, created_at: ts(120), updated_at: ts(2) },
  { id: "ph-02", workspace_id: W, drug_code: "DRG-00204", name_en: "Morphine sulfate", name_ar: "كبريتات المورفين", generic_name: "Morphine", atc_code: "N02AA01", form: "Ampoule", strength: "10 mg/mL", batch_number: "MO-24009", expiry_date: inDays(280), quantity_on_hand: 148, quantity_reserved: 12, reorder_level: 60, unit: "ampoule", unit_cost: 4.80, location: "CD cupboard, safe 1", controlled_schedule: "CD2", high_alert: true, requires_refrigeration: false, supplier_name: "SPIMACO", status: "active", metadata: { register: "CD-2026" }, created_at: ts(120), updated_at: hrs(8) },
  { id: "ph-03", workspace_id: W, drug_code: "DRG-00318", name_en: "Meropenem", name_ar: "ميروبينيم", generic_name: "Meropenem", atc_code: "J01DH02", form: "Vial", strength: "1 g", batch_number: "MP-24552", expiry_date: inDays(180), quantity_on_hand: 92, quantity_reserved: 21, reorder_level: 40, unit: "vial", unit_cost: 38.50, location: "Main store, C-04", controlled_schedule: null, high_alert: false, requires_refrigeration: false, supplier_name: "Jamjoom Pharma", status: "active", metadata: { restricted: "Microbiology approval required" }, created_at: ts(90), updated_at: hrs(8) },
  { id: "ph-04", workspace_id: W, drug_code: "DRG-00422", name_en: "Enoxaparin", name_ar: "إينوكسابارين", generic_name: "Enoxaparin sodium", atc_code: "B01AB05", form: "Pre-filled syringe", strength: "100 mg/mL", batch_number: "EN-24771", expiry_date: inDays(310), quantity_on_hand: 214, quantity_reserved: 18, reorder_level: 80, unit: "syringe", unit_cost: 22.40, location: "Fridge P-2", controlled_schedule: null, high_alert: true, requires_refrigeration: true, supplier_name: "Sanofi", status: "active", metadata: {}, created_at: ts(75), updated_at: hrs(9) },
  { id: "ph-05", workspace_id: W, drug_code: "DRG-00530", name_en: "Salbutamol nebuliser solution", name_ar: "محلول سالبوتامول للبخاخ", generic_name: "Salbutamol", atc_code: "R03AC02", form: "Nebule", strength: "2.5 mg/2.5 mL", batch_number: "SB-24330", expiry_date: inDays(95), quantity_on_hand: 640, quantity_reserved: 44, reorder_level: 200, unit: "nebule", unit_cost: 1.35, location: "Main store, B-08", controlled_schedule: null, high_alert: false, requires_refrigeration: false, supplier_name: "GSK", status: "active", metadata: {}, created_at: ts(60), updated_at: hrs(1) },
  { id: "ph-06", workspace_id: W, drug_code: "DRG-00641", name_en: "Oxaliplatin", name_ar: "أوكزاليبلاتين", generic_name: "Oxaliplatin", atc_code: "L01XA03", form: "Vial", strength: "100 mg/20 mL", batch_number: "OX-24118", expiry_date: inDays(240), quantity_on_hand: 18, quantity_reserved: 4, reorder_level: 10, unit: "vial", unit_cost: 620.00, location: "Cytotoxic store, locked", controlled_schedule: null, high_alert: true, requires_refrigeration: true, supplier_name: "Accord Healthcare", status: "active", metadata: { cytotoxic: true, requires_isolator: true }, created_at: ts(45), updated_at: hrs(6) },
  { id: "ph-07", workspace_id: W, drug_code: "DRG-00755", name_en: "Metformin", name_ar: "ميتفورمين", generic_name: "Metformin HCl", atc_code: "A10BA02", form: "Tablet", strength: "500 mg", batch_number: "MF-23880", expiry_date: inDays(28), quantity_on_hand: 1240, quantity_reserved: 0, reorder_level: 500, unit: "tablet", unit_cost: 0.18, location: "Main store, A-20", controlled_schedule: null, high_alert: false, requires_refrigeration: false, supplier_name: "Tabuk Pharmaceuticals", status: "active", metadata: { expiry_warning: true }, created_at: ts(300), updated_at: ts(3) },
  { id: "ph-08", workspace_id: W, drug_code: "DRG-00812", name_en: "Co-amoxiclav", name_ar: "كو-أموكسيكلاف", generic_name: "Amoxicillin/Clavulanic acid", atc_code: "J01CR02", form: "Vial", strength: "1.2 g", batch_number: "CA-24601", expiry_date: inDays(200), quantity_on_hand: 176, quantity_reserved: 15, reorder_level: 80, unit: "vial", unit_cost: 6.90, location: "Main store, C-01", controlled_schedule: null, high_alert: false, requires_refrigeration: false, supplier_name: "Jamjoom Pharma", status: "active", metadata: {}, created_at: ts(80), updated_at: hrs(6) },
  { id: "ph-09", workspace_id: W, drug_code: "DRG-00903", name_en: "Noradrenaline", name_ar: "نورأدرينالين", generic_name: "Norepinephrine bitartrate", atc_code: "C01CA03", form: "Ampoule", strength: "4 mg/4 mL", batch_number: "NA-24220", expiry_date: inDays(160), quantity_on_hand: 64, quantity_reserved: 8, reorder_level: 30, unit: "ampoule", unit_cost: 14.20, location: "ICU satellite store", controlled_schedule: null, high_alert: true, requires_refrigeration: false, supplier_name: "SPIMACO", status: "active", metadata: { double_check_required: true }, created_at: ts(50), updated_at: hrs(1) },
  { id: "ph-10", workspace_id: W, drug_code: "DRG-01015", name_en: "Ceftriaxone", name_ar: "سيفترياكسون", generic_name: "Ceftriaxone sodium", atc_code: "J01DD04", form: "Vial", strength: "1 g", batch_number: "CX-23990", expiry_date: ts(10), quantity_on_hand: 34, quantity_reserved: 0, reorder_level: 60, unit: "vial", unit_cost: 5.40, location: "Quarantine shelf", controlled_schedule: null, high_alert: false, requires_refrigeration: false, supplier_name: "Jamjoom Pharma", status: "expired", metadata: { pending_destruction: true }, created_at: ts(320), updated_at: ts(10) },
  { id: "ph-11", workspace_id: W, drug_code: "DRG-01102", name_en: "Linagliptin", name_ar: "ليناغليبتين", generic_name: "Linagliptin", atc_code: "A10BH05", form: "Tablet", strength: "5 mg", batch_number: "LG-24455", expiry_date: inDays(500), quantity_on_hand: 380, quantity_reserved: 90, reorder_level: 120, unit: "tablet", unit_cost: 3.10, location: "Outpatient pharmacy, D-06", controlled_schedule: null, high_alert: false, requires_refrigeration: false, supplier_name: "Boehringer Ingelheim", status: "active", metadata: {}, created_at: ts(40), updated_at: hrs(29) },
  { id: "ph-12", workspace_id: W, drug_code: "DRG-01188", name_en: "Prednisolone", name_ar: "بريدنيزولون", generic_name: "Prednisolone", atc_code: "H02AB06", form: "Tablet", strength: "5 mg", batch_number: "PR-24210", expiry_date: inDays(350), quantity_on_hand: 96, quantity_reserved: 42, reorder_level: 300, unit: "tablet", unit_cost: 0.22, location: "Main store, A-15", controlled_schedule: null, high_alert: false, requires_refrigeration: false, supplier_name: "Tabuk Pharmaceuticals", status: "active", metadata: { below_reorder: true }, created_at: ts(110), updated_at: mins(70) },
];

export const DEMO_DISPENSES: T<"dispenses">[] = [
  { id: "disp-01", workspace_id: W, dispense_number: "DSP-2026-55120", prescription_id: "rx-01", order_id: null, encounter_id: "enc-14", patient_id: "pt-14", patient_name: "Saud Al-Amri", stock_id: "ph-01", drug_name: "Paracetamol 500 mg", batch_number: "PC-24118", quantity: 28, unit: "tablet", dispense_type: "discharge", status: "collected", verified_by: "Dr. Huda Al-Qarni", dispensed_by: "Pharm. Nasser Al-Dawood", dispensed_at: hrs(25), counselled: true, total_cost: 3.36, metadata: {}, created_at: hrs(26), updated_at: hrs(25) },
  { id: "disp-02", workspace_id: W, dispense_number: "DSP-2026-55121", prescription_id: "rx-02", order_id: null, encounter_id: "enc-14", patient_id: "pt-14", patient_name: "Saud Al-Amri", stock_id: null, drug_name: "Ibuprofen 400 mg", batch_number: "IB-24310", quantity: 15, unit: "tablet", dispense_type: "discharge", status: "collected", verified_by: "Dr. Huda Al-Qarni", dispensed_by: "Pharm. Nasser Al-Dawood", dispensed_at: hrs(25), counselled: true, total_cost: 2.25, metadata: {}, created_at: hrs(26), updated_at: hrs(25) },
  { id: "disp-03", workspace_id: W, dispense_number: "DSP-2026-55208", prescription_id: null, order_id: "ord-08", encounter_id: "enc-06", patient_id: "pt-06", patient_name: "Abdullah Al-Shehri", stock_id: "ph-03", drug_name: "Meropenem 1 g", batch_number: "MP-24552", quantity: 3, unit: "vial", dispense_type: "inpatient", status: "dispensed", verified_by: "Dr. Huda Al-Qarni", dispensed_by: "Pharm. Reem Al-Otaibi", dispensed_at: hrs(8), counselled: false, total_cost: 115.50, metadata: { daily_supply: true }, created_at: hrs(9), updated_at: hrs(8) },
  { id: "disp-04", workspace_id: W, dispense_number: "DSP-2026-55230", prescription_id: null, order_id: "ord-24", encounter_id: "enc-08", patient_id: "pt-08", patient_name: "Ibrahim Al-Zahrani", stock_id: "ph-02", drug_name: "Morphine 10 mg/mL", batch_number: "MO-24009", quantity: 2, unit: "ampoule", dispense_type: "ward_stock", status: "dispensed", verified_by: "Dr. Huda Al-Qarni", dispensed_by: "Pharm. Reem Al-Otaibi", dispensed_at: hrs(19), counselled: false, total_cost: 9.60, metadata: { cd_register_entry: "CD-2026-0881", witnessed: true }, created_at: hrs(19), updated_at: hrs(19) },
  { id: "disp-05", workspace_id: W, dispense_number: "DSP-2026-55302", prescription_id: "rx-03", order_id: null, encounter_id: "enc-03", patient_id: "pt-03", patient_name: "Fatima Al-Harbi", stock_id: "ph-11", drug_name: "Linagliptin 5 mg", batch_number: "LG-24455", quantity: 90, unit: "tablet", dispense_type: "outpatient", status: "verified", verified_by: "Dr. Huda Al-Qarni", dispensed_by: null, dispensed_at: null, counselled: false, total_cost: 279.00, metadata: { awaiting_collection: true }, created_at: hrs(29), updated_at: hrs(28) },
  { id: "disp-06", workspace_id: W, dispense_number: "DSP-2026-55340", prescription_id: null, order_id: "ord-27", encounter_id: "enc-09", patient_id: "pt-09", patient_name: "Hessa Al-Subaie", stock_id: "ph-06", drug_name: "Oxaliplatin 150 mg", batch_number: "OX-24118", quantity: 2, unit: "vial", dispense_type: "inpatient", status: "dispensed", verified_by: "Dr. Huda Al-Qarni", dispensed_by: "Pharm. Aseel Al-Munif", dispensed_at: hrs(6.5), counselled: false, total_cost: 1240.00, metadata: { compounded_in_isolator: true, double_checked_by: "Pharm. Reem Al-Otaibi" }, created_at: hrs(7), updated_at: hrs(6.5) },
  { id: "disp-07", workspace_id: W, dispense_number: "DSP-2026-55355", prescription_id: "rx-07", order_id: null, encounter_id: "enc-13", patient_id: "pt-13", patient_name: "Reem Al-Faisal", stock_id: null, drug_name: "Levothyroxine 75 mcg", batch_number: "LT-24118", quantity: 90, unit: "tablet", dispense_type: "outpatient", status: "collected", verified_by: "Dr. Huda Al-Qarni", dispensed_by: "Pharm. Nasser Al-Dawood", dispensed_at: hrs(45), counselled: true, total_cost: 42.30, metadata: {}, created_at: hrs(46), updated_at: hrs(45) },
  { id: "disp-08", workspace_id: W, dispense_number: "DSP-2026-55401", prescription_id: null, order_id: "ord-20", encounter_id: "enc-12", patient_id: "pt-12", patient_name: "Turki Al-Malki", stock_id: "ph-05", drug_name: "Salbutamol 5 mg nebule", batch_number: "SB-24330", quantity: 4, unit: "nebule", dispense_type: "emergency", status: "dispensed", verified_by: null, dispensed_by: "Pharm. Aseel Al-Munif", dispensed_at: mins(72), counselled: false, total_cost: 5.40, metadata: { from_ed_stock: true }, created_at: mins(74), updated_at: mins(72) },
];
